-- Written by `npm run db:seed` from src/lib/categories and src/lib/templates.
-- Do not edit by hand: change the catalogues, then run the script again.

insert into public.templates (id, name, data, position) values
  ('marigold', 'Marigold Gate', '{"id":"marigold","name":"Marigold Gate","description":"Gilded gates that part on a marigold mandala, with sky lanterns and Raag Yaman.","occasion":"wedding","scene":{"format":"gate-fold","motif":"mandala","petals":{"colours":["marigold","card-accent","marigold-strong","rose"],"size":1},"lanterns":true},"colours":{"paper":"card-ivory","ink":"card-ink","inkMuted":"card-ink-muted","gold":"card-gold","goldText":"card-gold-text","accent":"card-accent","accentText":"card-accent-text","back":"card-back"},"fonts":{"names":{"font":"display","italic":false,"uppercase":false,"tracking":0,"scale":1},"labels":{"font":"label","italic":false,"uppercase":true,"tracking":0.3,"scale":1},"body":{"font":"sans","italic":true,"uppercase":false,"tracking":0,"scale":1}},"music":{"raga":"yaman"},"slots":[{"id":"doorLeft","sample":"Shubh"},{"id":"doorRight","sample":"Vivah"},{"id":"blessing","sample":""},{"id":"families","sample":"Together with their families"},{"id":"first","sample":"Aarav"},{"id":"joiner","sample":"&"},{"id":"second","sample":"Meera"},{"id":"line","sample":"invite you to celebrate their wedding"},{"id":"date","sample":"Saturday, 12 December 2026"},{"id":"venue","sample":"Pichola Lakeside Gardens, Udaipur"}]}'::jsonb, 0),
  ('rose', 'Rose Garden', '{"id":"rose","name":"Rose Garden","description":"Climbing roses on blush stock, a rose wreath on the gates, and Raag Khamaj.","occasion":"wedding","scene":{"format":"gate-fold","motif":"roses","petals":{"colours":["tpl-rose-ornament","tpl-rose-accent","rose","petal-blush"],"size":1.1},"lanterns":false},"colours":{"paper":"tpl-rose-paper","ink":"tpl-rose-ink","inkMuted":"tpl-rose-ink","gold":"tpl-rose-ornament","goldText":"tpl-rose-accent","accent":"tpl-rose-leaf","accentText":"tpl-rose-accent","back":"tpl-rose-back"},"fonts":{"names":{"font":"display","italic":true,"uppercase":false,"tracking":0,"scale":1.04},"labels":{"font":"label","italic":false,"uppercase":true,"tracking":0.3,"scale":1},"body":{"font":"sans","italic":true,"uppercase":false,"tracking":0,"scale":1}},"music":{"raga":"khamaj"},"slots":[{"id":"doorLeft","sample":"With"},{"id":"doorRight","sample":"Love"},{"id":"blessing","sample":""},{"id":"families","sample":"With joy in their hearts"},{"id":"first","sample":"Rohan"},{"id":"joiner","sample":"and"},{"id":"second","sample":"Isha"},{"id":"line","sample":"would love you to join them as they begin their life together"},{"id":"date","sample":"Sunday, 14 February 2027"},{"id":"venue","sample":"The Rose Terrace, Bengaluru"}]}'::jsonb, 1),
  ('emerald', 'Emerald Palace', '{"id":"emerald","name":"Emerald Palace","description":"Palace doors with a jaali arch on deep emerald, jasmine, lanterns and Raag Bihag.","occasion":"wedding","scene":{"format":"gate-fold","motif":"palace","petals":{"colours":["petal-jasmine","tpl-emerald-accent","petal-jasmine"],"size":0.75},"lanterns":true},"colours":{"paper":"tpl-emerald-paper","ink":"tpl-emerald-ink","inkMuted":"tpl-emerald-ink","gold":"tpl-emerald-ornament","goldText":"tpl-emerald-accent","accent":"tpl-emerald-ruby","accentText":"tpl-emerald-accent","back":"tpl-emerald-back"},"fonts":{"names":{"font":"display","italic":false,"uppercase":false,"tracking":0,"scale":1},"labels":{"font":"label","italic":false,"uppercase":true,"tracking":0.22,"scale":1},"body":{"font":"sans","italic":true,"uppercase":false,"tracking":0,"scale":1}},"music":{"raga":"bihag"},"slots":[{"id":"doorLeft","sample":"The"},{"id":"doorRight","sample":"Wedding"},{"id":"blessing","sample":""},{"id":"families","sample":"The Reddy and Rao families"},{"id":"first","sample":"Kabir"},{"id":"joiner","sample":"&"},{"id":"second","sample":"Zoya"},{"id":"line","sample":"request the honour of your presence at their wedding"},{"id":"date","sample":"Friday, 22 January 2027"},{"id":"venue","sample":"Moti Mahal Lawns, Hyderabad"}]}'::jsonb, 2),
  ('scroll', 'Royal Scroll', '{"id":"scroll","name":"Royal Scroll","description":"A parchment scroll on carved rods, sealed in vermilion, with Raag Desh.","occasion":"wedding","scene":{"format":"gate-fold","motif":"scroll","petals":{"colours":["marigold","card-accent","tpl-scroll-vermilion"],"size":1},"lanterns":true},"colours":{"paper":"tpl-scroll-paper","ink":"tpl-scroll-ink","inkMuted":"tpl-scroll-ink","gold":"tpl-scroll-ornament","goldText":"tpl-scroll-accent","accent":"tpl-scroll-vermilion","accentText":"tpl-scroll-accent","back":"tpl-scroll-back"},"fonts":{"names":{"font":"display","italic":false,"uppercase":false,"tracking":0,"scale":1},"labels":{"font":"label","italic":false,"uppercase":true,"tracking":0.24,"scale":1},"body":{"font":"sans","italic":true,"uppercase":false,"tracking":0,"scale":1}},"music":{"raga":"desh"},"slots":[{"id":"doorLeft","sample":"Shubh"},{"id":"doorRight","sample":"Lagna"},{"id":"blessing","sample":"Shri Ganeshaya Namah"},{"id":"families","sample":"The Rathore and Sisodia families"},{"id":"first","sample":"Vikram"},{"id":"joiner","sample":"weds"},{"id":"second","sample":"Ananya"},{"id":"line","sample":"seek your blessings as they begin their journey together"},{"id":"date","sample":"Thursday, 26 November 2026"},{"id":"venue","sample":"Umaid Haveli, Jodhpur"}]}'::jsonb, 3),
  ('monogram', 'Minimal Monogram', '{"id":"monogram","name":"Minimal Monogram","description":"Quiet stone-white stock, your initials in large type, and Raag Bhupali.","occasion":"wedding","scene":{"format":"gate-fold","motif":"monogram","petals":{"colours":["petal-jasmine","tpl-monogram-ornament"],"size":0.7},"lanterns":false},"colours":{"paper":"tpl-monogram-paper","ink":"tpl-monogram-ink","inkMuted":"tpl-monogram-ink","gold":"tpl-monogram-ornament","goldText":"tpl-monogram-accent","accent":"tpl-monogram-ornament","accentText":"tpl-monogram-accent","back":"tpl-monogram-back"},"fonts":{"names":{"font":"label","italic":false,"uppercase":true,"tracking":0.34,"scale":0.5},"labels":{"font":"label","italic":false,"uppercase":true,"tracking":0.28,"scale":0.92},"body":{"font":"sans","italic":false,"uppercase":false,"tracking":0,"scale":1}},"music":{"raga":"bhupali","tempo":72},"slots":[{"id":"families","sample":"Together with their families"},{"id":"first","sample":"Dev"},{"id":"joiner","sample":"&"},{"id":"second","sample":"Tara"},{"id":"line","sample":"are getting married"},{"id":"date","sample":"Saturday, 6 March 2027"},{"id":"venue","sample":"The Glasshouse, Mumbai"}]}'::jsonb, 4),
  ('kasavu', 'Kerala Kasavu', '{"id":"kasavu","name":"Kerala Kasavu","description":"Gold kasavu borders and brass nilavilakku lamps, jasmine, and Raag Madhyamavati.","occasion":"wedding","scene":{"format":"gate-fold","motif":"kasavu","petals":{"colours":["petal-jasmine","marigold","petal-jasmine"],"size":0.8},"lanterns":false},"colours":{"paper":"tpl-kasavu-paper","ink":"tpl-kasavu-ink","inkMuted":"tpl-kasavu-ink","gold":"tpl-kasavu-ornament","goldText":"tpl-kasavu-accent","accent":"tpl-kasavu-kumkum","accentText":"tpl-kasavu-accent","back":"tpl-kasavu-back"},"fonts":{"names":{"font":"display","italic":false,"uppercase":false,"tracking":0,"scale":1},"labels":{"font":"label","italic":false,"uppercase":true,"tracking":0.3,"scale":1},"body":{"font":"sans","italic":true,"uppercase":false,"tracking":0,"scale":1}},"music":{"raga":"madhyamavati"},"slots":[{"id":"doorLeft","sample":"Shubha"},{"id":"doorRight","sample":"Muhurtham"},{"id":"blessing","sample":""},{"id":"families","sample":"The Nair and Menon families"},{"id":"first","sample":"Arjun"},{"id":"joiner","sample":"&"},{"id":"second","sample":"Lakshmi"},{"id":"line","sample":"invite you to bless them on their wedding day"},{"id":"date","sample":"Sunday, 17 January 2027 · 10.30 am"},{"id":"venue","sample":"Sree Krishna Auditorium, Guruvayur"}]}'::jsonb, 5)
on conflict (id) do update set name = excluded.name, data = excluded.data, position = excluded.position;

insert into public.categories (id, "group", names, icon, priority, season, regions, functions, schedule, rsvp_questions, wording, position) values
  ('wedding', 'wedding-journey', '{"en":"Wedding","hi":"विवाह","mr":"लग्न","gu":"લગ્ન","bn":"বিয়ে","ta":"திருமணம்","te":"పెళ్లి","kn":"ಮದುವೆ","ml":"വിവാഹം","pa":"ਵਿਆਹ"}'::jsonb, 'flame', 90, array[9, 10, 11, 12, 1, 2, 3, 4, 5]::smallint[], array[]::text[], '{"planned":["wedding"],"suggested":["haldi","mehendi","sangeet","wedding","reception"],"primary":"wedding"}'::jsonb, 'full', array['meal', 'arrival', 'stay', 'pickup']::text[], '{}'::jsonb, 0),
  ('engagement', 'wedding-journey', '{"en":"Engagement","hi":"सगाई","mr":"साखरपुडा","gu":"સગાઈ","bn":"বাগদান","ta":"நிச்சயதார்த்தம்","te":"నిశ్చితార్థం","kn":"ನಿಶ್ಚಿತಾರ್ಥ","ml":"വിവാഹനിശ്ചയം","pa":"ਮੰਗਣੀ"}'::jsonb, 'ring', 70, array[6, 7, 8, 9, 10]::smallint[], array[]::text[], '{"planned":["engagement"],"suggested":["engagement"],"primary":"engagement"}'::jsonb, 'full', array['meal']::text[], '{"doorLeft":"Shubh","doorRight":"Sagai","line":"invite you to celebrate their engagement"}'::jsonb, 1),
  ('save-the-date', 'wedding-journey', '{"en":"Save the date","hi":"तारीख़ याद रखें","mr":"तारीख लक्षात ठेवा","gu":"તારીખ યાદ રાખો","bn":"তারিখটি মনে রাখুন","ta":"தேதியை நினைவில் வையுங்கள்","te":"తేదీ గుర్తుంచుకోండి","kn":"ದಿನಾಂಕ ನೆನಪಿಡಿ","ml":"തീയതി ഓർത്തുവെക്കൂ","pa":"ਤਾਰੀਖ਼ ਯਾਦ ਰੱਖੋ"}'::jsonb, 'calendar', 60, array[6, 7, 8, 9, 10]::smallint[], array[]::text[], '{"planned":["wedding"],"suggested":["wedding"],"primary":"wedding"}'::jsonb, 'date-only', array[]::text[], '{"doorLeft":"Save the","doorRight":"Date","families":"Mark your calendar","line":"are getting married. Formal invitation to follow."}'::jsonb, 2),
  ('roka', 'wedding-journey', '{"en":"Roka","hi":"रोका","mr":"रोका","gu":"રોકા","bn":"রোকা","ta":"ரோகா","te":"రోకా","kn":"ರೋಕಾ","ml":"റോക്ക","pa":"ਰੋਕਾ"}'::jsonb, 'gem', 55, array[6, 7, 8, 9, 10]::smallint[], array['PB', 'HR', 'DL', 'CH', 'HP', 'JK', 'UP', 'UT']::text[], '{"planned":["roka"],"suggested":["roka","engagement"],"primary":"roka"}'::jsonb, 'full', array['meal']::text[], '{"doorLeft":"Shubh","doorRight":"Roka","line":"seek your blessings at their roka ceremony"}'::jsonb, 3),
  ('haldi', 'wedding-journey', '{"en":"Haldi","hi":"हल्दी","mr":"हळद","gu":"પીઠી","bn":"গায়ে হলুদ","ta":"மஞ்சள் நீராட்டு","te":"పసుపు","kn":"ಅರಿಶಿನ ಶಾಸ್ತ್ರ","ml":"ഹൽദി","pa":"ਹਲਦੀ"}'::jsonb, 'turmeric', 50, array[9, 10, 11, 12, 1, 2, 3, 4, 5]::smallint[], array[]::text[], '{"planned":["haldi"],"suggested":["haldi","mehendi"],"primary":"haldi"}'::jsonb, 'full', array[]::text[], '{"doorLeft":"Haldi","doorRight":"Rasam","line":"invite you to shower them with turmeric and blessings"}'::jsonb, 4),
  ('mehendi', 'wedding-journey', '{"en":"Mehendi","hi":"मेहंदी","mr":"मेहंदी","gu":"મહેંદી","bn":"মেহেন্দি","ta":"மெஹந்தி","te":"మెహందీ","kn":"ಮೆಹಂದಿ","ml":"മെഹന്ദി","pa":"ਮਹਿੰਦੀ"}'::jsonb, 'henna', 50, array[9, 10, 11, 12, 1, 2, 3, 4, 5]::smallint[], array['RJ', 'GJ', 'MP', 'MH', 'PB', 'HR', 'DL', 'CH', 'HP', 'JK', 'UP', 'UT']::text[], '{"planned":["mehendi"],"suggested":["mehendi","haldi","sangeet"],"primary":"mehendi"}'::jsonb, 'full', array['song']::text[], '{"doorLeft":"Mehendi","doorRight":"Raat","line":"invite you to an afternoon of henna, songs and laughter"}'::jsonb, 5),
  ('sangeet', 'wedding-journey', '{"en":"Sangeet","hi":"संगीत","mr":"संगीत","gu":"સંગીત","bn":"সংগীত","ta":"சங்கீத்","te":"సంగీత్","kn":"ಸಂಗೀತ್","ml":"സംഗീത്","pa":"ਸੰਗੀਤ"}'::jsonb, 'music', 50, array[9, 10, 11, 12, 1, 2, 3, 4, 5]::smallint[], array['RJ', 'GJ', 'MH', 'PB', 'HR', 'DL', 'CH', 'HP', 'JK', 'UP', 'UT']::text[], '{"planned":["sangeet"],"suggested":["sangeet","mehendi"],"primary":"sangeet"}'::jsonb, 'full', array['song', 'meal']::text[], '{"doorLeft":"Sangeet","doorRight":"Sandhya","line":"invite you to an evening of music and dance"}'::jsonb, 6),
  ('reception', 'wedding-journey', '{"en":"Reception","hi":"स्वागत समारोह","mr":"स्वागत समारंभ","gu":"સ્વાગત સમારંભ","bn":"বৌভাত","ta":"வரவேற்பு","te":"రిసెప్షన్","kn":"ಆರತಕ್ಷತೆ","ml":"സ്വീകരണം","pa":"ਰਿਸੈਪਸ਼ਨ"}'::jsonb, 'celebrate', 45, array[9, 10, 11, 12, 1, 2, 3, 4, 5]::smallint[], array[]::text[], '{"planned":["reception"],"suggested":["reception"],"primary":"reception"}'::jsonb, 'full', array['meal']::text[], '{"doorLeft":"Swagat","doorRight":"Samaroh","line":"invite you to dinner as they celebrate their marriage"}'::jsonb, 7)
on conflict (id) do update set "group" = excluded."group", names = excluded.names, icon = excluded.icon,
  priority = excluded.priority, season = excluded.season, regions = excluded.regions,
  functions = excluded.functions, schedule = excluded.schedule,
  rsvp_questions = excluded.rsvp_questions, wording = excluded.wording, position = excluded.position;

delete from public.category_templates;
insert into public.category_templates (category_id, template_id, position) values
  ('wedding', 'marigold', 0),
  ('wedding', 'rose', 1),
  ('wedding', 'emerald', 2),
  ('wedding', 'scroll', 3),
  ('wedding', 'monogram', 4),
  ('wedding', 'kasavu', 5),
  ('engagement', 'rose', 0),
  ('engagement', 'monogram', 1),
  ('engagement', 'marigold', 2),
  ('engagement', 'emerald', 3),
  ('save-the-date', 'monogram', 0),
  ('save-the-date', 'rose', 1),
  ('save-the-date', 'marigold', 2),
  ('roka', 'marigold', 0),
  ('roka', 'rose', 1),
  ('roka', 'emerald', 2),
  ('haldi', 'marigold', 0),
  ('haldi', 'kasavu', 1),
  ('haldi', 'rose', 2),
  ('mehendi', 'rose', 0),
  ('mehendi', 'emerald', 1),
  ('mehendi', 'marigold', 2),
  ('sangeet', 'emerald', 0),
  ('sangeet', 'scroll', 1),
  ('sangeet', 'marigold', 2),
  ('reception', 'monogram', 0),
  ('reception', 'emerald', 1),
  ('reception', 'scroll', 2),
  ('reception', 'rose', 3);
