import type { Category } from "./schema";

/*
 * The launch categories: the wedding journey. Plain data in the shape of categorySchema,
 * so Step 8 can seed the database from this file and Step 23 can add birthdays, baby,
 * festivals and more without code changes.
 *
 * Names in Indian languages are the common words families use; they get a native
 * speaker's review with the rest of the translations in Step 12.
 */

/** Months when wedding invites go out: September to May, skipping the monsoon. */
const WEDDING_SEASON = [9, 10, 11, 12, 1, 2, 3, 4, 5];
/** Roka, engagement and save-the-dates come a few months before the season. */
const EARLY_SEASON = [6, 7, 8, 9, 10];
/** Birthdays, anniversaries and parties happen all year. */
const ALL_YEAR = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];
/** Diwali falls in October or November; its invites go out from September. */
const DIWALI_SEASON = [9, 10, 11];

const NORTH = ["PB", "HR", "DL", "CH", "HP", "JK", "UP", "UT"] as const;

export const CATEGORIES = {
  wedding: {
    id: "wedding",
    group: "wedding-journey",
    names: {
      en: "Wedding",
      hi: "विवाह",
      mr: "लग्न",
      gu: "લગ્ન",
      bn: "বিয়ে",
      ta: "திருமணம்",
      te: "పెళ్లి",
      kn: "ಮದುವೆ",
      ml: "വിവാഹം",
      pa: "ਵਿਆਹ",
    },
    icon: "flame",
    priority: 90,
    season: WEDDING_SEASON,
    regions: [],
    functions: {
      planned: ["wedding"],
      suggested: ["haldi", "mehendi", "sangeet", "wedding", "reception"],
      primary: "wedding",
    },
    schedule: "full",
    rsvpQuestions: ["meal", "arrival", "stay", "pickup"],
    templates: [
      "marigold",
      "rose",
      "emerald",
      "scroll",
      "monogram",
      "kasavu",
      "rangmahal",
      "paithani",
      "bandhani",
      "alpona",
      "gopuram",
      "phulkari",
    ],
    // Each design keeps its own wedding wording
    wording: {},
  },
  engagement: {
    id: "engagement",
    group: "wedding-journey",
    names: {
      en: "Engagement",
      hi: "सगाई",
      mr: "साखरपुडा",
      gu: "સગાઈ",
      bn: "বাগদান",
      ta: "நிச்சயதார்த்தம்",
      te: "నిశ్చితార్థం",
      kn: "ನಿಶ್ಚಿತಾರ್ಥ",
      ml: "വിവാഹനിശ്ചയം",
      pa: "ਮੰਗਣੀ",
    },
    icon: "ring",
    priority: 70,
    season: EARLY_SEASON,
    regions: [],
    functions: { planned: ["engagement"], suggested: ["engagement"], primary: "engagement" },
    schedule: "full",
    rsvpQuestions: ["meal"],
    templates: ["rose", "monogram", "marigold", "emerald", "paithani", "alpona"],
    wording: {
      doorLeft: "Shubh",
      doorRight: "Sagai",
      line: "invite you to celebrate their engagement",
    },
  },
  "save-the-date": {
    id: "save-the-date",
    group: "wedding-journey",
    names: {
      en: "Save the date",
      hi: "तारीख़ याद रखें",
      mr: "तारीख लक्षात ठेवा",
      gu: "તારીખ યાદ રાખો",
      bn: "তারিখটি মনে রাখুন",
      ta: "தேதியை நினைவில் வையுங்கள்",
      te: "తేదీ గుర్తుంచుకోండి",
      kn: "ದಿನಾಂಕ ನೆನಪಿಡಿ",
      ml: "തീയതി ഓർത്തുവെക്കൂ",
      pa: "ਤਾਰੀਖ਼ ਯਾਦ ਰੱਖੋ",
    },
    icon: "calendar",
    priority: 60,
    season: EARLY_SEASON,
    regions: [],
    functions: { planned: ["wedding"], suggested: ["wedding"], primary: "wedding" },
    schedule: "date-only",
    rsvpQuestions: [],
    templates: ["monogram", "rose", "marigold"],
    wording: {
      doorLeft: "Save the",
      doorRight: "Date",
      families: "Mark your calendar",
      line: "are getting married. Formal invitation to follow.",
    },
  },
  roka: {
    id: "roka",
    group: "wedding-journey",
    names: {
      en: "Roka",
      hi: "रोका",
      mr: "रोका",
      gu: "રોકા",
      bn: "রোকা",
      ta: "ரோகா",
      te: "రోకా",
      kn: "ರೋಕಾ",
      ml: "റോക്ക",
      pa: "ਰੋਕਾ",
    },
    icon: "gem",
    priority: 55,
    season: EARLY_SEASON,
    regions: [...NORTH],
    functions: { planned: ["roka"], suggested: ["roka", "engagement"], primary: "roka" },
    schedule: "full",
    rsvpQuestions: ["meal"],
    templates: ["marigold", "rose", "emerald", "rangmahal", "phulkari"],
    wording: {
      doorLeft: "Shubh",
      doorRight: "Roka",
      line: "seek your blessings at their roka ceremony",
    },
  },
  haldi: {
    id: "haldi",
    group: "wedding-journey",
    names: {
      en: "Haldi",
      hi: "हल्दी",
      mr: "हळद",
      gu: "પીઠી",
      bn: "গায়ে হলুদ",
      ta: "மஞ்சள் நீராட்டு",
      te: "పసుపు",
      kn: "ಅರಿಶಿನ ಶಾಸ್ತ್ರ",
      ml: "ഹൽദി",
      pa: "ਹਲਦੀ",
    },
    icon: "turmeric",
    priority: 50,
    season: WEDDING_SEASON,
    regions: [],
    functions: { planned: ["haldi"], suggested: ["haldi", "mehendi"], primary: "haldi" },
    schedule: "full",
    rsvpQuestions: [],
    templates: ["marigold", "kasavu", "rose", "gopuram", "paithani"],
    wording: {
      doorLeft: "Haldi",
      doorRight: "Rasam",
      line: "invite you to shower them with turmeric and blessings",
    },
  },
  mehendi: {
    id: "mehendi",
    group: "wedding-journey",
    names: {
      en: "Mehendi",
      hi: "मेहंदी",
      mr: "मेहंदी",
      gu: "મહેંદી",
      bn: "মেহেন্দি",
      ta: "மெஹந்தி",
      te: "మెహందీ",
      kn: "ಮೆಹಂದಿ",
      ml: "മെഹന്ദി",
      pa: "ਮਹਿੰਦੀ",
    },
    icon: "henna",
    priority: 50,
    season: WEDDING_SEASON,
    regions: ["RJ", "GJ", "MP", "MH", ...NORTH],
    functions: {
      planned: ["mehendi"],
      suggested: ["mehendi", "haldi", "sangeet"],
      primary: "mehendi",
    },
    schedule: "full",
    rsvpQuestions: ["song"],
    templates: ["rose", "emerald", "marigold", "bandhani", "paithani"],
    wording: {
      doorLeft: "Mehendi",
      doorRight: "Raat",
      line: "invite you to an afternoon of henna, songs and laughter",
    },
  },
  sangeet: {
    id: "sangeet",
    group: "wedding-journey",
    names: {
      en: "Sangeet",
      hi: "संगीत",
      mr: "संगीत",
      gu: "સંગીત",
      bn: "সংগীত",
      ta: "சங்கீத்",
      te: "సంగీత్",
      kn: "ಸಂಗೀತ್",
      ml: "സംഗീത്",
      pa: "ਸੰਗੀਤ",
    },
    icon: "music",
    priority: 50,
    season: WEDDING_SEASON,
    regions: ["RJ", "GJ", "MH", ...NORTH],
    functions: { planned: ["sangeet"], suggested: ["sangeet", "mehendi"], primary: "sangeet" },
    schedule: "full",
    rsvpQuestions: ["song", "meal"],
    templates: ["emerald", "scroll", "marigold", "bandhani", "phulkari", "rangmahal"],
    wording: {
      doorLeft: "Sangeet",
      doorRight: "Sandhya",
      line: "invite you to an evening of music and dance",
    },
  },
  reception: {
    id: "reception",
    group: "wedding-journey",
    names: {
      en: "Reception",
      hi: "स्वागत समारोह",
      mr: "स्वागत समारंभ",
      gu: "સ્વાગત સમારંભ",
      bn: "বৌভাত",
      ta: "வரவேற்பு",
      te: "రిసెప్షన్",
      kn: "ಆರತಕ್ಷತೆ",
      ml: "സ്വീകരണം",
      pa: "ਰਿਸੈਪਸ਼ਨ",
    },
    icon: "celebrate",
    priority: 45,
    season: WEDDING_SEASON,
    regions: [],
    functions: { planned: ["reception"], suggested: ["reception"], primary: "reception" },
    schedule: "full",
    rsvpQuestions: ["meal"],
    templates: ["monogram", "emerald", "scroll", "rose", "rangmahal"],
    wording: {
      doorLeft: "Swagat",
      doorRight: "Samaroh",
      line: "invite you to dinner as they celebrate their marriage",
    },
  },
  // Beyond weddings (Step 12p): each is one function with its own painted theme
  birthday: {
    id: "birthday",
    group: "birthdays",
    names: {
      en: "Birthday",
      hi: "जन्मदिन",
      mr: "वाढदिवस",
      gu: "જન્મદિવસ",
      bn: "জন্মদিন",
      ta: "பிறந்தநாள்",
      te: "పుట్టినరోజు",
      kn: "ಹುಟ್ಟುಹಬ್ಬ",
      ml: "ജന്മദിനം",
      pa: "ਜਨਮਦਿਨ",
    },
    icon: "celebrate",
    priority: 40,
    season: ALL_YEAR,
    regions: [],
    functions: { planned: ["birthday"], suggested: ["birthday"], primary: "birthday" },
    schedule: "full",
    rsvpQuestions: ["meal"],
    templates: ["rose", "marigold", "monogram"],
    wording: {
      doorLeft: "Happy",
      doorRight: "Birthday",
      blessing: "Happy birthday",
      families: "With love from the family",
      line: "invite you to a birthday party with cake, games and blessings",
    },
    people: "one",
  },
  anniversary: {
    id: "anniversary",
    group: "birthdays",
    names: {
      en: "Anniversary",
      hi: "सालगिरह",
      mr: "लग्नाचा वाढदिवस",
      gu: "લગ્નજયંતી",
      bn: "বিবাহবার্ষিকী",
      ta: "திருமண நாள்",
      te: "పెళ్లి రోజు",
      kn: "ವಿವಾಹ ವಾರ್ಷಿಕೋತ್ಸವ",
      ml: "വിവാഹ വാർഷികം",
      pa: "ਵਰ੍ਹੇਗੰਢ",
    },
    icon: "ring",
    priority: 35,
    season: ALL_YEAR,
    regions: [],
    functions: { planned: ["anniversary"], suggested: ["anniversary"], primary: "anniversary" },
    schedule: "full",
    rsvpQuestions: ["meal"],
    templates: ["rose", "emerald", "monogram"],
    wording: {
      doorLeft: "Saath",
      doorRight: "Saal",
      blessing: "Years of togetherness",
      families: "With their children and family",
      line: "invite you to celebrate their wedding anniversary",
    },
  },
  party: {
    id: "party",
    group: "parties",
    names: {
      en: "Party",
      hi: "पार्टी",
      mr: "पार्टी",
      gu: "પાર્ટી",
      bn: "পার্টি",
      ta: "விருந்து",
      te: "పార్టీ",
      kn: "ಪಾರ್ಟಿ",
      ml: "പാർട്ടി",
      pa: "ਪਾਰਟੀ",
    },
    icon: "music",
    priority: 30,
    season: ALL_YEAR,
    regions: [],
    functions: { planned: ["party"], suggested: ["party"], primary: "party" },
    schedule: "full",
    rsvpQuestions: ["meal", "song"],
    templates: ["monogram", "scroll", "emerald"],
    wording: {
      doorLeft: "You're",
      doorRight: "Invited",
      families: "Hosted by friends",
      line: "invite you to an evening of music, food and friends",
    },
    people: "one",
  },
  // A baby shower and Diwali (Step 12u): one function each, with their own painted theme
  "baby-shower": {
    id: "baby-shower",
    group: "baby",
    names: {
      en: "Baby shower",
      hi: "गोद भराई",
      mr: "डोहाळे जेवण",
      gu: "સીમંત",
      bn: "সাধ",
      ta: "வளைகாப்பு",
      te: "సీమంతం",
      kn: "ಸೀಮಂತ",
      ml: "സീമന്തം",
      pa: "ਗੋਦ ਭਰਾਈ",
    },
    icon: "flower",
    priority: 30,
    season: ALL_YEAR,
    regions: [],
    functions: { planned: ["baby-shower"], suggested: ["baby-shower"], primary: "baby-shower" },
    schedule: "full",
    rsvpQuestions: ["meal"],
    templates: ["rose", "marigold", "monogram"],
    wording: {
      doorLeft: "Godh",
      doorRight: "Bharai",
      first: "Priya",
      blessing: "Blessings for the little one",
      families: "With love from both families",
      line: "invite you to shower blessings on the mother-to-be",
    },
    people: "one",
  },
  diwali: {
    id: "diwali",
    group: "festivals",
    names: {
      en: "Diwali",
      hi: "दिवाली",
      mr: "दिवाळी",
      gu: "દિવાળી",
      bn: "দীপাবলি",
      ta: "தீபாவளி",
      te: "దీపావళి",
      kn: "ದೀಪಾವಳಿ",
      ml: "ദീപാവലി",
      pa: "ਦੀਵਾਲੀ",
    },
    icon: "diya",
    priority: 25,
    season: DIWALI_SEASON,
    regions: [],
    functions: { planned: ["diwali"], suggested: ["diwali"], primary: "diwali" },
    schedule: "full",
    rsvpQuestions: ["meal"],
    templates: ["marigold", "rose", "emerald"],
    wording: {
      doorLeft: "Shubh",
      doorRight: "Deepavali",
      first: "Diwali Milan",
      blessing: "May Lakshmi bless your home",
      families: "With love from the family",
      line: "invite you to an evening of diyas, sweets and Lakshmi puja",
    },
    people: "one",
  },
  housewarming: {
    id: "housewarming",
    group: "home-religious",
    names: {
      en: "Housewarming",
      hi: "गृह प्रवेश",
      mr: "गृहप्रवेश",
      gu: "ગૃહપ્રવેશ",
      bn: "গৃহপ্রবেশ",
      ta: "கிரகப்பிரவேசம்",
      te: "గృహప్రవేశం",
      kn: "ಗೃಹಪ್ರವೇಶ",
      ml: "ഗൃഹപ്രവേശം",
      pa: "ਗ੍ਰਹਿ ਪ੍ਰਵੇਸ਼",
    },
    icon: "flame",
    priority: 24,
    season: ALL_YEAR,
    regions: [],
    functions: { planned: ["housewarming"], suggested: ["housewarming"], primary: "housewarming" },
    schedule: "full",
    rsvpQuestions: ["meal"],
    templates: ["marigold", "rose", "emerald"],
    wording: {
      doorLeft: "Griha",
      doorRight: "Pravesh",
      first: "Sharma Niwas",
      blessing: "May this home be filled with joy",
      families: "With love from the Sharma family",
      line: "invite you to bless their new home with a puja and lunch",
    },
    people: "one",
  },
  puja: {
    id: "puja",
    group: "home-religious",
    names: {
      en: "Puja and katha",
      hi: "पूजा और कथा",
      mr: "पूजा आणि कथा",
      gu: "પૂજા અને કથા",
      bn: "পুজো ও কথা",
      ta: "பூஜை",
      te: "పూజ",
      kn: "ಪೂಜೆ",
      ml: "പൂജ",
      pa: "ਪੂਜਾ ਅਤੇ ਕਥਾ",
    },
    icon: "diya",
    priority: 24,
    season: ALL_YEAR,
    regions: [],
    functions: { planned: ["puja"], suggested: ["puja"], primary: "puja" },
    schedule: "full",
    rsvpQuestions: ["meal"],
    templates: ["marigold", "rose", "scroll"],
    wording: {
      doorLeft: "Shubh",
      doorRight: "Puja",
      first: "Satyanarayan Katha",
      blessing: "With the Lord's blessings",
      families: "With love from the Sharma family",
      line: "invite you to the puja, aarti and prasad at their home",
    },
    people: "one",
  },
  "thread-ceremony": {
    id: "thread-ceremony",
    group: "home-religious",
    names: {
      en: "Thread ceremony",
      hi: "जनेऊ संस्कार",
      mr: "मुंज",
      gu: "જનોઈ",
      bn: "উপনয়ন",
      ta: "உபநயனம்",
      te: "ఉపనయనం",
      kn: "ಉಪನಯನ",
      ml: "ഉപനയനം",
      pa: "ਜਨੇਊ ਸੰਸਕਾਰ",
    },
    icon: "flame",
    priority: 23,
    season: ALL_YEAR,
    regions: [],
    functions: {
      planned: ["thread-ceremony"],
      suggested: ["thread-ceremony"],
      primary: "thread-ceremony",
    },
    schedule: "full",
    rsvpQuestions: ["meal"],
    templates: ["marigold", "scroll", "rose"],
    wording: {
      doorLeft: "Shubh",
      doorRight: "Upanayan",
      first: "Aarav",
      blessing: "With the blessings of our elders",
      families: "With love from the Sharma family",
      line: "invite you to bless him at his thread ceremony",
    },
    people: "one",
  },
  "ganesh-chaturthi": {
    id: "ganesh-chaturthi",
    group: "festivals",
    names: {
      en: "Ganesh Chaturthi",
      hi: "गणेश चतुर्थी",
      mr: "गणेशोत्सव",
      gu: "ગણેશ ચતુર્થી",
      bn: "গণেশ চতুর্থী",
      ta: "விநாயகர் சதுர்த்தி",
      te: "వినాయక చవితి",
      kn: "ಗಣೇಶ ಚತುರ್ಥಿ",
      ml: "വിനായക ചതുർത്ഥി",
      pa: "ਗਣੇਸ਼ ਚਤੁਰਥੀ",
    },
    icon: "diya",
    priority: 23,
    season: [7, 8, 9],
    regions: ["MH", "GA", "KA", "TG", "AP", "GJ"],
    functions: {
      planned: ["ganesh-chaturthi"],
      suggested: ["ganesh-chaturthi"],
      primary: "ganesh-chaturthi",
    },
    schedule: "full",
    rsvpQuestions: ["meal"],
    templates: ["marigold", "rose", "scroll"],
    wording: {
      doorLeft: "Ganpati",
      doorRight: "Bappa Morya",
      first: "Sharma Family Ganpati",
      blessing: "Ganpati Bappa Morya",
      families: "With love from the Sharma family",
      line: "invite you for Bappa's darshan, aarti and prasad at our home",
    },
    people: "one",
  },
  navratri: {
    id: "navratri",
    group: "festivals",
    names: {
      en: "Navratri and Durga Puja",
      hi: "नवरात्रि और दुर्गा पूजा",
      mr: "नवरात्री",
      gu: "નવરાત્રી",
      bn: "দুর্গাপূজা",
      ta: "நவராத்திரி",
      te: "దసరా నవరాత్రులు",
      kn: "ನವರಾತ್ರಿ",
      ml: "നവരാത്രി",
      pa: "ਨਵਰਾਤਰੀ",
    },
    icon: "music",
    priority: 23,
    season: [8, 9, 10],
    regions: ["GJ", "WB", "MH", "RJ"],
    functions: { planned: ["navratri"], suggested: ["navratri"], primary: "navratri" },
    schedule: "full",
    rsvpQuestions: ["meal", "song"],
    templates: ["bandhani", "alpona", "marigold"],
    wording: {
      doorLeft: "Shubh",
      doorRight: "Navratri",
      first: "Navratri Utsav",
      blessing: "Jai Mata Di",
      families: "With love from the Sharma family",
      line: "invite you to nine nights of garba, aarti and bhog",
    },
    people: "one",
  },
  annaprashan: {
    id: "annaprashan",
    group: "baby",
    names: {
      en: "Annaprashan",
      hi: "अन्नप्राशन",
      mr: "उष्टावण",
      gu: "અન્નપ્રાશન",
      bn: "অন্নপ্রাশন",
      ta: "அன்னப்பிராசனம்",
      te: "అన్నప్రాశన",
      kn: "ಅನ್ನಪ್ರಾಶನ",
      ml: "ചോറൂണ്",
      pa: "ਅੰਨਪ੍ਰਾਸ਼ਨ",
    },
    icon: "flower",
    priority: 22,
    season: ALL_YEAR,
    regions: [],
    functions: { planned: ["annaprashan"], suggested: ["annaprashan"], primary: "annaprashan" },
    schedule: "full",
    rsvpQuestions: ["meal"],
    templates: ["rose", "marigold", "monogram"],
    wording: {
      doorLeft: "Shubh",
      doorRight: "Annaprashan",
      first: "Anaya",
      blessing: "Blessings for the little one",
      families: "With love from the family",
      line: "invite you to bless our little one at the first rice ceremony",
    },
    people: "one",
  },
  eid: {
    id: "eid",
    group: "festivals",
    names: {
      en: "Eid and iftar",
      hi: "ईद और इफ़्तार",
      mr: "ईद आणि इफ्तार",
      gu: "ઈદ અને ઇફ્તાર",
      bn: "ঈদ ও ইফতার",
      ta: "ரமலான் இஃப்தார்",
      te: "ఈద్ మరియు ఇఫ్తార్",
      kn: "ಈದ್ ಮತ್ತು ಇಫ್ತಾರ್",
      ml: "പെരുന്നാൾ",
      pa: "ਈਦ ਅਤੇ ਇਫ਼ਤਾਰ",
    },
    icon: "celebrate",
    priority: 22,
    season: ALL_YEAR,
    regions: [],
    functions: { planned: ["eid"], suggested: ["eid"], primary: "eid" },
    schedule: "full",
    rsvpQuestions: ["meal"],
    templates: ["emerald", "monogram", "rose"],
    wording: {
      doorLeft: "Eid",
      doorRight: "Mubarak",
      first: "Iftar Dawat",
      blessing: "Eid Mubarak",
      families: "With love from the Khan family",
      line: "invite you to break the fast with us at our iftar dawat",
    },
    people: "one",
  },
  retirement: {
    id: "retirement",
    group: "parties",
    names: {
      en: "Retirement",
      hi: "सेवानिवृत्ति",
      mr: "सेवानिवृत्ती",
      gu: "નિવૃત્તિ",
      bn: "অবসর",
      ta: "பணி ஓய்வு",
      te: "పదవీ విరమణ",
      kn: "ನಿವೃತ್ತಿ",
      ml: "വിരമിക്കൽ",
      pa: "ਸੇਵਾਮੁਕਤੀ",
    },
    icon: "celebrate",
    priority: 20,
    season: ALL_YEAR,
    regions: [],
    functions: { planned: ["retirement"], suggested: ["retirement"], primary: "retirement" },
    schedule: "full",
    rsvpQuestions: ["meal"],
    templates: ["monogram", "emerald", "rose"],
    wording: {
      doorLeft: "Happy",
      doorRight: "Retirement",
      first: "R. K. Sharma",
      blessing: "Here's to the next chapter",
      families: "With love from family and colleagues",
      line: "invite you to celebrate a career well lived",
    },
    people: "one",
  },
  janmashtami: {
    id: "janmashtami",
    group: "festivals",
    names: {
      en: "Janmashtami",
      hi: "जन्माष्टमी",
      mr: "गोकुळाष्टमी",
      gu: "જન્માષ્ટમી",
      bn: "জন্মাষ্টমী",
      ta: "கிருஷ்ண ஜெயந்தி",
      te: "కృష్ణాష్టమి",
      kn: "ಕೃಷ್ಣ ಜನ್ಮಾಷ್ಟಮಿ",
      ml: "ശ്രീകൃഷ്ണ ജയന്തി",
      pa: "ਜਨਮ ਅਸ਼ਟਮੀ",
    },
    icon: "diya",
    priority: 20,
    season: [7, 8, 9],
    regions: [],
    functions: { planned: ["janmashtami"], suggested: ["janmashtami"], primary: "janmashtami" },
    schedule: "full",
    rsvpQuestions: ["meal"],
    templates: ["marigold", "rose", "scroll"],
    wording: {
      doorLeft: "Shubh",
      doorRight: "Janmashtami",
      first: "Krishna Janmotsav",
      blessing: "Jai Shri Krishna",
      families: "With love from the Sharma family",
      line: "invite you to celebrate Krishna's birth with bhajans, jhanki and midnight aarti",
    },
    people: "one",
  },
  sankranti: {
    id: "sankranti",
    group: "festivals",
    names: {
      en: "Sankranti and Pongal",
      hi: "मकर संक्रांति",
      mr: "मकर संक्रांत",
      gu: "ઉત્તરાયણ",
      bn: "পৌষ সংক্রান্তি",
      ta: "பொங்கல்",
      te: "సంక్రాంతి",
      kn: "ಸಂಕ್ರಾಂತಿ",
      ml: "മകരസംക്രാന്തി",
      pa: "ਮਾਘੀ",
    },
    icon: "celebrate",
    priority: 20,
    season: [12, 1],
    regions: ["GJ", "TN", "AP", "TG", "KA", "MH", "RJ"],
    functions: { planned: ["sankranti"], suggested: ["sankranti"], primary: "sankranti" },
    schedule: "full",
    rsvpQuestions: ["meal"],
    templates: ["marigold", "gopuram", "bandhani"],
    wording: {
      doorLeft: "Happy",
      doorRight: "Sankranti",
      first: "Kite Day",
      blessing: "Sweet words, sweet year",
      families: "With love from the Patel family",
      line: "invite you to a day of kites, til laddoos and pongal",
    },
    people: "one",
  },
  "farewell-party": {
    id: "farewell-party",
    group: "parties",
    names: {
      en: "Farewell party",
      hi: "विदाई समारोह",
      mr: "निरोप समारंभ",
      gu: "વિદાય સમારંભ",
      bn: "বিদায় সংবর্ধনা",
      ta: "பிரியாவிடை விழா",
      te: "వీడ్కోలు వేడుక",
      kn: "ಬೀಳ್ಕೊಡುಗೆ",
      ml: "യാത്രയയപ്പ്",
      pa: "ਵਿਦਾਇਗੀ ਪਾਰਟੀ",
    },
    icon: "music",
    priority: 18,
    season: ALL_YEAR,
    regions: [],
    functions: {
      planned: ["farewell-party"],
      suggested: ["farewell-party"],
      primary: "farewell-party",
    },
    schedule: "full",
    rsvpQuestions: ["meal", "song"],
    templates: ["emerald", "monogram", "rose"],
    wording: {
      doorLeft: "Farewell",
      doorRight: "Night",
      first: "Batch of 2026",
      blessing: "Here's to new beginnings",
      families: "Hosted by the juniors",
      line: "invite you to one last evening together before new beginnings",
    },
    people: "one",
  },
  "shop-opening": {
    id: "shop-opening",
    group: "business",
    names: {
      en: "Shop opening",
      hi: "उद्घाटन",
      mr: "उद्घाटन",
      gu: "ઉદ્ઘાટન",
      bn: "উদ্বোধন",
      ta: "திறப்பு விழா",
      te: "ప్రారంభోత్సవం",
      kn: "ಉದ್ಘಾಟನೆ",
      ml: "ഉദ്ഘാടനം",
      pa: "ਉਦਘਾਟਨ",
    },
    icon: "celebrate",
    priority: 18,
    season: ALL_YEAR,
    regions: [],
    functions: { planned: ["shop-opening"], suggested: ["shop-opening"], primary: "shop-opening" },
    schedule: "full",
    rsvpQuestions: ["meal"],
    templates: ["marigold", "emerald", "monogram"],
    wording: {
      doorLeft: "Grand",
      doorRight: "Opening",
      first: "Sharma Jewellers",
      blessing: "With Shri Ganesh's blessings",
      families: "From the Sharma family and team",
      line: "invite you to the opening of our new shop with puja and refreshments",
    },
    people: "one",
  },
  onam: {
    id: "onam",
    group: "festivals",
    names: {
      en: "Onam",
      hi: "ओणम",
      mr: "ओणम",
      gu: "ઓણમ",
      bn: "ওণাম",
      ta: "ஓணம்",
      te: "ఓణం",
      kn: "ಓಣಂ",
      ml: "ഓണം",
      pa: "ਓਣਮ",
    },
    icon: "flower",
    priority: 18,
    season: [7, 8, 9],
    regions: ["KL"],
    functions: { planned: ["onam"], suggested: ["onam"], primary: "onam" },
    schedule: "full",
    rsvpQuestions: ["meal"],
    templates: ["kasavu", "marigold", "gopuram"],
    wording: {
      doorLeft: "Happy",
      doorRight: "Onam",
      first: "Onam Sadhya",
      blessing: "Onashamsakal",
      families: "With love from the Menon family",
      line: "invite you to share the Onam sadhya and pookalam with us",
    },
    people: "one",
  },
  lohri: {
    id: "lohri",
    group: "festivals",
    names: {
      en: "Lohri",
      hi: "लोहड़ी",
      mr: "लोहडी",
      gu: "લોહડી",
      bn: "লোহরি",
      ta: "லோஹ்ரி",
      te: "లోహ్రీ",
      kn: "ಲೋಹ್ರಿ",
      ml: "ലോഹ്രി",
      pa: "ਲੋਹੜੀ",
    },
    icon: "flame",
    priority: 18,
    season: [12, 1],
    regions: ["PB", "HR", "DL", "CH", "HP", "JK"],
    functions: { planned: ["lohri"], suggested: ["lohri"], primary: "lohri" },
    schedule: "full",
    rsvpQuestions: ["meal", "song"],
    templates: ["phulkari", "marigold"],
    wording: {
      doorLeft: "Happy",
      doorRight: "Lohri",
      first: "Lohri Night",
      blessing: "Lohri di lakh lakh vadhaiyan",
      families: "With love from the Sandhu family",
      line: "invite you around the bonfire for rewari, bhangra and dinner",
    },
    people: "one",
  },
  launch: {
    id: "launch",
    group: "business",
    names: {
      en: "Launch event",
      hi: "लॉन्च इवेंट",
      mr: "लॉन्च सोहळा",
      gu: "લૉન્ચ ઇવેન્ટ",
      bn: "উদ্বোধনী অনুষ্ঠান",
      ta: "அறிமுக விழா",
      te: "లాంచ్ ఈవెంట్",
      kn: "ಬಿಡುಗಡೆ ಸಮಾರಂಭ",
      ml: "ലോഞ്ച് ഇവന്റ്",
      pa: "ਲਾਂਚ ਸਮਾਗਮ",
    },
    icon: "celebrate",
    priority: 16,
    season: ALL_YEAR,
    regions: [],
    functions: { planned: ["launch"], suggested: ["launch"], primary: "launch" },
    schedule: "full",
    rsvpQuestions: ["meal"],
    templates: ["emerald", "monogram"],
    wording: {
      doorLeft: "You're",
      doorRight: "Invited",
      first: "The Aurora Launch",
      blessing: "Something new is here",
      families: "From the team",
      line: "invite you to the launch evening, with a first look and dinner",
    },
    people: "one",
  },
  christening: {
    id: "christening",
    group: "baby",
    names: {
      en: "Christening",
      hi: "बपतिस्मा",
      mr: "बाप्तिस्मा",
      gu: "બાપ્તિસ્મા",
      bn: "ব্যাপটিজম",
      ta: "ஞானஸ்நானம்",
      te: "బాప్తిస్మం",
      kn: "ದೀಕ್ಷಾಸ್ನಾನ",
      ml: "മാമ്മോദീസ",
      pa: "ਬਪਤਿਸਮਾ",
    },
    icon: "flower",
    priority: 15,
    season: ALL_YEAR,
    regions: [],
    functions: { planned: ["christening"], suggested: ["christening"], primary: "christening" },
    schedule: "full",
    rsvpQuestions: ["meal"],
    templates: ["rose", "monogram", "emerald"],
    wording: {
      doorLeft: "Holy",
      doorRight: "Baptism",
      first: "Aaron",
      blessing: "God bless our little one",
      families: "With love from the D'Souza family",
      line: "invite you to celebrate the christening of our little one, followed by lunch",
    },
    people: "one",
  },
  "prayer-meet": {
    id: "prayer-meet",
    group: "home-religious",
    names: {
      en: "Prayer meeting",
      hi: "श्रद्धांजलि सभा",
      mr: "श्रद्धांजली सभा",
      gu: "પ્રાર્થના સભા",
      bn: "স্মরণসভা",
      ta: "நினைவஞ்சலி",
      te: "సంస్మరణ సభ",
      kn: "ಶ್ರದ್ಧಾಂಜಲಿ ಸಭೆ",
      ml: "അനുസ്മരണ യോഗം",
      pa: "ਅੰਤਿਮ ਅਰਦਾਸ",
    },
    icon: "flower",
    priority: 15,
    season: ALL_YEAR,
    regions: [],
    functions: { planned: ["prayer-meet"], suggested: ["prayer-meet"], primary: "prayer-meet" },
    schedule: "full",
    rsvpQuestions: [],
    templates: ["scroll", "monogram"],
    wording: {
      doorLeft: "In Loving",
      doorRight: "Memory",
      first: "Shri R. K. Sharma",
      blessing: "Om Shanti",
      families: "The Sharma family",
      line: "request your presence at a prayer meeting in his loving memory",
    },
    people: "one",
  },
} satisfies Record<string, Category>;

export type CategoryId = keyof typeof CATEGORIES;

/** Every launch category in its base order, for pickers. */
export const CATEGORY_IDS = Object.keys(CATEGORIES) as CategoryId[];

export function isCategoryId(value: unknown): value is CategoryId {
  return typeof value === "string" && Object.hasOwn(CATEGORIES, value);
}

export function getCategory(id: CategoryId): Category {
  return CATEGORIES[id];
}
