import type * as en from "../editor";
import type { Translation } from "@/i18n/text";
import type { LeadId, TaalId } from "@/lib/templates/ids";

/* हिन्दी: निमंत्रण एडिटर (/create)। English: src/content/editor.ts. */

export const editor: Translation<typeof en.editor> = {
  metaTitle: "अपना निमंत्रण बनाएँ",
  metaDescription: "3D डिज़ाइन चुनें, नाम और रस्में जोड़ें, फिर अपना निमंत्रण देखें।",
  headerLabel: "निमंत्रण एडिटर",
  progressLabel: "निमंत्रण की प्रगति",
  progress: (step, total) => `${total} में से चरण ${step}`,
  done: "पूरा",
  designChosen: "आपका डिज़ाइन",
  changeDesign: "डिज़ाइन बदलें",
  stages: { design: "डिज़ाइन", details: "आपकी जानकारी", preview: "झलक और भेजें" },
  sections: {
    label: "आपकी जानकारी, तीन हिस्सों में",
    open: (part, summary, state) =>
      `${part}: ${summary}${state === "done" ? ", पूरा" : state === "check" ? ", एक बार देखें" : ""}। खोलें`,
    done: "पूरा",
    check: "एक बार देखें",
    edit: "बदलें",
    names: (names) => (names.length ? names.join(" और ") : "नाम जोड़ें"),
    functions: (names) =>
      names.length === 0
        ? "अपनी रस्में चुनें"
        : names.length <= 3
          ? names.join(", ")
          : `${names.slice(0, 2).join(", ")} और ${names.length - 2} और`,
    extras: (photos, music) =>
      `${photos === 0 ? "अभी कोई तस्वीर नहीं" : `${photos} तस्वीर${photos === 1 ? "" : "ें"}`} · ${music ? "संगीत चालू" : "संगीत बंद"}`,
  },
  back: "पीछे",
  next: "आगे बढ़ें",
  toPreview: "निमंत्रण देखें",
  preview: "निमंत्रण की झलक",
  showPreview: "झलक",
  previewTitle: "आपका निमंत्रण",
  livePreview: "लाइव झलक, बड़ा करके देखें",
  hideLivePreview: "लाइव झलक छिपाएँ",
  showLivePreview: "लाइव झलक दिखाएँ",
  close: "बंद करें",
  optional: "वैकल्पिक",
  characters: (used, max) => `${max} में से ${used} अक्षर`,
  fixErrors: (count) => (count === 1 ? "एक चीज़ पर ध्यान दें" : `${count} चीज़ों पर ध्यान दें`),
  errors: {
    required: "कृपया इसे भरें",
    "too-long": "यह कार्ड के लिए बहुत लंबा है",
    "no-functions": "कम से कम एक रस्म चुनें",
    "photo-needed": "यह तस्वीर जोड़ें। आपका डिज़ाइन इसे अपने फ़्रेम में दिखाता है।",
  },
  save: {
    idle: "ड्राफ़्ट इसी डिवाइस पर सहेजे जाते हैं",
    saving: "सहेज रहे हैं…",
    saved: "ड्राफ़्ट सहेजा गया",
    unavailable: "इस डिवाइस पर सहेज नहीं सकते",
  },
};

export const syncCopy: Translation<typeof en.syncCopy> = {
  idle: "आपके खाते में सहेजा जाता है",
  syncing: "सहेज रहे हैं…",
  synced: "आपके खाते में सहेजा गया",
  offline: "इस डिवाइस पर सहेजा, फिर कोशिश जारी",
  missing: "यह निमंत्रण आपके खाते में नहीं है। शायद हटा दिया गया हो।",
  switchFailed: "खुला हुआ निमंत्रण सहेज नहीं पाए, इसलिए वही खुला है। थोड़ी देर में फिर कोशिश करें।",
};

export const stepCopy: Translation<typeof en.stepCopy> = {
  occasion: {
    label: "अवसर",
    eyebrow: "अवसर चुनें",
    title: "आप क्या मना रहे हैं?",
    intro:
      "अवसर से निमंत्रण तैयार होता है: कौन-सी रस्में, कौन-से शब्द और कौन-से डिज़ाइन। बाद में बदलें तो भी आपका लिखा कुछ नहीं खोता।",
  },
  tradition: {
    label: "परंपरा",
    eyebrow: "परंपरा चुनें",
    title: "कार्ड किसकी परंपरा से बने?",
    intro:
      "परंपरा से कार्ड का शुभ चिह्न, मंगलाचरण, रस्मों के स्थानीय नाम और परिवार की शब्दावली तय होती है। सब कुछ बदला जा सकता है, और यह चरण छोड़ भी सकते हैं।",
  },
  design: {
    label: "डिज़ाइन",
    eyebrow: "डिज़ाइन चुनें",
    title: "वह डिज़ाइन चुनें जिसे मेहमान खोलेंगे",
    intro:
      "हर डिज़ाइन की अपनी पेंटिंग, अपना खुलना और अपना राग है। कभी भी बदलें, आपके लिखे सारे शब्द बने रहेंगे।",
  },
  language: {
    label: "भाषा",
    eyebrow: "कार्ड की भाषा",
    title: "आपका कार्ड किस भाषा में हो?",
    intro:
      "कार्ड पर सब कुछ इसी भाषा में आएगा: नाम, शब्द, रस्मों के नाम और तारीख़ें। हर पंक्ति के लिए दिए गए सुझाव भी इसी भाषा में होंगे।",
  },
  couple: {
    label: "जोड़ा",
    eyebrow: "जोड़ा",
    title: "जोड़ा कौन है?",
    intro:
      "नाम कार्ड पर बड़े अक्षरों में आते हैं। बाक़ी पंक्तियाँ आपके अवसर के शब्दों से शुरू होती हैं; इन्हें अपने परिवार के अंदाज़ में बदल लीजिए।",
  },
  functions: {
    label: "रस्में",
    eyebrow: "रस्में",
    title: "सब कब और कहाँ है?",
    intro:
      "वे रस्में चुनें जिनमें मेहमानों को बुला रहे हैं। कार्ड पर मुख्य रस्म की तारीख़ और जगह आती है; खोलने पर मेहमान हर रस्म देखते हैं।",
  },
  extras: {
    label: "तस्वीरें और संगीत",
    eyebrow: "तस्वीरें और संगीत",
    title: "इसे अपना बनाइए",
    intro:
      "आपका डिज़ाइन जो तस्वीरें दिखाता है वे जोड़ें, कार्ड खुलते समय बजने वाला राग चुनें, और तय करें कि जवाब में क्या पूछना है।",
  },
  preview: {
    label: "झलक",
    eyebrow: "झलक",
    title: "मेहमान यही देखेंगे",
    intro: "कार्ड खोलिए, संगीत चलाइए और एक बार फिर पढ़ लीजिए।",
  },
};

export const functionCopy: Translation<typeof en.functionCopy> = {
  roka: {
    name: "रोका",
    description: "परिवार रिश्ते को आशीर्वाद देते हैं और उपहार बदलते हैं",
    dressIdeas: ["उत्सवी पारंपरिक", "लाल और सुनहरा", "हल्के रंग के सूट और साड़ियाँ"],
  },
  engagement: {
    name: "सगाई",
    description: "अँगूठी की रस्म, सगाई या निश्चयतार्थम",
    dressIdeas: ["इंडो-वेस्टर्न", "हल्के रंग और आइवरी", "उत्सवी पारंपरिक"],
  },
  tilak: {
    name: "तिलक",
    description: "कन्या पक्ष वर को तिलक लगाकर आशीर्वाद और उपहार देता है",
    dressIdeas: ["उत्सवी पारंपरिक", "कुर्ता और बंदगला", "लाल और सुनहरा"],
  },
  "ganesh-puja": {
    name: "गणेश पूजन",
    description: "गणेश स्थापना या पूजन, ताकि शुभ कार्य निर्विघ्न शुरू हो",
    dressIdeas: ["पारंपरिक भारतीय", "पीले और लाल", "सादा और सुरुचिपूर्ण"],
  },
  "grah-shanti": {
    name: "ग्रह शांति",
    description: "शादी से पहले घर पर हवन और परिवार के लिए आशीर्वाद",
    dressIdeas: ["पारंपरिक भारतीय", "सूती और रेशमी", "हल्के रंग"],
  },
  mandap: {
    name: "मंडप मुहूर्त",
    description: "मंडप की स्थापना और पूजन; दक्षिण में पंदक्काल",
    dressIdeas: ["पारंपरिक भारतीय", "चटक और रंगीन", "आरामदेह पारंपरिक"],
  },
  mameru: {
    name: "मामेरू",
    description: "ननिहाल से उपहार लेकर मामा आते हैं; उत्तर में भात या मायरा",
    dressIdeas: ["बांधनी और लहरिया", "उत्सवी पारंपरिक", "लाल और गुलाबी"],
  },
  haldi: {
    name: "हल्दी",
    description: "हल्दी का आशीर्वाद, अक्सर शादी से पहले की सुबह",
    dressIdeas: ["पीले रंग", "सफ़ेद और हल्के रंग", "ऐसे कपड़े जिन पर दाग़ की फ़िक्र न हो"],
  },
  mehendi: {
    name: "मेहँदी",
    description: "मेहँदी, संगीत और सुकून भरी दोपहर",
    dressIdeas: ["हरे और फूलदार", "चटक और रंगीन", "आरामदेह पारंपरिक"],
  },
  sangeet: {
    name: "संगीत",
    description: "गीत, नृत्य और प्रस्तुतियों की शाम",
    dressIdeas: ["इंडो-वेस्टर्न", "सितारे और चमक", "गहरे रत्न जैसे रंग"],
  },
  garba: {
    name: "गरबा रात",
    description: "देर रात तक रास, गरबा और डांडिया",
    dressIdeas: ["चनिया चोली और केडियू", "शीशे का काम", "चटक और रंगीन"],
  },
  bhoj: {
    name: "पारिवारिक भोज",
    description: "परिवार और दोस्तों के लिए भोज: केळवण, आइबुड़ो भात या भोजन समारंभ",
    dressIdeas: ["उत्सवी पारंपरिक", "आरामदेह पारंपरिक", "स्मार्ट कैज़ुअल"],
  },
  baraat: {
    name: "बारात",
    description: "संगीत और नाच के साथ दूल्हे की बारात निकलती है",
    dressIdeas: ["साफ़े और पगड़ी", "शेरवानी और कुर्ता", "उत्सवी पारंपरिक"],
  },
  "baraat-welcome": {
    name: "बारात स्वागत",
    description: "कन्या पक्ष बारातियों का स्वागत करता है: मिलनी या जान आगमन",
    dressIdeas: ["पारंपरिक भारतीय", "रेशम और ज़री", "उत्सवी पारंपरिक"],
  },
  wedding: {
    name: "विवाह",
    description: "फेरे, वचन और विवाह संस्कार",
    dressIdeas: ["पारंपरिक भारतीय", "हल्के रंग, काला या सफ़ेद नहीं", "रेशम और ज़री"],
  },
  vidaai: {
    name: "विदाई",
    description: "आशीर्वाद के साथ दुल्हन की विदाई",
    dressIdeas: ["पारंपरिक भारतीय", "हल्के रंग", "रेशम और ज़री"],
  },
  reception: {
    name: "रिसेप्शन",
    description: "सबके साथ भोज और जश्न",
    dressIdeas: ["औपचारिक", "ब्लैक टाई", "उत्सवी शाम के कपड़े"],
  },
  birthday: {
    name: "जन्मदिन की पार्टी",
    description: "केक, खेल और जन्मदिन पर आशीर्वाद",
    dressIdeas: ["हल्के रंग", "स्मार्ट कैज़ुअल", "जैसे चाहें"],
  },
  anniversary: {
    name: "सालगिरह का भोज",
    description: "साथ बिताए बरसों के जश्न की शाम",
    dressIdeas: ["औपचारिक", "उत्सवी पारंपरिक", "लाल और सुनहरा"],
  },
  party: {
    name: "पार्टी",
    description: "संगीत, खाना और दोस्त",
    dressIdeas: ["स्मार्ट कैज़ुअल", "कॉकटेल", "कुछ चमकीला"],
  },
  "baby-shower": {
    name: "गोद भराई",
    description: "होने वाली माँ के लिए आशीर्वाद, गीत और उपहार",
    dressIdeas: ["हल्के रंग", "उत्सवी पारंपरिक", "हरा और पीला"],
  },
  diwali: {
    name: "दिवाली की पार्टी",
    description: "लक्ष्मी पूजा, दीये, मिठाई और भोज",
    dressIdeas: ["उत्सवी पारंपरिक", "लाल और सुनहरा", "कुछ चमकीला"],
  },
  housewarming: {
    name: "गृह प्रवेश",
    description: "नए घर में पूजा, हवन और भोजन",
    dressIdeas: ["उत्सवी पारंपरिक", "हल्के रंग", "आरामदायक पारंपरिक"],
  },
  puja: {
    name: "पूजा",
    description: "कथा, आरती और प्रसाद",
    dressIdeas: ["उत्सवी पारंपरिक", "सफ़ेद और पीला", "पारंपरिक"],
  },
  "thread-ceremony": {
    name: "जनेऊ संस्कार",
    description: "उपनयन, हवन और परिवार का भोजन",
    dressIdeas: ["पारंपरिक", "सफ़ेद और सुनहरा", "उत्सवी पारंपरिक"],
  },
  annaprashan: {
    name: "अन्नप्राशन",
    description: "बच्चे का पहला अन्न, आशीर्वाद के साथ",
    dressIdeas: ["हल्के रंग", "उत्सवी पारंपरिक", "पीला और सफ़ेद"],
  },
  christening: {
    name: "बपतिस्मा",
    description: "चर्च में आराधना और परिवार के साथ भोजन",
    dressIdeas: ["सफ़ेद और हल्के रंग", "रविवार की पोशाक", "स्मार्ट कैज़ुअल"],
  },
  "prayer-meet": {
    name: "श्रद्धांजलि सभा",
    description: "प्रार्थना, भजन और स्मरण",
    dressIdeas: ["सफ़ेद", "हल्के रंग", "सादा और शांत"],
  },
  retirement: {
    name: "सेवानिवृत्ति समारोह",
    description: "एक लंबे करियर के लिए भोज और शुभकामनाएँ",
    dressIdeas: ["स्मार्ट कैज़ुअल", "औपचारिक", "उत्सवी पारंपरिक"],
  },
  "farewell-party": {
    name: "विदाई समारोह",
    description: "संगीत, यादें और प्यार भरी विदाई",
    dressIdeas: ["औपचारिक", "स्मार्ट कैज़ुअल", "कुछ चमकीला"],
  },
  "shop-opening": {
    name: "उद्घाटन",
    description: "फ़ीता काटना, पूजा और जलपान",
    dressIdeas: ["उत्सवी पारंपरिक", "स्मार्ट कैज़ुअल", "औपचारिक"],
  },
  launch: {
    name: "लॉन्च",
    description: "पहली झलक, कुछ शब्द और भोज",
    dressIdeas: ["बिज़नेस फ़ॉर्मल", "स्मार्ट कैज़ुअल", "ब्लैक टाई"],
  },
  "ganesh-chaturthi": {
    name: "गणपति दर्शन",
    description: "आरती, दर्शन और प्रसाद",
    dressIdeas: ["उत्सवी पारंपरिक", "पीला और लाल", "पारंपरिक"],
  },
  navratri: {
    name: "नवरात्रि की रात",
    description: "गरबा, आरती और भोग",
    dressIdeas: ["चनिया चोली", "उत्सवी पारंपरिक", "चटकीले रंग"],
  },
  janmashtami: {
    name: "जन्माष्टमी",
    description: "भजन, झाँकी और आधी रात की आरती",
    dressIdeas: ["उत्सवी पारंपरिक", "पीला और नीला", "नन्हे कान्हा की पोशाक"],
  },
  onam: {
    name: "ओणम सद्या",
    description: "पूक्कलम, सद्या और गीत",
    dressIdeas: ["कसवु", "सफ़ेद और सुनहरा", "उत्सवी पारंपरिक"],
  },
  sankranti: {
    name: "संक्रांति",
    description: "पतंग, तिल के लड्डू और पोंगल",
    dressIdeas: ["चटकीले रंग", "उत्सवी पारंपरिक", "छत के लिए आरामदायक"],
  },
  lohri: {
    name: "लोहड़ी की आग",
    description: "अलाव, रेवड़ी, भांगड़ा और भोज",
    dressIdeas: ["फुलकारी", "चटकीले रंग", "कुछ गरम"],
  },
  eid: {
    name: "इफ़्तार दावत",
    description: "रोज़ा इफ़्तार, दावत और ईद की मुबारकबाद",
    dressIdeas: ["उत्सवी पारंपरिक", "सफ़ेद और हरा", "कुछ शालीन"],
  },
  "naming-ceremony": {
    name: "नामकरण",
    description: "नाम, आशीर्वाद और भोज",
    dressIdeas: ["हल्के रंग", "त्योहारी पारंपरिक", "आरामदायक कपड़े"],
  },
  holi: {
    name: "होली",
    description: "रंग, संगीत, ठंडाई और भोज",
    dressIdeas: ["सफ़ेद कपड़े", "पुराने कपड़े जो रंगे जा सकें", "आरामदायक जूते"],
  },
  christmas: {
    name: "क्रिसमस पार्टी",
    description: "कैरल, प्लम केक और डिनर",
    dressIdeas: ["लाल और हरा", "त्योहारी कपड़े", "गर्म कपड़े"],
  },
  reunion: {
    name: "रीयूनियन",
    description: "पुराने दोस्त, किस्से और डिनर",
    dressIdeas: ["स्मार्ट कैज़ुअल", "स्कूल के रंग", "आरामदायक कपड़े"],
  },
  graduation: {
    name: "ग्रेजुएशन पार्टी",
    description: "केक, परिवार और गर्व भरी शाम",
    dressIdeas: ["स्मार्ट कैज़ुअल", "त्योहारी कपड़े", "कॉलेज के रंग"],
  },
  "gudi-padwa": {
    name: "गुड़ी पड़वा",
    description: "गुड़ी, पूजा और त्योहारी भोज",
    dressIdeas: ["नौवारी और कुर्ता", "त्योहारी पारंपरिक", "केसरिया और हरा"],
  },
  baisakhi: {
    name: "बैसाखी",
    description: "फ़सल, भांगड़ा, गिद्धा और भोज",
    dressIdeas: ["फुलकारी", "चटक पगड़ी और दुपट्टे", "त्योहारी पारंपरिक"],
  },
  bihu: {
    name: "बिहू",
    description: "बिहू गीत, नृत्य और पीठा",
    dressIdeas: ["मेखला चादर", "गमोसा", "त्योहारी पारंपरिक"],
  },
  "raksha-bandhan": {
    name: "रक्षाबंधन",
    description: "राखी, आरती, मिठाई और दोपहर का भोजन",
    dressIdeas: ["त्योहारी पारंपरिक", "चटख रंग", "कुछ आरामदायक"],
  },
  "karva-chauth": {
    name: "करवा चौथ",
    description: "कथा, चाँद का दीदार और रात का भोजन",
    dressIdeas: ["लाल और सुनहरा", "शादी का लहंगा या साड़ी", "कुछ त्योहारी"],
  },
};

export const functionFields: Translation<typeof en.functionFields> = {
  group: "रस्में",
  date: "तारीख़",
  datePlaceholder: "तारीख़ चुनें",
  time: "शुरू होने का समय",
  timePlaceholder: "समय चुनें",
  venue: "जगह",
  venuePlaceholder: "जैसे पिछोला लेकसाइड गार्डन्स, उदयपुर",
  city: "शहर या जगह",
  cityPlaceholder: "जैसे उदयपुर",
  cityHint: "सेव द डेट में सिर्फ़ तारीख़ और शहर चाहिए। समय और जगह निमंत्रण में आएँगे।",
  suggested: (occasion) => `${occasion} की रस्में`,
  more: "और रस्में",
  moreHint: "कोई और रस्म जोड़ें जिसमें मेहमानों को बुला रहे हैं।",
  showMore: (count) => `${count} और रस्में दिखाएँ`,
  address: "पता",
  addressHint: "मेहमानों को यह जगह के नाम के नीचे दिखेगा।",
  pin: "Google Maps पिन",
  pinHint:
    "Google Maps में जगह खोलें, Share दबाएँ और लिंक यहाँ चिपकाएँ। मेहमानों को नक़्शा और ठीक उसी जगह तक एक टैप में रास्ता मिलेगा।",
  pinInvalid: "यह Google Maps का लिंक नहीं है। Google Maps में Share से लिंक कॉपी करें।",
  parking: "पार्किंग",
  parkingPlaceholder: "मुख्य गेट पर वैले, हॉल के पीछे मुफ़्त पार्किंग",
  dressCode: "ड्रेस कोड",
  dressIdeas: "ड्रेस कोड के सुझाव",
  onCard: "कार्ड पर",
  endTime: "ख़त्म होने का समय",
  endHint: "देर तक चलना हो तो ख़ाली छोड़ दें।",
  muhuratHint: "शुरू और ख़त्म होने का सही समय, मिनट तक, चुनें। मेहमानों को ठीक वैसा ही दिखेगा।",
  moreDetails: "और जानकारी",
  moreDetailsHint: "ख़त्म होने का समय, पता, नक़्शे की पिन, पार्किंग और ड्रेस कोड",
};

export const coupleCopy: Translation<typeof en.coupleCopy> = {
  namesHeading: "नाम",
  wordingHeading: "शब्द",
  example: (sample) => `जैसे ${sample}`,
  joinerHint: "नामों के बीच का शब्द, जैसे &, संग या weds।",
  doorsHint: "द्वारों पर लिखे दो छोटे शब्द।",
  anyScript: "किसी भी लिपि में लिखें। हिन्दी, तमिल, बांग्ला और बाक़ी सब कार्ड पर आ जाती हैं।",
  latinOnCard: (language) =>
    `आपका कार्ड ${language} में है, इसलिए मेहमान यह नाम अंग्रेज़ी अक्षरों में देखेंगे। नीचे ${language} में लिखा नाम चुनें, या ${language} कीबोर्ड से टाइप करें।`,
  spellings: (language) => `${language} अक्षरों में`,
  useSpelling: (name) => `${name} लिखें`,
  languagesHeading: "कार्ड की भाषा",
  languagesHint: "दो भाषाएँ चुनने पर मेहमान निमंत्रण पर उनके बीच बदल सकते हैं।",
  bothLanguages: (main, second) => `${main} और ${second}`,
  secondHeading: (language) => `${language} में कार्ड`,
  secondHint: (main) => `कोई पंक्ति ख़ाली छोड़ें तो ${main} कार्ड वाले शब्द ही आएँगे।`,
  ideas: "सुझाव",
  ideasLabel: (field) => `${field} के सुझाव`,
  useIdea: (text) => `“${text}” लिखें`,
  moreWording: "कार्ड के और शब्द",
  moreWordingHint: "द्वार के शब्द और परिवार की पंक्ति। हर एक आपके अवसर के शब्दों से शुरू होता है।",
  cardIn: "कार्ड की भाषा:",
  changeLanguage: "भाषा बदलें",
};

export const languageCopy: Translation<typeof en.languageCopy> = {
  mainHeading: "कार्ड की भाषा",
  traditionMatch: "आपकी परंपरा की",
  secondHeading: "दूसरी भाषा भी जोड़ें?",
  secondHint:
    "मेहमान निमंत्रण पर दोनों भाषाओं के बीच बदल सकेंगे। दूसरी भाषा सेलिब्रेशन और ग्रैंड पैकेज में मिलती है।",
  secondNone: "सिर्फ़ एक भाषा",
  secondLabel: "दूसरी भाषा",
};

export const namesCopy: Translation<typeof en.namesCopy> = {
  steps: {
    birthday: { label: "जन्मदिन", eyebrow: "जन्मदिन", title: "किसका जन्मदिन है?" },
    anniversary: { label: "जोड़ा", eyebrow: "जोड़ा", title: "किनकी सालगिरह है?" },
    party: { label: "पार्टी", eyebrow: "पार्टी", title: "पार्टी का नाम क्या है?" },
    "baby-shower": { label: "होने वाली माँ", eyebrow: "गोद भराई", title: "होने वाली माँ कौन हैं?" },
    diwali: { label: "दिवाली", eyebrow: "दिवाली", title: "आपकी दिवाली पार्टी का नाम क्या है?" },
    housewarming: { label: "घर", eyebrow: "नया घर", title: "नए घर का नाम क्या है?" },
    puja: { label: "पूजा", eyebrow: "पूजा", title: "आप कौन-सी पूजा रख रहे हैं?" },
    "thread-ceremony": { label: "बालक", eyebrow: "जनेऊ संस्कार", title: "किसका जनेऊ संस्कार है?" },
    annaprashan: { label: "बच्चा", eyebrow: "अन्नप्राशन", title: "बच्चे का नाम क्या है?" },
    christening: { label: "बच्चा", eyebrow: "बपतिस्मा", title: "बच्चे का नाम क्या है?" },
    "prayer-meet": {
      label: "स्मृति में",
      eyebrow: "श्रद्धांजलि सभा",
      title: "आप किसकी स्मृति में सभा रख रहे हैं?",
    },
    retirement: {
      label: "सेवानिवृत्त",
      eyebrow: "सेवानिवृत्ति",
      title: "कौन सेवानिवृत्त हो रहे हैं?",
    },
    "farewell-party": {
      label: "विदाई",
      eyebrow: "विदाई समारोह",
      title: "आप किसे विदा कर रहे हैं?",
    },
    "shop-opening": { label: "व्यवसाय", eyebrow: "उद्घाटन", title: "आपके व्यवसाय का नाम क्या है?" },
    launch: { label: "इवेंट", eyebrow: "लॉन्च", title: "आप क्या लॉन्च कर रहे हैं?" },
    "ganesh-chaturthi": {
      label: "गणपति",
      eyebrow: "गणेश चतुर्थी",
      title: "आपके गणपति उत्सव का नाम क्या है?",
    },
    navratri: { label: "उत्सव", eyebrow: "नवरात्रि", title: "आपके नवरात्रि उत्सव का नाम क्या है?" },
    janmashtami: {
      label: "उत्सव",
      eyebrow: "जन्माष्टमी",
      title: "आपके जन्माष्टमी उत्सव का नाम क्या है?",
    },
    onam: { label: "उत्सव", eyebrow: "ओणम", title: "आपके ओणम उत्सव का नाम क्या है?" },
    sankranti: {
      label: "उत्सव",
      eyebrow: "संक्रांति",
      title: "आपके संक्रांति उत्सव का नाम क्या है?",
    },
    lohri: { label: "उत्सव", eyebrow: "लोहड़ी", title: "आपकी लोहड़ी की रात का नाम क्या है?" },
    eid: { label: "दावत", eyebrow: "ईद और इफ़्तार", title: "आपकी दावत का नाम क्या है?" },
    "naming-ceremony": { label: "बच्चा", eyebrow: "नामकरण", title: "बच्चे का नाम क्या है?" },
    holi: { label: "उत्सव", eyebrow: "होली", title: "आपकी होली पार्टी का नाम क्या है?" },
    christmas: {
      label: "पार्टी",
      eyebrow: "क्रिसमस",
      title: "आपकी क्रिसमस पार्टी का नाम क्या है?",
    },
    reunion: { label: "रीयूनियन", eyebrow: "रीयूनियन", title: "कौन-सा बैच या ग्रुप मिल रहा है?" },
    graduation: { label: "ग्रेजुएट", eyebrow: "ग्रेजुएशन", title: "किसका ग्रेजुएशन है?" },
    "gudi-padwa": {
      label: "उत्सव",
      eyebrow: "गुड़ी पड़वा और उगादि",
      title: "आपके नववर्ष उत्सव का नाम क्या है?",
    },
    baisakhi: { label: "उत्सव", eyebrow: "बैसाखी", title: "आपके बैसाखी उत्सव का नाम क्या है?" },
    bihu: { label: "उत्सव", eyebrow: "बिहू", title: "आपके बिहू उत्सव का नाम क्या है?" },
    "raksha-bandhan": {
      label: "बहन और भाई",
      eyebrow: "रक्षाबंधन",
      title: "किनका रक्षाबंधन है?",
    },
    "karva-chauth": { label: "जोड़ी", eyebrow: "करवा चौथ", title: "कौन मना रहे हैं?" },
  },
  one: {
    birthday: { label: "जन्मदिन वाले का नाम", example: "आरव" },
    party: { label: "पार्टी का नाम", example: "दिवाली की रात" },
    "baby-shower": { label: "उनका नाम", example: "प्रिया" },
    diwali: { label: "पार्टी का नाम", example: "शर्मा परिवार की दिवाली" },
    housewarming: { label: "घर या परिवार का नाम", example: "शर्मा निवास" },
    puja: { label: "पूजा का नाम", example: "सत्यनारायण कथा" },
    "thread-ceremony": { label: "उसका नाम", example: "आरव" },
    annaprashan: { label: "बच्चे का नाम", example: "अनाया" },
    christening: { label: "बच्चे का नाम", example: "एरन" },
    "prayer-meet": { label: "उनका नाम", example: "श्री आर. के. शर्मा" },
    retirement: { label: "उनका नाम", example: "आर. के. शर्मा" },
    "farewell-party": { label: "नाम या बैच", example: "2026 बैच" },
    "shop-opening": { label: "व्यवसाय का नाम", example: "शर्मा ज्वेलर्स" },
    launch: { label: "इवेंट का नाम", example: "ऑरोरा लॉन्च" },
    "ganesh-chaturthi": { label: "उत्सव का नाम", example: "शर्मा परिवार के गणपति" },
    navratri: { label: "उत्सव का नाम", example: "नवरात्रि उत्सव" },
    janmashtami: { label: "उत्सव का नाम", example: "कृष्ण जन्मोत्सव" },
    onam: { label: "उत्सव का नाम", example: "ओणम सद्या" },
    sankranti: { label: "उत्सव का नाम", example: "पतंग उत्सव" },
    lohri: { label: "उत्सव का नाम", example: "लोहड़ी की रात" },
    eid: { label: "दावत का नाम", example: "इफ़्तार दावत" },
    "naming-ceremony": { label: "बच्चे का नाम", example: "अनाया" },
    holi: { label: "उत्सव का नाम", example: "होली मिलन" },
    christmas: { label: "पार्टी का नाम", example: "क्रिसमस पार्टी" },
    reunion: { label: "बैच या ग्रुप", example: "2006 का बैच" },
    graduation: { label: "ग्रेजुएट का नाम", example: "रिया" },
    "gudi-padwa": { label: "उत्सव का नाम", example: "गुड़ी पड़वा भोज" },
    baisakhi: { label: "उत्सव का नाम", example: "बैसाखी मेला" },
    bihu: { label: "उत्सव का नाम", example: "रंगाली बिहू" },
  },
  oneHint:
    "यह मुखपृष्ठ पर बड़े अक्षरों में छपता है। कौन बुला रहा है और क्यों, यह नीचे के शब्दों में लिखें।",
};

const LEAD_NAMES: Record<LeadId, string> = {
  santoor: "संतूर",
  sitar: "सितार",
  bansuri: "बांसुरी",
  shehnai: "शहनाई",
  veena: "वीणा",
};

const TAAL_NAMES: Record<TaalId, string> = {
  keherwa: "ढोलक",
  dadra: "ढोलक",
  garba: "गरबा ढोल और तालियाँ",
  bhangra: "पंजाबी ढोल",
};

export const extrasCopy: Translation<typeof en.extrasCopy> = {
  photosHeading: "तस्वीरें",
  photosHint: (max) =>
    `${max} तक तस्वीरें। सहेजने से पहले फ़ोन पर ही छोटी की जाती हैं, ताकि मेहमानों के लिए जल्दी खुलें।`,
  addPhotos: "तस्वीरें जोड़ें",
  dropHere: "या यहाँ छोड़ें",
  photo: (index) => `तस्वीर ${index}`,
  removePhoto: (index) => `तस्वीर ${index} हटाएँ`,
  moveEarlier: (index) => `तस्वीर ${index} पहले लाएँ`,
  full: (max) => `सभी ${max} हो गईं। नई जोड़ने के लिए एक हटाएँ।`,
  processing: "तस्वीरें तैयार हो रही हैं…",
  photoFailed: "यह तस्वीर नहीं पढ़ी जा सकी। JPEG या PNG आज़माएँ।",
  storageFailed: "इस ब्राउज़र में तस्वीरें सहेजी नहीं जा सकतीं, जैसे प्राइवेट मोड में।",
  emptyPhotos: "अभी कोई तस्वीर नहीं",
  emptyPhotosBody: "जोड़े की तस्वीरें और प्री-वेडिंग शूट सबसे अच्छे लगते हैं।",
  coupleHeading: "तस्वीर वाला पन्ना",
  coupleHint:
    "आपकी तस्वीर थीम के अपने फ़्रेम में, आपके नामों के बाद वाले पन्ने पर। हर थीम के फ़्रेम का आकार अलग है।",
  coupleLayouts: {
    none: "तस्वीर वाला पन्ना नहीं",
    one: "आप दोनों की एक तस्वीर",
    two: "दो तस्वीरें, दोनों की अलग-अलग",
  },
  photoHintOne: "आपकी तस्वीर थीम के अपने फ़्रेम में, नाम के बाद वाले पन्ने पर।",
  photoLayoutsOne: {
    none: "तस्वीर वाला पन्ना नहीं",
    one: "एक तस्वीर",
  },
  coupleAddFirst: "ऊपर तस्वीर जोड़ें, वह फ़्रेम में लग जाएगी।",
  designPhotosHeading: "आपके डिज़ाइन की तस्वीरें",
  designPhotosHint: (frames) =>
    frames === 1
      ? "आपके डिज़ाइन में एक फ़्रेम है। उसमें लगने वाली तस्वीर जोड़ें।"
      : "आपके डिज़ाइन में दो फ़्रेम हैं। दोनों के लिए एक-एक तस्वीर जोड़ें।",
  framePhotos: {
    together: "आप दोनों की तस्वीर",
    one: "आपकी तस्वीर",
    of: (name) => `${name} की तस्वीर`,
    first: "पहली तस्वीर",
    second: "दूसरी तस्वीर",
  },
  addFramePhoto: (frame) => `जोड़ें: ${frame}`,
  changeFramePhoto: (frame) => `बदलें: ${frame}`,
  framePhotoAdded: "जुड़ गई",
  framePhotoNeeded: "ज़रूरी",
  changePhoto: "तस्वीर बदलें",
  galleryHeading: "और तस्वीरें",
  galleryHint: (max) => `वैकल्पिक। मेहमान इन्हें निमंत्रण पर देख सकेंगे। कुल ${max} तस्वीरें तक।`,
  coupleFrame: (index, frames) =>
    frames === 1 ? "फ़्रेम की तस्वीर" : index === 1 ? "पहला फ़्रेम" : "दूसरा फ़्रेम",
  useThisPhoto: (index) => `तस्वीर ${index}`,
  fitHeading: "तस्वीरें फ़्रेम में बिठाएँ",
  fitHint: "हर तस्वीर को खिसकाएँ, बड़ा करें और सीधा करें, ताकि वह फ़्रेम में अच्छी लगे।",
  adjust: "ठीक करें",
  adjustLabel: (frame) => `तस्वीर ठीक करें: ${frame}`,
  adjusted: "ठीक की गई",
  adjustTitle: "तस्वीर ठीक करें",
  adjustDescription:
    "तस्वीर को खींचकर खिसकाएँ। बड़ा-छोटा करने के लिए दो उँगलियों से या स्लाइडर से ज़ूम करें।",
  adjustStage:
    "फ़्रेम में तस्वीर। खिसकाने के लिए तीर वाली कुंजियाँ और ज़ूम के लिए प्लस या माइनस दबाएँ।",
  zoom: "ज़ूम",
  straighten: "सीधा करें",
  turn: "घुमाएँ",
  turnLabel: "तस्वीर को दाईं ओर चौथाई घुमाएँ",
  resetPhoto: "पहले जैसा",
  savePhoto: "सहेजें",
  cancelPhoto: "रद्द करें",
  closePhoto: "बंद करें",
  musicHeading: "संगीत",
  musicHint: "कार्ड खुलते समय वहीं रचा गया राग, या आपके अपने संगीत की छोटी-सी क्लिप।",
  musicSource: { raga: "राग", own: "अपना संगीत" },
  ragaHint: "वहीं रचा जाता है, इसलिए मेहमानों का डेटा ख़र्च नहीं होता।",
  ownHint:
    "फ़ोन से कोई गाना या रिकॉर्डिंग चुनें और उसका पसंदीदा हिस्सा रखें, 30 सेकंड तक। कार्ड खुलते ही मेहमान इसे सुनेंगे, और यह आपके वीडियो में भी बजेगा।",
  chooseSong: "गाना चुनें",
  songTypes: "MP3, M4A, WAV या AAC",
  readingSong: "आपका गाना पढ़ा जा रहा है…",
  songFailed: "यह फ़ाइल पढ़ी नहीं जा सकी। MP3 या M4A फ़ाइल आज़माएँ।",
  clipFailed: "इस ब्राउज़र में क्लिप नहीं बन सकी। Chrome या Safari आज़माएँ।",
  clipStorageFailed: "इस ब्राउज़र में संगीत सहेजा नहीं जा सकता, जैसे प्राइवेट मोड में।",
  trimHeading: "पसंदीदा हिस्सा रखें",
  waveformLabel: (name) => `${name} का आकार, रखा गया हिस्सा चमकता हुआ`,
  startAt: "शुरुआत",
  clipLength: "लंबाई",
  seconds: (n) => `${n} सेकंड`,
  secondsShort: (n) => `${n} से.`,
  playPart: "यह हिस्सा सुनें",
  stopPart: "रोकें",
  rights: "मुझे यह संगीत इस्तेमाल करने का अधिकार है",
  rightsHint:
    "अपनी रिकॉर्डिंग, लाइसेंस लिया हुआ गाना, या रॉयल्टी-फ़्री संगीत इस्तेमाल करें। Instagram या YouTube से डाउनलोड की गई क्लिप आम तौर पर इस्तेमाल नहीं की जा सकतीं, और मालिक के कहने पर हम संगीत हटा देते हैं।",
  useClip: "यह संगीत लगाएँ",
  makingClip: "आपकी क्लिप बन रही है…",
  cancelTrim: "रद्द करें",
  changeClip: "बदलें",
  removeClip: "हटाएँ",
  listenClip: "सुनें",
  clipMeta: (n) => `आपका संगीत · ${n} सेकंड`,
  listen: (raga) => `${raga} सुनें`,
  stopListening: "सुनना बंद करें",
  designsOwn: "डिज़ाइन का अपना",
  playOnOpen: "मेहमान कार्ड खोलें तो संगीत बजे",
  playOnOpenHint: "मेहमान कभी भी रोक सकते हैं।",
  pacing: {
    heading: "हर पन्ने का समय",
    hint: "संगीत और रील आपके पन्नों जितने लंबे चलते हैं। ऑटो में हर पन्ने को उसके शब्दों जितना समय मिलता है।",
    auto: "ऑटो",
    seconds: (n: number) => `${n} से.`,
    summary: (pages: number, live: number, reel: number) =>
      `${pages} पन्ने: निमंत्रण पर लगभग ${live} सेकंड संगीत, और ${reel} सेकंड की रील।`,
  },
  questionsHeading: "मेहमानों से सवाल",
  questionsHint:
    "हर जवाब में बताया जाता है कि हर रस्म में कौन आ रहा है, और एक संदेश भी। और जो जानना हो, उस पर निशान लगाएँ।",
  questionHints: {
    meal: "शाकाहारी, जैन, मांसाहारी या वीगन",
    arrival: "जिस दिन वे शहर पहुँचेंगे",
    stay: "क्या उन्हें कमरा चाहिए",
    pickup: "क्या उन्हें स्टेशन या हवाई अड्डे से लाना है",
    song: "कोई गाना जो वे सुनना चाहें",
  },
  ragaNames: {
    yaman: "राग यमन",
    khamaj: "राग खमाज",
    bihag: "राग बिहाग",
    desh: "राग देस",
    bhupali: "राग भूपाली",
    madhyamavati: "राग मध्यमावती",
    mand: "राग मांड",
    bhimpalasi: "राग भीमपलासी",
    pilu: "राग पीलू",
    bhairavi: "राग भैरवी",
    hamsadhwani: "राग हंसध्वनि",
    kafi: "राग काफ़ी",
  },
  ragaSound: (sound, mood) =>
    `${LEAD_NAMES[sound.lead]}${sound.taal ? ` और ${TAAL_NAMES[sound.taal]}` : ""} · ${mood}`,
  ragaMoods: {
    yaman: "शाम का, रूमानी",
    khamaj: "हल्का और कोमल",
    bihag: "देर शाम का, शादी का राग",
    desh: "बरसात का, उत्सवी",
    bhupali: "उजला और आनंदमय",
    madhyamavati: "शुभ, कर्नाटक संगीत",
    mand: "राजस्थानी लोक, शाही",
    bhimpalasi: "दोपहर का, भक्तिमय",
    pilu: "लोक रंग, चंचल",
    bhairavi: "कोमल, विदाई का राग",
    hamsadhwani: "शुभ, गणपति वंदना",
    kafi: "उत्सवी लोक, होली के रंग",
  },
};

export const traditionCopy: Translation<typeof en.traditionCopy> = {
  group: "परंपराएँ",
  none: "कोई परंपरा नहीं",
  noneHint: "डिज़ाइन की अपनी शब्दावली, कोई चिह्न नहीं",
  nearYou: "आपके यहाँ",
  draftNote:
    "ये परंपराएँ अभी शुरुआती रूप में हैं। हर समुदाय के लोग लॉन्च से पहले शब्द, चिह्न और रस्मों के नाम जाँच रहे हैं, इसलिए कुछ ठीक न लगे तो हमें ज़रूर बताएँ।",
  names: {
    "north-hindu": "उत्तर भारतीय हिन्दू",
    rajasthani: "राजस्थानी और मारवाड़ी",
    marathi: "मराठी",
    gujarati: "गुजराती",
    bengali: "बंगाली हिन्दू",
    tamil: "तमिल हिन्दू",
    modern: "आधुनिक",
  },
  hints: {
    "north-hindu": "श्री गणेशाय नमः, दर्शनाभिलाषी और स्वागतोत्सुक",
    rajasthani: "श्री गणेशाय नमः, पीठी और महिला संगीत",
    marathi: "श्री गणेशाय नमः, साखरपुडा और हळद",
    gujarati: "कंकोत्री की शब्दावली, गोळ धाणा, पीठी और बच्चों का टहुको",
    bengali: "प्रजापतये नमः, गाये हलुद और बौ भात",
    tamil: "पिल्लैयार सुऴि, निच्चयतार्थम और वरवेर्पु",
    modern: "कोई धार्मिक चिह्न नहीं, किसी भी जोड़े या अंतर-धार्मिक शादी के लिए",
  },
  elements: "धार्मिक तत्व",
  symbol: "कार्ड के ऊपर शुभ चिह्न",
  symbolNames: {
    om: "ॐ",
    kalash: "मंगल कलश",
    swastik: "स्वस्तिक",
    diya: "दीया",
    prajapati: "प्रजापति",
    suzhi: "पिल्लैयार सुऴि",
  },
  noSymbol: "कोई चिह्न नहीं",
  symbolNote: "देवी-देवताओं के चित्र भारतीय कलाकार बना रहे हैं, वे बाद में आएँगे।",
  invocation: "मंगलाचरण",
  invocationModes: { script: "अपनी लिपि में", latin: "अंग्रेज़ी अक्षरों में", off: "न दिखाएँ" },
  meanings: {
    "Shri Ganeshaya Namah": "भगवान गणेश को नमन",
    "Prajapataye Namah": "विवाह के देवता प्रजापति को नमन",
    "Sri Vinayagar Thunai": "भगवान विनायक की कृपा से",
  },
  wording: "परिवार की शब्दावली",
  wordingIntro: "मेहमान इन्हें कार्ड के नीचे पढ़ेंगे। कोई भी खाली छोड़ सकते हैं।",
  wordingLabels: {
    blessingsFrom: "आशीर्वाद",
    requesters: "निमंत्रक",
    welcome: "स्वागतोत्सुक",
    children: "बच्चों की मनुहार",
  },
  ceremonies: "रस्मों के नाम",
  ceremoniesIntro: "मेहमानों के पेज पर रस्में अपने स्थानीय नाम से दिखेंगी।",
};

export const designCopy: Translation<typeof en.designCopy> = {
  marigold: {
    name: "गेंदा द्वार",
    description: "गेंदे के मंडल पर खुलते सुनहरे द्वार, आकाश दीप और राग यमन।",
  },
  rose: {
    name: "गुलाब बाग़",
    description: "हल्के गुलाबी कार्ड पर चढ़ती बेलें, द्वार पर गुलाब की माला और राग खमाज।",
  },
  emerald: {
    name: "पन्ना महल",
    description: "गहरे पन्ने पर जाली वाले मेहराब के महल-द्वार, चमेली, कंदील और राग बिहाग।",
  },
  scroll: {
    name: "शाही स्क्रॉल",
    description: "नक्काशीदार डंडों पर चर्मपत्र, सिंदूरी मुहर और राग देस।",
  },
  monogram: {
    name: "सादा मोनोग्राम",
    description: "शांत पत्थर-सफ़ेद कार्ड, बड़े अक्षरों में आपके नाम के पहले अक्षर और राग भूपाली।",
  },
  kasavu: {
    name: "केरल कसवु",
    description: "सुनहरी कसवु किनारी, पीतल के निलविलक्कु दीप, चमेली और राग मध्यमावती।",
  },
  rangmahal: {
    name: "रंग महल",
    description: "मरून महल के झरोखे, फ़िरोज़ी मीनाकारी फूल, कंदील और राग मांड।",
  },
  paithani: {
    name: "पैठणी मोर",
    description:
      "पैठणी की मंदिर किनारी और मोरपंख के पंखे, रानी और हरे रंग में, राग भीमपलासी के साथ।",
  },
  bandhani: {
    name: "बांधनी उत्सव",
    description: "गहरे फ़िरोज़ी पर बांधनी की बूँदें और शीशे का काम, रानी गुलाबी और राग पीलू।",
  },
  alpona: {
    name: "अल्पना लाल",
    description: "सफ़ेद पर लाल पाड़ की साड़ी और अल्पना का कमल, राग भैरवी के साथ।",
  },
  gopuram: {
    name: "गोपुरम पोन",
    description: "सुनहरे मंदिर गोपुरम, कोलम और पीतल के दीप, क्रीम रंग पर, राग हंसध्वनि के साथ।",
  },
  phulkari: {
    name: "फुलकारी रंग",
    description: "लाल खद्दर पर सुनहरी फुलकारी कढ़ाई, शाही नीले द्वार और राग काफ़ी।",
  },
};

export const occasionCopy: Translation<typeof en.occasionCopy> = {
  group: "अवसर",
  setsUp: "यह क्या तैयार करता है",
  planned: "तय रस्में",
  questions: "मेहमानों से पूछा जाएगा",
  noQuestions: "बस यह कि वे आ रहे हैं और कितने लोग",
  designs: (count) => `${count} सुझाए गए डिज़ाइन`,
  suggestedBadge: "सुझाया गया",
  suggestedFor: (occasion) => `${occasion} के लिए सुझाया गया`,
  moreDesigns: "और डिज़ाइन",
};

export const previewCopy: Translation<typeof en.previewCopy> = {
  ready: "आपका निमंत्रण तैयार है",
  live: "आपका निमंत्रण लाइव है",
  liveBody: (link) => `मेहमान इसे ${link} पर खोलते हैं। यहाँ किए बदलाव वहाँ तुरंत दिखते हैं।`,
  readyBody:
    "यह इसी डिवाइस पर सहेजा गया है। इसे अपने खाते में रखने और प्रकाशित करने के लिए साइन इन करें, फिर लिंक WhatsApp पर भेजें।",
  readyBodyAccount:
    "यह तस्वीरों समेत आपके खाते में सहेजा गया है। पहले इसे मेहमानों की नज़र से देखें, फिर लिंक पाने के लिए प्रकाशित करें।",
  seeAsGuest: "मेहमानों की नज़र से देखें",
  seeAsGuestBody: "पूरा निमंत्रण, पूरी स्क्रीन पर: खुलना, संगीत, हर पेज और जवाब का फ़ॉर्म।",
  notReady: "कुछ ब्योरा बाक़ी है",
  fix: (label) => `${label} पूरा करें`,
  occasionHeading: "अवसर",
  namesHeading: "नाम",
  functionsHeading: "रस्में",
  photosHeading: "तस्वीरें",
  noPhotos: "कोई तस्वीर नहीं जोड़ी",
  musicHeading: "संगीत",
  playsOnOpen: "मेहमानों के कार्ड खोलते ही बजता है",
  dressCode: "ड्रेस कोड",
  edit: "बदलें",
  editStep: (label) => `${label} बदलें`,
  startOver: "नया निमंत्रण शुरू करें",
  startOverTitle: "नया निमंत्रण शुरू करें?",
  startOverBody: "इससे इस डिवाइस पर सहेजे नाम, रस्में और तस्वीरें मिट जाएँगी।",
  startOverConfirm: "मिटाएँ और नए सिरे से शुरू करें",
  startOverKeepBody:
    "यह निमंत्रण मेरे निमंत्रण में रहेगा, आप कभी भी लौट सकते हैं। नया ख़ाली शुरू होगा।",
  startOverKeepConfirm: "नया निमंत्रण शुरू करें",
  cancel: "यही निमंत्रण रखें",
  cleared: "नया निमंत्रण शुरू हुआ",
};

export const suiteCopy: Translation<typeof en.suiteCopy> = {
  heading: "आपके अवसर के डिज़ाइन",
  intro:
    "खुलने के बाद मेहमान इसी डिज़ाइन में आपके नाम, हर रस्म और जवाब का फ़ॉर्म देखते हैं। आपकी परंपरा के रस्मों के नाम, आशीर्वचन और चिह्न हर डिज़ाइन में वही रहते हैं।",
  cardHeading: "कार्ड का काग़ज़ और रंग",
  cardIntro: "कार्ड के रंग वाले पन्ने यहाँ चुने कार्ड का काग़ज़, रंग और राग लेते हैं।",
  suggested: "आपकी परंपरा के अनुरूप",
  pairs: (design) => `कार्ड भी ${design} में बदल जाएगा`,
  preview: "पन्ने चलाएँ",
  textBox: "शब्दों के पीछे डिब्बा",
  textBoxHint:
    "बंद रहने पर शब्द सीधे चित्र पर दिखते हैं। चालू करने पर वे कार्ड के रंग के हल्के डिब्बे में दिखते हैं। तुलना के लिए पन्ने चलाएँ; यही बटन पन्नों पर भी है।",
  formatHeading: "निमंत्रण का प्रकार",
  formats: {
    scene: {
      name: "दृश्य",
      description:
        "सब कुछ एक ही चित्र पर: आपकी फ़ोटो, नाम और हर रस्म बारी-बारी से उड़कर आती है। मेहमान झट से सब देख लेते हैं।",
    },
    story: {
      name: "कहानी",
      description: "हर रस्म का पूरी स्क्रीन का अपना चित्रित पन्ना, एक के बाद एक।",
    },
  },
  blessingPage: "आशीर्वाद वाले पन्ने से शुरू करें",
  blessingPageHint:
    "यह थीम भगवान के चित्र और उसके नीचे आपके आशीर्वाद से शुरू होती है, आपके नामों से पहले।",
  names: {
    "rajwada-bagh": "रजवाड़ा बाग़",
    "shahi-savari": "शाही सवारी",
    kayal: "कायल",
    "noor-bagh": "नूर बाग़",
    "phulkari-haveli": "फुलकारी हवेली",
    rajbari: "राजबाड़ी",
    "peshwai-wada": "पेशवाई वाडा",
    "kutch-toran": "कच्छ तोरण",
    gubbara: "गुब्बारा",
    saath: "साथ",
    rooftop: "रूफ़टॉप",
    "ivory-arch": "आइवरी आर्च",
    gulaab: "गुलाब",
    "deco-noir": "डेको नुआर",
    taara: "तारा",
    kaagaz: "काग़ज़",
    mitti: "मिट्टी",
    neel: "नील",
    pichwai: "पिछवाई",
    tanjore: "तंजौर",
    kashi: "काशी",
    sagar: "सागर",
    mysuru: "मैसूरु",
    kalamkari: "कलमकारी",
    pattachitra: "पट्टचित्र",
    chinar: "चिनार",
    "chai-bagan": "चाय बागान",
    "sufi-raat": "सूफ़ी रात",
    chapel: "चैपल",
    sakura: "सकुरा",
    vigna: "विन्या",
    himani: "हिमानी",
    van: "वन",
    riad: "रियाद",
    palna: "पालना",
    deepotsav: "दीपोत्सव",
    "jungle-party": "जंगल पार्टी",
    "udaipur-lake": "उदयपुर झील",
    "space-voyage": "अंतरिक्ष यात्रा",
    "rainbow-unicorn": "इंद्रधनुष यूनिकॉर्न",
    "dino-jungle": "डायनो जंगल",
    "ocean-pearl": "समुद्री मोती",
    "boho-onederland": "बोहो पहला जन्मदिन",
    "fairytale-castle": "परीकथा महल",
    "little-racer": "नन्हा रेसर",
    "gold-gala": "गोल्ड गाला",
    "amrit-utsav": "अमृत उत्सव",
    "silver-jubilee": "रजत जयंती",
    "golden-jubilee": "स्वर्ण जयंती",
    "oh-baby": "ओह बेबी",
    "new-year-eve": "नए साल की रात",
    "kitty-tea": "किटी टी पार्टी",
    "pool-party": "पूल पार्टी",
    "baraat-band": "बारात बैंड",
    "roka-shagun": "रोका शगुन",
    "chooda-ceremony": "चूड़ा रस्म",
    "rishikesh-ganga": "ऋषिकेश गंगा",
    "jaisalmer-dunes": "जैसलमेर के टीले",
    "fort-night": "किले की रात",
    "sheesh-mahal": "शीश महल",
    "white-rann": "सफ़ेद रण",
    annaprashan: "अन्नप्राशन",
    "christening-lilies": "बपतिस्मा की कुमुदिनी",
    "new-home-modern": "नया घर",
    satyanarayan: "सत्यनारायण कथा",
    "mata-ki-chowki": "माता की चौकी",
    upanayana: "उपनयन",
    shraddhanjali: "श्रद्धांजलि",
    "retirement-garden": "सेवानिवृत्ति का बगीचा",
    "farewell-night": "विदाई की रात",
    "grand-opening": "शुभ उद्घाटन",
    "launch-stage": "लॉन्च मंच",
    "ganesh-utsav": "गणेश उत्सव",
    "durga-pujo": "दुर्गा पूजा",
    janmashtami: "जन्माष्टमी",
    "onam-pookalam": "ओणम पूक्कलम",
    "pongal-kolam": "पोंगल कोलम",
    "uttarayan-kites": "उत्तरायण की पतंगें",
    "lohri-bonfire": "लोहड़ी का अलाव",
    "iftar-dawat": "इफ़्तार दावत",
    "kadamb-krishna": "कदंब कृष्ण",
    "ganesh-genda": "गणेश गेंदा",
    "siya-ram-mala": "सिया राम माला",
    "kailash-kamal": "कैलाश कमल",
    "kamal-sarovar": "कमल सरोवर",
    gulmohar: "गुलमोहर",
    "vat-vriksha": "वट वृक्ष",
    "mogra-raat": "मोगरा रात",
    "tulip-kashmir": "ट्यूलिप कश्मीर",
    "wisteria-tunnel": "विस्टेरिया",
    "prem-vriksh": "प्रेम वृक्ष",
    amaltas: "अमलतास",
    "palash-van": "पलाश वन",
    "parijat-angan": "पारिजात आँगन",
    "aam-bagiya": "आम की बगिया",
    "vazhai-mandap": "वाळै मंडप",
    "mor-bagh": "मोर बाग़",
    "orchid-meghalaya": "ऑर्किड मेघालय",
    "rhododendron-himalaya": "बुरांश हिमालय",
    "sunflower-haldi": "सूरजमुखी हल्दी",
    "lavender-field": "लैवेंडर खेत",
    "hydrangea-blue": "नीली हाइड्रेंजिया",
    "peony-blush": "पियोनी ब्लश",
    "magnolia-moon": "मैगनोलिया चाँद",
    "phool-chandelier": "फूलों का झूमर",
    "mor-kamal": "मोर कमल",
    "rajwada-haathi": "रजवाड़ा हाथी",
    "madhubani-machhli": "मधुबनी मछली",
    "pichwai-gaay": "पिछवाई गाय",
    "kerala-mural": "केरल भित्तिचित्र",
    "kalyana-vazhai": "कल्याण वाळै",
    "alpana-topor": "अल्पना टोपोर",
    "kutch-rang": "कच्छ रंग",
    "mughal-bagh": "मुग़ल बाग़",
    "phulkari-lavan": "फुलकारी लावां",
    "safed-gulaab": "सफ़ेद गुलाब",
    "line-art-gold": "सुनहरी रेखा",
    "samudra-sanjh": "समुद्र सांझ",
    "kaagaz-chaand": "काग़ज़ चांद",
    "doli-vidaai": "डोली विदाई",
    "haldi-genda": "हल्दी गेंदा",
    "mehendi-jhoola": "मेहंदी झूला",
    "sangeet-dhol": "संगीत ढोल",
    "pehla-janamdin": "पहला जन्मदिन",
    "godh-bharai": "गोद भराई",
    "griha-kalash": "गृह कलश",
    "sona-saath": "सोना साथ",
    "bagh-reception": "बाग़ रिसेप्शन",
    "naamkaran-chanda": "नामकरण चंदा",
    "swagat-laxmi": "स्वागत लक्ष्मी",
    "holi-rang": "होली रंग",
    "christmas-tara": "क्रिसमस तारा",
    "reunion-yaarana": "रीयूनियन याराना",
    "graduation-topi": "ग्रेजुएशन टोपी",
    "gudi-padwa": "गुड़ी पड़वा",
    "baisakhi-mela": "बैसाखी मेला",
    "bihu-utsav": "बिहू उत्सव",
    "gond-vriksh": "गोंड वृक्ष",
    "warli-vivah": "वारली विवाह",
    "kalighat-pat": "कालीघाट पट",
    "cheriyal-talambralu": "चेरियाल तलंब्रालु",
    "axomiya-biya": "असमिया बिया",
    "antarpat-mangal": "अंतरपट मंगल",
    "kangra-megh": "कांगड़ा मेघ",
    "hyderabadi-nikah": "हैदराबादी निकाह",
    "goa-azulejo": "गोवा अज़ुलेजो",
    "pressed-phool": "प्रेस्ड फूल",
    "tuscan-vineyard": "टस्कन अंगूर बाग़",
    "boho-pampas": "बोहो पैम्पस",
    "winter-pine": "विंटर पाइन",
    "kantha-silai": "कांथा सिलाई",
    "tholu-bommalata": "तोलु बोम्मलाटा",
    "chikankari-awadh": "चिकनकारी अवध",
    "bidri-raat": "बिदरी रात",
    "stained-glass": "रंगीन काँच",
    "chinoiserie-bagh": "शिनुआज़री बाग़",
    "nouveau-arch": "नूवो मेहराब",
    "safar-shaadi": "सफ़र शादी",
    "chibi-jodi": "चिबी जोड़ी",
    "jaago-gagar": "जागो गागर",
    "tilak-thaal": "तिलक थाल",
    "nalangu-vilayattu": "नलंगु",
    "sagai-anguthi": "गुलाब अँगूठी",
    "chandni-cocktail": "चाँदनी कॉकटेल",
    "kathputli-sangeet": "कठपुतली संगीत",
    sehrabandi: "सेहराबंदी",
    "laxmi-aagman": "लक्ष्मी आगमन",
    shashtipurti: "षष्टिपूर्ति",
    "circus-tent": "सर्कस टेंट",
    "toy-train": "खिलौना रेल",
    "pet-party": "पेट पार्टी",
    "mixtape-party": "मिक्सटेप पार्टी",
    "pehli-salgirah": "पहली सालगिरह",
    "eid-milan": "ईद मिलन",
    "garba-raas": "गरबा रास",
    valaikappu: "वलैकाप्पु",
    "shubh-labh": "शुभ लाभ",
    "retirement-naav": "रिटायरमेंट नाव",
    "phad-gatha": "फड़ गाथा",
    "mandana-lal": "मांडणा लाल",
    "gota-patti": "गोटा पत्ती",
    "pithora-ghoda": "पिथोरा घोड़ा",
    "sohrai-khovar": "सोहराई कोहबर",
    "aipan-kumaon": "ऐपण कुमाऊँ",
    "pipli-chhata": "पिपली छाता",
    "bishnupur-terracotta": "बिष्णुपुर टेराकोटा",
    "ganjifa-patte": "गंजीफ़ा पत्ते",
    "kanjivaram-pattu": "कांजीवरम पट्टू",
    "kasavu-sona": "कसवु सोना",
    "urli-pookal": "उरली पूक्कल",
    "kar-e-kashmir": "कार-ए-कश्मीर",
    "zardozi-mehfil": "ज़रदोज़ी महफ़िल",
    "patola-bandh": "पटोला बंध",
    "kundan-jhumka": "कुंदन झुमका",
    "moti-bharat": "मोती भरत",
    "polaroid-lights": "पोलरॉइड लाइट्स",
    "dak-tikat": "डाक टिकट",
    "kadhai-hoop": "कढ़ाई हूप",
    "locket-jodi": "लॉकेट जोड़ी",
    "syahi-bamboo": "स्याही बाँस",
    "lace-ivory": "लेस आइवरी",
    "origami-saaras": "ओरिगामी सारस",
    "nimbu-amalfi": "नींबू अमाल्फ़ी",
    "rail-yatra": "रेल यात्रा",
    "rakhi-dor": "राखी डोर",
    "karva-chandni": "करवा चाँदनी",
    "judwa-taare": "जुड़वाँ तारे",
    "naya-mehmaan": "नया मेहमान",
    "jal-mahal": "जल महल",
    "gulmohar-rasta": "गुलमोहर रास्ता",
    "genda-barsaat": "गेंदा बरसात",
    "akash-kandil": "आकाश कंदील",
    "chand-raat": "चाँद रात",
    "titli-bagh": "तितली बाग़",
    "malli-mazhai": "मल्ली मड़ई",
    "shiuli-bhor": "शिउली भोर",
    "sarson-khet": "सरसों खेत",
    "shamiana-raat": "शामियाना रात",
    "kettuvallam-raat": "केट्टुवल्लम रात",
    "diya-dhara": "दीया धारा",
    "wedding-bells": "वेडिंग बेल्स",
    "saawan-bundein": "सावन बूँदें",
    "hans-jheel": "हंस झील",
    "navratri-garbi": "नवरात्रि गरबी",
    "snow-globe": "स्नो ग्लोब",
    "sea-bubbles": "समंदर के बुलबुले",
    "badal-sapne": "बादल सपने",
    "aangan-subah": "आँगन सुबह",
    "neeli-nagri": "नीली नगरी",
    "kesar-kyari": "केसर क्यारी",
    "konkan-kinara": "कोंकण किनारा",
    "megh-jharna": "मेघ झरना",
    "fawwara-bagh": "फव्वारा बाग़",
    "deodar-sanjh": "देवदार साँझ",
    "jhoomar-mahal": "झूमर महल",
    "champa-baag": "चंपा बाग़",
    "tota-bagh": "तोता बाग़",
    aatishbaazi: "आतिशबाज़ी",
    "toota-taara": "टूटा तारा",
    "phoolon-ki-holi": "फूलों की होली",
    "dahi-handi": "दही हांडी",
    "vallam-kali": "वल्लम कली",
    "pongal-paanai": "पोंगल पानई",
    "khazana-dweep": "ख़ज़ाना द्वीप",
    "kaagaz-ki-kashti": "काग़ज़ की कश्ती",
    "aurora-igloo": "ऑरोरा इग्लू",
    "teddy-picnic": "टेडी पिकनिक",
    "dukaan-mahurat": "दुकान मुहूर्त",
    "mameru-bandhani": "मामेरु बांधनी",
    "sindhi-ajrak": "सिंधी अजरक",
    "hampi-ruins": "हम्पी",
    "coorg-estate": "कूर्ग एस्टेट",
    "bali-garden": "बाली गार्डन",
    "santorini-white": "सेंटोरिनी",
    "glass-house": "ग्लास हाउस",
    "minimal-white": "मिनिमल सफ़ेद",
    "fairy-forest": "परी वन",
    "love-letter": "प्रेम पत्र",
    "parsi-chalk": "पारसी चॉक",
    "jazz-lounge": "जैज़ लाउंज",
    "bride-squad": "ब्राइड स्क्वॉड",
    "teej-jhoola": "तीज झूला",
    "cricket-stadium": "क्रिकेट स्टेडियम",
    "neon-arcade": "नियॉन आर्केड",
    "retro-bollywood": "रेट्रो बॉलीवुड",
    "pink-haveli": "गुलाबी हवेली",
    "char-bagh": "चार बाग़",
    "kashi-ghat": "काशी घाट",
    "temple-pond": "मंदिर का तालाब",
    "kovil-corridor": "कोविल",
    "arati-mandap": "पेल्लि पंदिरी",
    "zamindar-bari": "ज़मींदार बाड़ी",
    "kutch-bhunga": "भूंगा",
    "punjab-haveli": "सरसों हवेली",
    "pune-wada": "वाडा आंगन",
    "chinar-dal": "डल झील",
    classic: "कार्ड के रंग",
  },
  descriptions: {
    "rajwada-bagh": "मुग़ल मेहराब से दिखता महल का बाग़, फ़व्वारे और लालटेनें।",
    "shahi-savari": "रेगिस्तानी क़िले के आगे हाथियों की शाही सवारी, ऊपर झंडियाँ।",
    kayal: "केरल के बैकवॉटर में हाउसबोट, नारियल के पेड़ और तैरते दीये।",
    "noor-bagh": "सफ़ेद संगमरमर, जाली और लंबी नहर वाला मुग़ल बाग़।",
    "phulkari-haveli": "फुलकारी से सजी पंजाबी हवेली, ढोल, गेंदे और सरसों के खेत।",
    rajbari: "लाल-सफ़ेद पुरानी बंगाली हवेली, केले के पौधे और शोला के फूल।",
    "peshwai-wada": "पैठणी रंगों में पेशवाकालीन लकड़ी का वाडा, रंगोली और आम के पत्ते।",
    "kutch-toran": "शीशे के काम और बांधनी से सजा कच्छ का भूंगा आँगन, पीछे सफ़ेद रण।",
    gubbara: "गुब्बारों और झंडियों वाला हल्के रंगों का बाग़ीचा, नीचे केक की मेज़।",
    saath: "सूर्यास्त में झील पर लाल गुलाब और मोमबत्तियाँ, साथ के बरसों के लिए।",
    rooftop: "रात में शहर की छत, झिलमिल रोशनियाँ, गद्दे और आतिशबाज़ी।",
    "ivory-arch": "नया और शांत अंदाज़: हाथीदांत रंग के मेहराब, पम्पास घास और समुद्र किनारे की धूप।",
    gulaab: "सफ़ेद काग़ज़ पर जलरंग के गुलाब और पियोनी।",
    "deco-noir": "काले और सुनहरे आर्ट डेको में, 1920 के किसी भव्य होटल जैसा।",
    taara: "सुनहरे चाँद, तारों और मुलायम बादलों वाला आधी रात का आसमान।",
    kaagaz: "हल्के रंगों के कटे काग़ज़ की परतें, कमल और जाली के साथ।",
    mitti: "रेगिस्तान की बोहो शादी: टेराकोटा मेहराब, पम्पास घास और टीले।",
    neel: "जयपुर की ब्लू पॉटरी: सफ़ेद संगमरमर पर नीली और फ़िरोज़ी टाइलें।",
    pichwai: "कमल के तालाब और गायों वाली नाथद्वारा पिछवाई, श्रीनाथजी के दर्शन से शुरू।",
    tanjore: "सोने के पत्तर और रत्नों वाली तंजौर चित्रकला, गणेश जी के दर्शन से शुरू।",
    kashi: "भोर में बनारस के घाट, गणेश जी के दर्शन से शुरू, गंगा पर दीये।",
    sagar: "समुद्र तट की शादी: सफ़ेद पर्दे, नारियल के पेड़ और सूर्यास्त।",
    mysuru: "दशहरे की रोशनी में मैसूरु महल, मैसूर की सुनहरी चित्रकला, गणेश जी के दर्शन से शुरू।",
    kalamkari: "कमल और मोरों वाला हाथ से रंगा कलमकारी कपड़ा, भगवान वेंकटेश्वर के दर्शन से शुरू।",
    pattachitra: "ओडिशा का रंग-बिरंगा पट्टचित्र, भगवान जगन्नाथ के दर्शन से शुरू।",
    chinar: "पतझड़ का कश्मीर: डल झील, शिकारे, चिनार के पत्ते और अखरोट की नक़्क़ाशीदार लकड़ी।",
    "chai-bagan": "गमोसा के लाल-सफ़ेद रंगों में असम के चाय बागान, नदी किनारे बिहू के ढोल।",
    "sufi-raat": "चाँदनी में सूफ़ी आँगन, लालटेनें, गुलाब और ठहरा पानी।",
    chapel: "लिली के फूलों वाला सफ़ेद बाग़ीचे का चैपल, रंगीन काँच की खिड़की से शुरू।",
    sakura: "लकड़ी के पुल, ठहरे तालाब और काग़ज़ की लालटेनों पर खिले चेरी के फूल।",
    vigna: "सुनहरी शाम में टस्कनी के अंगूर के बाग़, जैतून के पेड़ और पत्थर का विला।",
    himani: "बर्फ़ीले पहाड़, चीड़ का जंगल और सर्दियों की गुनगुनी रोशनी।",
    van: "काई, फ़र्न, झिलमिल रोशनी और जुगनुओं वाला जादुई जंगल।",
    riad: "रंगीन टाइलों के फ़व्वारे, मेहराबें और पीतल की लालटेनों वाला मोरक्को का रियाद।",
    palna: "हल्के रंगों के बादलों के बीच फूलों से सजा झूला पालना।",
    deepotsav: "दीयों, रंगोली और आतिशबाज़ी वाली दिवाली की रात, लक्ष्मी-गणेश के दर्शन से शुरू।",
    "jungle-party": "प्यारे जानवरों, गुब्बारों और बड़े पत्तों वाला कहानी जैसा जंगल।",
    "udaipur-lake": "शाम की पिछोला झील, हर रस्म के लिए सफ़ेद संगमरमर का झरोखा।",
    "space-voyage": "ग्रहों के बीच एक झरोखा, हर कार्यक्रम के लिए सितारों वाली पट्टिका।",
    "rainbow-unicorn": "रुई जैसे बादल और इंद्रधनुष, साथ में एक यूनिकॉर्न।",
    "dino-jungle": "ज्वालामुखी वाला जंगल, एक प्यारा डायनासोर और लकड़ी का बोर्ड।",
    "ocean-pearl": "सीपियों और मोतियों वाला समुद्र तल, ऊपर से आती धूप।",
    "boho-onederland": "हल्के रंग, पम्पास घास और बेंत का आईना, पहले जन्मदिन के लिए।",
    "fairytale-castle": "गुलाबी शाम में परियों का महल, बग्घी और सुनहरा पत्र।",
    "little-racer": "चेकर झंडों, ट्रॉफी और दो छोटी गाड़ियों वाला रेस ट्रैक।",
    "gold-gala": "काले और सुनहरे आर्ट डेको में, मोमबत्तियों और सफ़ेद गुलाबों के साथ।",
    "amrit-utsav": "60वें, 75वें या 100वें जन्मदिन के लिए पीतल के दीये और गेंदे।",
    "silver-jubilee": "25 साल साथ के लिए चांदी, सफ़ेद गुलाब और शाम की झील।",
    "golden-jubilee": "50 साल साथ के लिए सुनहरा फ्रेम, ग्रामोफोन और ढलती धूप।",
    "oh-baby": "हल्के आसमान में गर्म हवा के गुब्बारे, नीचे टेडी।",
    "new-year-eve": "शहर पर आतिशबाज़ी, साथ में शैम्पेन और सुनहरे गुब्बारे।",
    "kitty-tea": "सहेलियों की दोपहर के लिए पियोनी, मैकरून और नाज़ुक कप।",
    "pool-party": "गर्मी के दिन नीला पूल, गुड़हल और तैरने वाला छल्ला।",
    "baraat-band": "शाम की महल वाली गली, बैंड बाजा और सजी हुई सफ़ेद घोड़ी।",
    "roka-shagun": "लाल दीवार, शगुन की थालियाँ और सोना, पहले वचन के लिए।",
    "chooda-ceremony": "हवेली के आँगन में लाल-सफ़ेद चूड़ा, कलीरे और गेंदे।",
    "rishikesh-ganga": "गंगा पर गेंदे की मालाएँ और शाम को तैरते दीये।",
    "jaisalmer-dunes": "सुनहरी रेत, नक्काशीदार झरोखा और रेगिस्तान की लालटेनें।",
    "fort-night": "अँधेरी झील के पार जगमगाता किला, गेंदे और दीये।",
    "sheesh-mahal": "सुनहरी चमक वाला शीशों का महल, लाल कालीन और दीये।",
    "white-rann": "कच्छ का नमक रेगिस्तान, हल्का आसमान, लालटेन और मोगरा।",
    annaprashan: "केले के पत्तों की माला, चाँदी की कटोरी में खीर और सुबह की हल्की धूप।",
    "christening-lilies": "सफ़ेद कुमुदिनी, जैतून के पत्ते और समुद्र किनारे का फव्वारा।",
    "new-home-modern": "पौधों, लालटेन और झूले वाली धूप भरी बालकनी।",
    satyanarayan: "कथा के लिए पीतल के कलश, केले के पत्ते और गेंदे।",
    "mata-ki-chowki": "जागरण के लिए लाल मख़मल, गेंदे की मालाएँ और दीयों की कतारें।",
    upanayana: "जनेऊ के लिए नक्काशीदार पत्थर, मोगरा और सुबह की शांति।",
    shraddhanjali: "श्रद्धांजलि सभा के लिए सफ़ेद रजनीगंधा और हल्की रोशनी।",
    "retirement-garden": "पहाड़ियों पर ढलती शाम और बगीचे की छत।",
    "farewell-night": "तारों तले कॉलेज के आँगन पर जगमग रोशनी।",
    "grand-opening": "पहले दिन के लिए लाल फ़ीता, गेंदे के खंभे और पीतल के कलश।",
    "launch-stage": "अँधेरा मंच, चमकती स्क्रीन और कुर्सियों की कतारें।",
    "ganesh-utsav": "बप्पा के स्वागत में गेंदे, गुलाब और केले के पत्ते।",
    "durga-pujo": "पूजा के लिए लाल-सफ़ेद शोला, ढाक और दीये।",
    janmashtami: "कान्हा के लिए मोरपंख, बाँसुरी और आधी रात का आसमान।",
    "onam-pookalam": "पूक्कलम, फूलों की माला और धूप में बैकवाटर।",
    "pongal-kolam": "पोंगल की मिट्टी की हांडियाँ, गन्ना और दरवाज़े पर कोलम।",
    "uttarayan-kites": "जनवरी के साफ़ आसमान में छतों पर रंग-बिरंगी पतंगें।",
    "lohri-bonfire": "रात का गाँव का आँगन, फुलकारी और अलाव की रोशनी।",
    "iftar-dawat": "इफ़्तार के लिए जाली का मेहराब, लालटेन और ढलती शाम में खजूर।",
    "kadamb-krishna": "वृंदावन के कदंब कुंज के ऊपर राधा-कृष्ण, यमुना किनारे कदंब के फूल और मोर।",
    "ganesh-genda": "गेंदे की लड़ियों, आम के पत्तों और पीतल की घंटियों वाले आँगन के ऊपर गणेश जी।",
    "siya-ram-mala": "राजसी बाग़ के ऊपर सीता-राम, लाल गुलाब और मोगरे की जयमाला वाले फ़्रेम।",
    "kailash-kamal": "सुबह के हिमालयी बुग्याल में ब्रह्मकमल के ऊपर शिव-पार्वती।",
    "kamal-sarovar": "सुबह का गुलाबी कमल सरोवर, ठहरे पानी पर कमल के फ़्रेम।",
    gulmohar: "नीले आसमान के नीचे खिले लाल गुलमोहर की राह।",
    "vat-vriksha": "सुनहरी शाम में विशाल बरगद, डालियों से झूले जैसे लटकते फ़्रेम।",
    "mogra-raat": "चाँदनी रात में मोगरे का बाग़, जुगनू और गहरा नीला आसमान।",
    "tulip-kashmir": "बर्फ़ीले पहाड़ों के नीचे कश्मीर का वसंती ट्यूलिप बाग़।",
    "wisteria-tunnel": "झूलते बैंगनी विस्टेरिया की बाग़ वाली सुरंग, हल्की और सपनीली।",
    "prem-vriksh": "गुलाबी फूलों से भरा प्रेम का पेड़, लवबर्ड और झिलमिल रोशनी।",
    amaltas: "गर्मी की धूप में सुनहरी बारिश सी झूलती अमलतास की लड़ियाँ।",
    "palash-van": "वसंत का पलाश वन, केसरिया आसमान के नीचे दहकते फूल।",
    "parijat-angan": "सुबह का पुराना आँगन, पारिजात के झरते फूलों का बिछौना।",
    "aam-bagiya": "गर्मी की शुरुआत की आम की बगिया, सुनहरे आम, बौर और झूला।",
    "vazhai-mandap": "केले के पत्तों, नारियल के फूलों और मोगरे वाला दक्षिण भारतीय बाग़।",
    "mor-bagh": "बारिश के बाद का राजसी बाग़, नाचते मोर और पंखों के फ़्रेम।",
    "orchid-meghalaya": "पहाड़ों का धुंध भरा वर्षावन, झरना और जंगली ऑर्किड।",
    "rhododendron-himalaya": "वसंत की धुंध में लाल-गुलाबी बुरांश से भरी हिमालयी ढलान।",
    "sunflower-haldi": "हल्दी के लिए खिला सूरजमुखी का खेत और हल्दी की कटोरी।",
    "lavender-field": "ढलती शाम में लैवेंडर की लहराती कतारें, डेज़ी और तितलियाँ।",
    "hydrangea-blue": "सुबह की ताज़ा रोशनी में झील किनारे नीली हाइड्रेंजिया और सफ़ेद गुलाब।",
    "peony-blush": "हल्की गुलाबी पियोनी और गुलाबों का सपनीला बाग़।",
    "magnolia-moon": "शांत झील किनारे पूरे चाँद के नीचे चमकते सफ़ेद मैगनोलिया।",
    "phool-chandelier": "झरते ऑर्किड, गुलाब और क्रिस्टल लड़ियों के नीचे मोमबत्ती से जगमग हॉल।",
    "mor-kamal": "हल्के गुलाबी जलरंग में मोर और कमल के साथ चित्रित जोड़ा। तस्वीरों की ज़रूरत नहीं।",
    "rajwada-haathi":
      "राजस्थानी लघुचित्र: दो हाथियों के बीच सुनहरे छत्र के नीचे जोड़ा। तस्वीरों की ज़रूरत नहीं।",
    "madhubani-machhli":
      "मिथिला की मधुबनी कला: सूरज, बांस, मछलियाँ और वरमाला लिए जोड़ा। तस्वीरों की ज़रूरत नहीं।",
    "pichwai-gaay":
      "पिछवाई की रात: चांद के नीचे कमल ताल के पास सफ़ेद गायों संग जोड़ा। तस्वीरों की ज़रूरत नहीं।",
    "kerala-mural": "केरल भित्तिचित्र: थाली, सजा हाथी और पीतल का दीपक। तस्वीरों की ज़रूरत नहीं।",
    "kalyana-vazhai":
      "केले के पौधों के बीच पवित्र अग्नि के पास दक्षिण भारतीय मंदिर विवाह। तस्वीरों की ज़रूरत नहीं।",
    "alpana-topor":
      "शोला मुकुट, पान के पत्ते और सफ़ेद अल्पना के साथ बंगाली विवाह। तस्वीरों की ज़रूरत नहीं।",
    "kutch-rang": "डांडिया खेलता गुजराती जोड़ा, शीशे का काम, ढोल और ऊँट। तस्वीरों की ज़रूरत नहीं।",
    "mughal-bagh": "रात के मुग़ल बाग़ में निकाह: लालटेन, सरू और फ़व्वारा। तस्वीरों की ज़रूरत नहीं।",
    "phulkari-lavan":
      "फुलकारी किनारों के बीच गेंदे के फूलों संग आनंद कारज। तस्वीरों की ज़रूरत नहीं।",
    "safed-gulaab":
      "सफ़ेद गुलाब, कबूतर और फूलों के मेहराब के साथ बाग़ में विवाह। तस्वीरों की ज़रूरत नहीं।",
    "line-art-gold":
      "एक सुनहरी रेखा में बना आधुनिक जोड़ा, यूकेलिप्टस की पत्तियों के साथ। तस्वीरों की ज़रूरत नहीं।",
    "samudra-sanjh":
      "सूर्यास्त के समय ताड़ के पेड़ों के बीच समुद्र तट पर विवाह। तस्वीरों की ज़रूरत नहीं।",
    "kaagaz-chaand":
      "परतदार काग़ज़ कला: सुनहरे चांद के नीचे पहाड़ियों पर जोड़ा। तस्वीरों की ज़रूरत नहीं।",
    "doli-vidaai":
      "गाँव से गुज़रती डोली और सफ़ेद घोड़े पर दूल्हा, लोक कला में। तस्वीरों की ज़रूरत नहीं।",
    "haldi-genda":
      "गेंदे की लड़ियों और हल्दी के कटोरे के साथ धूप भरी हल्दी। तस्वीरों की ज़रूरत नहीं।",
    "mehendi-jhoola":
      "फूलों के झूले पर मेहंदी लगे हाथों वाली दुल्हन और तोते। तस्वीरों की ज़रूरत नहीं।",
    "sangeet-dhol": "जगमग रोशनी, ढोल और नाचता जोड़ा, संगीत की रात। तस्वीरों की ज़रूरत नहीं।",
    "pehla-janamdin":
      "बादलों में पहला जन्मदिन: गुब्बारे, केक और जानवर दोस्त। तस्वीरों की ज़रूरत नहीं।",
    "godh-bharai": "पालना, हंस और गुलाब की माला के साथ कोमल गोद भराई। तस्वीरों की ज़रूरत नहीं।",
    "griha-kalash":
      "गृह प्रवेश: कलश, तोरण और रंगोली के साथ नए दरवाज़े पर जोड़ा। तस्वीरों की ज़रूरत नहीं।",
    "sona-saath":
      "सूर्यास्त में नीम के पेड़ तले झूले पर सालगिरह मनाता जोड़ा। तस्वीरों की ज़रूरत नहीं।",
    "bagh-reception":
      "गज़ीबो, हंस, लटकते फूल और दीपों के साथ बाग़ में रिसेप्शन। तस्वीरों की ज़रूरत नहीं।",
    "naamkaran-chanda":
      "अर्धचंद्र और काग़ज़ी सारसों के नीचे गेंदे से सजे पालने पर झुके माता-पिता। तस्वीरों की ज़रूरत नहीं।",
    "swagat-laxmi":
      "घंटियों और गुलाबों के नीचे, घर आए नन्हे मेहमान पर दादा-दादी फूल बरसाते हुए। तस्वीरों की ज़रूरत नहीं।",
    "holi-rang":
      "पलाश के पेड़ के पास ढोल की थाप पर गुलाल उड़ाते दोस्त, गुझिया और रंगों की कटोरियाँ। तस्वीरों की ज़रूरत नहीं।",
    "christmas-tara":
      "क्रिसमस ट्री के पास कैरल गाता परिवार, प्लम केक, तोहफ़े और काग़ज़ी तारे। तस्वीरों की ज़रूरत नहीं।",
    "reunion-yaarana":
      "पुरानी तस्वीर, क्रिकेट बैट और टिफ़िन के साथ स्कूल की सीढ़ियों पर पुराने दोस्त। तस्वीरों की ज़रूरत नहीं।",
    "graduation-topi":
      "उड़ती टोपियों, गुब्बारों और सूरजमुखी के नीचे ग्रेजुएट को गले लगाते माता-पिता। तस्वीरों की ज़रूरत नहीं।",
    "gudi-padwa":
      "ऊँची गुड़ी के पास मराठी परिवार, पूरन पोली और फूलों की रंगोली। तस्वीरों की ज़रूरत नहीं।",
    "baisakhi-mela":
      "सुनहरे गेहूँ में भांगड़ा और गिद्धा, पतंगें, ढोल और गाँव का मेला। तस्वीरों की ज़रूरत नहीं।",
    "bihu-utsav":
      "मेखला चादर में बिहू नर्तक, ढोल और पेपा, कपौ फूल और पीठा। तस्वीरों की ज़रूरत नहीं।",
    "gond-vriksh":
      "पक्षियों से भरा गोंड जीवन-वृक्ष, नीचे हिरण और मोर के साथ जोड़ा। तस्वीरों की ज़रूरत नहीं।",
    "warli-vivah":
      "लाल मिट्टी पर वारली नर्तक दूल्हा-दुल्हन की गाड़ी के चारों ओर नाचते हुए। तस्वीरों की ज़रूरत नहीं।",
    "kalighat-pat":
      "दो रोहू मछलियों के बीच, कालीघाट शैली में बंगाली दूल्हा-दुल्हन। तस्वीरों की ज़रूरत नहीं।",
    "cheriyal-talambralu":
      "चेरियाल चित्रपट में एक-दूसरे पर चावल बरसाता तेलुगु जोड़ा। तस्वीरों की ज़रूरत नहीं।",
    "axomiya-biya":
      "गमोसा की झालर के नीचे मुगा रेशम में असमिया जोड़ा, ज़ोराई और चाय के बागान। तस्वीरों की ज़रूरत नहीं।",
    "antarpat-mangal":
      "दो पीतल की समई के बीच, अंतरपट की घड़ी पर मराठी विवाह। तस्वीरों की ज़रूरत नहीं।",
    "kangra-megh":
      "पहाड़ी लघुचित्र: पहली बारिश में एक छाते के नीचे जोड़ा। तस्वीरों की ज़रूरत नहीं।",
    "hyderabadi-nikah":
      "चमेली की लड़ियों और पीतल की लालटेनों के नीचे दक्कनी निकाह। तस्वीरों की ज़रूरत नहीं।",
    "goa-azulejo":
      "नीले-सफ़ेद गोवा टाइलों पर चित्रित समुद्र किनारे की शादी। तस्वीरों की ज़रूरत नहीं।",
    "pressed-phool":
      "हाथ से बने कागज़ पर दबाए हुए जंगली फूल और फ़र्न, सादा और आधुनिक। तस्वीरों की ज़रूरत नहीं।",
    "tuscan-vineyard": "सुनहरी शाम में अंगूर के बाग़ों के बीच चलता जोड़ा। तस्वीरों की ज़रूरत नहीं।",
    "boho-pampas":
      "पैम्पस घास, मैक्रेमे और मोमबत्तियों के बीच बोहो अंदाज़ का जोड़ा। तस्वीरों की ज़रूरत नहीं।",
    "winter-pine":
      "बर्फ़ से ढके देवदारों और गर्म लालटेनों के बीच सर्दियों की शादी। तस्वीरों की ज़रूरत नहीं।",
    "kantha-silai":
      "मुलायम सफ़ेद सूती कपड़े पर कांथा टाँकों में कही गई शादी। तस्वीरों की ज़रूरत नहीं।",
    "tholu-bommalata":
      "दीये से जगमगाते परदे पर आंध्र की छाया-कठपुतली शादी। तस्वीरों की ज़रूरत नहीं।",
    "chikankari-awadh":
      "लखनऊ की चिकनकारी, सफ़ेद पर सफ़ेद, कढ़ाई वाले सरू के पेड़ों के बीच जोड़ा। तस्वीरों की ज़रूरत नहीं।",
    "bidri-raat":
      "काले पर बिदरी चाँदी की नक्काशी: चाँदी के मंडप के नीचे जोड़ा। तस्वीरों की ज़रूरत नहीं।",
    "stained-glass":
      "गुलाब, लिली और कबूतरों वाली धूप में चमकती रंगीन काँच की खिड़की। तस्वीरों की ज़रूरत नहीं।",
    "chinoiserie-bagh":
      "हाथ से बनी शिनुआज़री: पियोनी, पक्षी और बाग़ के पुल पर जोड़ा। तस्वीरों की ज़रूरत नहीं।",
    "nouveau-arch": "जोड़े के चारों ओर लिली और आइरिस का आर्ट नूवो मेहराब। तस्वीरों की ज़रूरत नहीं।",
    "safar-shaadi":
      "डेस्टिनेशन शादी के लिए यात्रा स्क्रैपबुक: टिकट, कम्पास और सूटकेस। तस्वीरों की ज़रूरत नहीं।",
    "chibi-jodi":
      "हाथी के बच्चे और छोटे घोड़े के साथ प्यारी कार्टून दुल्हन और दूल्हा। तस्वीरों की ज़रूरत नहीं।",
    "jaago-gagar":
      "पंजाबी जागो की रात: दीयों वाली पीतल की गागर, फुलकारी और ढोल। तस्वीरों की ज़रूरत नहीं।",
    "tilak-thaal":
      "तिलक की रस्म: दुल्हन का परिवार दूल्हे का स्वागत करता है। तस्वीरों की ज़रूरत नहीं।",
    "nalangu-vilayattu":
      "तमिल नलंगु के खेल: नारियल लुढ़काता जोड़ा, ख़ुश होता परिवार। तस्वीरों की ज़रूरत नहीं।",
    "sagai-anguthi":
      "हल्के गुलाबी जलरंग में गुलाब बाग़ में अँगूठी की रस्म। तस्वीरों की ज़रूरत नहीं।",
    "chandni-cocktail":
      "परी-बत्तियों के नीचे छत पर शादी से पहले की पार्टी। तस्वीरों की ज़रूरत नहीं।",
    "kathputli-sangeet": "नाचती कठपुतलियों के साथ राजस्थानी संगीत। तस्वीरों की ज़रूरत नहीं।",
    sehrabandi: "बारात से पहले परिवार दूल्हे का सेहरा बाँधता है। तस्वीरों की ज़रूरत नहीं।",
    "laxmi-aagman": "चावल का कलश गिराकर दुल्हन का नए घर में स्वागत। तस्वीरों की ज़रूरत नहीं।",
    shashtipurti: "60वें जन्मदिन का आशीर्वाद, फूल बरसाता परिवार। तस्वीरों की ज़रूरत नहीं।",
    "circus-tent": "छोटे रिंगमास्टर, हाथी और सील के साथ सर्कस जन्मदिन। तस्वीरों की ज़रूरत नहीं।",
    "toy-train":
      "हरी पहाड़ियों पर गुब्बारे, केक और तोहफ़े ले जाती लकड़ी की रेल। तस्वीरों की ज़रूरत नहीं।",
    "pet-party": "कुत्ते का जन्मदिन: दोस्त, केक और पंजे वाले गुब्बारे। तस्वीरों की ज़रूरत नहीं।",
    "mixtape-party":
      "पोलरॉइड, बूमबॉक्स और रोलर स्केट्स वाली रेट्रो कैसेट पार्टी। तस्वीरों की ज़रूरत नहीं।",
    "pehli-salgirah":
      "चाँद के नीचे लालटेनों से सजी हाउसबोट पर पहली सालगिरह। तस्वीरों की ज़रूरत नहीं।",
    "eid-milan": "लालटेनों और चाँद के नीचे परिवार का ईद मिलन। तस्वीरों की ज़रूरत नहीं।",
    "garba-raas":
      "डांडिया, शीशे के काम और गरबो दीयों वाली नवरात्रि गरबा रात। तस्वीरों की ज़रूरत नहीं।",
    valaikappu: "होने वाली माँ के लिए तमिल चूड़ी की रस्म। तस्वीरों की ज़रूरत नहीं।",
    "shubh-labh": "दुकान का उद्घाटन: गेंदे से सजे द्वार पर फ़ीता काटना। तस्वीरों की ज़रूरत नहीं।",
    "retirement-naav":
      "नए सफ़र की तरह रिटायरमेंट: सूर्योदय में नाव से रवाना। तस्वीरों की ज़रूरत नहीं।",
    "phad-gatha":
      "ऊँट, मोर और घोड़े-हाथी की सवारी वाला राजस्थानी फड़ चित्र। आप दोनों की तस्वीरों के लिए दो फ़्रेम।",
    "mandana-lal":
      "लाल मिट्टी पर सफ़ेद मांडणा मोर और कमल, शब्दों के लिए सादा पलस्तर। आप दोनों की तस्वीरों के लिए दो फ़्रेम।",
    "gota-patti":
      "रानी गुलाबी रेशम पर सुनहरी गोटा पत्ती और सितारे, किनारे पर फुंदने। आप दोनों की तस्वीरों के लिए दो फ़्रेम।",
    "pithora-ghoda":
      "सफ़ेद दीवार पर बिंदियों वाले पिथोरा घोड़े, पंछी, सूरज और चाँद। आप दोनों की तस्वीरों के लिए दो फ़्रेम।",
    "sohrai-khovar":
      "झारखंड की मिट्टी की दीवार पर मोर, बैल और गाय, फूलों वाले पेड़ के नीचे। आप दोनों की तस्वीरों के लिए दो फ़्रेम।",
    "aipan-kumaon":
      "लाल गेरू पर चावल के घोल से बना कुमाऊँनी ऐपण, कमल और पहाड़ी चीड़। आप दोनों की तस्वीरों के लिए दो फ़्रेम।",
    "pipli-chhata":
      "ओडिशा का पिपली काम: छतरियाँ, तोते और हाथी, छोटे शीशों के साथ। आप दोनों की तस्वीरों के लिए दो फ़्रेम।",
    "bishnupur-terracotta":
      "बंगाल का नक्काशीदार टेराकोटा, बांकुड़ा घोड़ा और नावों-हाथियों की पट्टी। आप दोनों की तस्वीरों के लिए दो फ़्रेम।",
    "ganjifa-patte":
      "लाल, सुनहरे और हरे रंग के गोल मैसूरु गंजीफ़ा पत्ते और चंदन की डिब्बियाँ। आप दोनों की तस्वीरों के लिए दो फ़्रेम।",
    "kanjivaram-pattu":
      "मंदिर-शिखरों और मोरों की ज़री वाली मैरून कांजीवरम रेशम। आप दोनों की तस्वीरों के लिए दो फ़्रेम।",
    "kasavu-sona":
      "सुनहरे किनारे वाली केरल की कसवु, पीतल का दीया और मोगरे की लड़ियाँ। आप दोनों की तस्वीरों के लिए दो फ़्रेम।",
    "urli-pookal":
      "पीतल के फ़्रेम, गेंदे की लड़ियाँ और तैरते फूलों व दीयों वाली उरली। आप दोनों की तस्वीरों के लिए दो फ़्रेम।",
    "kar-e-kashmir":
      "चिनार के पत्तों, गुलाब, आइरिस और बुलबुल से सजा कश्मीरी पेपर-माशे। आप दोनों की तस्वीरों के लिए दो फ़्रेम।",
    "zardozi-mehfil":
      "गहरे मैरून मखमल पर उभरी सुनहरी ज़रदोज़ी और मोती, निकाह या रिसेप्शन के लिए। आप दोनों की तस्वीरों के लिए दो फ़्रेम।",
    "patola-bandh":
      "लाल, हरे और केसरिया में बुने हाथी और तोते वाला पाटन पटोला। आप दोनों की तस्वीरों के लिए दो फ़्रेम।",
    "kundan-jhumka":
      "गुलाबी रेशम पर कुंदन लटकन, मोतियों का हार, झुमके और चूड़ियाँ। आप दोनों की तस्वीरों के लिए दो फ़्रेम।",
    "moti-bharat":
      "गुजराती मोती भरत: मोतियों का तोरण, तोते और हाथी। आप दोनों की तस्वीरों के लिए दो फ़्रेम।",
    "polaroid-lights":
      "फ़ेयरी लाइट्स पर टँगी दो इंस्टेंट फ़ोटो, सूखे फूल और एक लिफ़ाफ़ा। आप दोनों की तस्वीरों के लिए दो फ़्रेम।",
    "dak-tikat":
      "दो पुराने डाक टिकट, लाख की मुहर, एयरमेल धारियाँ और चिट्ठियों का बंडल। आप दोनों की तस्वीरों के लिए दो फ़्रेम।",
    "kadhai-hoop":
      "छोटे कढ़े फूलों वाले दो लकड़ी के कढ़ाई घेरे और धागे की रीलें। आप दोनों की तस्वीरों के लिए दो फ़्रेम।",
    "locket-jodi":
      "गुलाबी मखमल पर ज़ंजीर से लटके दो पुराने सोने के लॉकेट, मोती और गुलाब। आप दोनों की तस्वीरों के लिए दो फ़्रेम।",
    "syahi-bamboo":
      "चावल के काग़ज़ पर आलूबुख़ारे के फूल, बाँस और दो नन्हे पंछी, स्याही से। आप दोनों की तस्वीरों के लिए दो फ़्रेम।",
    "lace-ivory":
      "आइवरी लेस के मेहराब, साटन के फ़ीते और लिली के फूल, चर्च या बगीचे की शादी के लिए। आप दोनों की तस्वीरों के लिए दो फ़्रेम।",
    "origami-saaras":
      "हल्के रंगों के काग़ज़ी सारस और मुड़े फूल, दो चुन्नटदार काग़ज़ी फ़्रेम के साथ। आप दोनों की तस्वीरों के लिए दो फ़्रेम।",
    "nimbu-amalfi":
      "धूप जैसे नींबू और हाथ से रंगी नीली-पीली टाइलें, गर्मियों की शादी के लिए। आप दोनों की तस्वीरों के लिए दो फ़्रेम।",
    "rail-yatra":
      "दो खिड़कियों वाला पुराना हरा रेल डिब्बा, प्लेटफ़ॉर्म पर सूटकेस और गेंदे। आप दोनों की तस्वीरों के लिए दो फ़्रेम।",
    "rakhi-dor": "एक राखी बहन और भाई के फ़्रेम को जोड़ती है, नीचे रोली, चावल और मिठाई की थाली।",
    "karva-chandni":
      "पूरे चाँद के नीचे दो पीतल की छलनियाँ, सजा करवा, दीया और लाल चूड़ियाँ। आप दोनों की तस्वीरों के लिए दो फ़्रेम।",
    "judwa-taare":
      "जुड़वाँ बच्चों के लिए गुलाबी और नीला तारा, झंडियाँ, गुब्बारे और दो मंज़िला केक।",
    "naya-mehmaan": "होने वाले माता-पिता के लिए दो बादल, पालने के ऊपर झूलते खिलौने से।",
    "jal-mahal":
      "शाम को झील का महल: पानी लहराता है, बेलें झूलती हैं और गुलाब की पंखुड़ियाँ गिरती हैं।",
    "gulmohar-rasta": "खिले गुलमोहर की सड़क, जिस पर लाल फूल लगातार झरते हैं।",
    "genda-barsaat": "हल्दी के लिए गेंदे की बरसात, झूलती तोरण की लड़ियों के साथ।",
    "akash-kandil": "दिवाली की रात दीयों से जगमगाते शहर के ऊपर उड़ते आकाश कंदील।",
    "chand-raat": "मुग़ल आँगन में ईद की रात, झूलती कंदीलें और टिमटिमाते तारे।",
    "titli-bagh": "धूप भरा बाग़ जिसमें तितलियाँ उड़ती हैं और बुलबुले ऊपर तैरते हैं।",
    "malli-mazhai": "मंदिर के तालाब पर मोगरे की बारिश, पानी पर तैरते दीयों के साथ।",
    "shiuli-bhor": "बंगाल के गाँव के तालाब के पास भोर में झरते शिउली के फूल।",
    "sarson-khet": "खिले सरसों के खेत, लहराते फुलकारी दुपट्टे और आसमान में पतंगें।",
    "shamiana-raat": "तारों के नीचे शादी का शामियाना, टिमटिमाती रोशनी और उड़ती चिंगारियाँ।",
    "kettuvallam-raat": "चाँदनी में केरल का बैकवॉटर, डोलती हाउसबोट और घूमते जुगनू।",
    "diya-dhara": "गोधूलि में घाटों के पास नदी पर बहते पत्तों के दीये।",
    "wedding-bells": "पहाड़ी पर सफ़ेद चर्च, झूलती घंटियाँ और उड़ते सफ़ेद कबूतर।",
    "saawan-bundein": "मेहंदी के आँगन पर सावन की बारिश, हिलते खाली झूले के साथ।",
    "hans-jheel": "सूर्यास्त की झील पर हंसों का जोड़ा, धीरे-धीरे गिरती विलो की पत्तियाँ।",
    "navratri-garbi": "गाँव के चौक में जगमगाते गरबो के घड़े, ऊपर उठती चिंगारियाँ।",
    "snow-globe": "काँच के गोले में बर्फ़ीला गाँव, घूमती गिरती बर्फ़ के साथ।",
    "sea-bubbles": "समंदर के भीतर: तैरती मछलियाँ और रोशनी में ऊपर उठते बुलबुले।",
    "badal-sapne": "नरम बादलों पर पालना, ऊपर झूलते खिलौने के साथ।",
    "aangan-subah": "नए घर के आँगन में सुबह: झूलता तोरण और आती-जाती गौरैया।",
    "neeli-nagri": "साँझ की नीली नगरी: क़िले के ऊपर कबूतर, डोलती पतंगें और झूलती लालटेनें।",
    "kesar-kyari": "कश्मीर की केसर क्यारी: घूमकर गिरते चिनार के पत्ते और झील पर तैरती धुंध।",
    "konkan-kinara":
      "सूर्यास्त में कोंकण का किनारा: झूमते नारियल, डोलती नावें और उड़ते समुद्री पक्षी।",
    "megh-jharna": "बादलों में झरना: बहती धुंध, झूमते ऑर्किड और उड़ती तितली।",
    "fawwara-bagh": "चाँदनी में मुग़ल फव्वारे: गिरती पंखुड़ियाँ और घूमते जुगनू।",
    "deodar-sanjh": "देवदार की पहाड़ियों में साँझ: घाटी में तैरते बादल और चक्कर लगाता बाज़।",
    "jhoomar-mahal": "झूमरों वाला महल: झूमते, चमकते झूमर और तैरती गुलाब की पंखुड़ियाँ।",
    "champa-baag": "मंदिर के तालाब पर चंपा: घूमकर गिरते फूल और उड़ते तोते।",
    "tota-bagh": "मेहंदी के बाग़ में तोते: डालियों के बीच उड़ते तोते और गिरती पंखुड़ियाँ।",
    aatishbaazi: "क़िले पर आतिशबाज़ी: आसमान में खिलती रोशनी और झिलमिलाती झील।",
    "toota-taara": "शांत मैदान पर टूटते तारे: टिमटिमाते तारे और घूमते जुगनू।",
    "phoolon-ki-holi": "वृंदावन की फूलों वाली होली: उड़ता गुलाल और बरसती पंखुड़ियाँ।",
    "dahi-handi": "गली के ऊपर झूलती हांडी: झूमते गेंदे और गिरते मोरपंख।",
    "vallam-kali": "ओणम पर सर्प नौकाएँ: झूमते नारियल, गिरती पंखुड़ियाँ और नदी पार उड़ता बगुला।",
    "pongal-paanai": "उफनता पोंगल: उठती भाप, झूमता गन्ना और आसमान में पतंगें।",
    "khazana-dweep": "ख़ज़ाने का द्वीप: डोलता जहाज़, उड़ते पक्षी और चमकते सोने के सिक्के।",
    "kaagaz-ki-kashti": "बारिश में काग़ज़ की कश्तियाँ: धारा में तैरती नावें और हल्की बारिश।",
    "aurora-igloo": "इग्लू पर उत्तरी रोशनी: लहराता ऑरोरा, गिरती बर्फ़ और चलते पेंगुइन।",
    "teddy-picnic": "टेडी भालुओं की पिकनिक: उड़ते गुब्बारे, तैरते बुलबुले और फहराती झंडियाँ।",
    "dukaan-mahurat": "दुकान की पहली सुबह: झूलता तोरण, गिरती पंखुड़ियाँ और उड़ते गुब्बारे।",
    "mameru-bandhani": "मामेरु के लिए बांधनी की साड़ियाँ, पीतल और उपहार।",
    "sindhi-ajrak": "सिंधी शादी के लिए नील और लाल अजरक, गुलाब और फुंदने।",
    "hampi-ruins": "पुराने मंदिरों के बीच पत्थर की सीढ़ियाँ, पीतल के दीये और मोगरा।",
    "coorg-estate": "कॉफ़ी बागान पर धुंध, लाल बेरियाँ और सफ़ेद फूल।",
    "bali-garden": "कमल का तालाब, चंपा और तैरती मोमबत्तियाँ।",
    "santorini-white": "सफ़ेद दीवारें, नीला समुद्र और शाम की बोगनवेलिया।",
    "glass-house": "धूप भरा शीशे का बागीचा, यूकेलिप्टस, गुलाब और मोमबत्तियाँ।",
    "minimal-white": "सफ़ेद फूल, संगमरमर और हल्की मोमबत्ती की रोशनी।",
    "fairy-forest": "जुगनू, धुंध वाली झील और रोशनी में लिपटे पुराने पेड़।",
    "love-letter": "मोहर लगा लिफ़ाफ़ा, गुलाब और पुरानी कलम, तारीख़ बताने के लिए।",
    "parsi-chalk": "हल्की हरी दीवारें, लेस, गुलाब और फ़र्श पर चॉक के नमूने।",
    "jazz-lounge": "संगीत की रात के लिए पन्ना हरा मख़मल, पीतल और जाम।",
    "bride-squad": "दुल्हन की सहेलियों के लिए गुलाबी पियोनी, मैकरून और रिबन।",
    "teej-jhoola": "सावन में फूलों का झूला, मोर और हरी चूड़ियाँ।",
    "cricket-stadium": "हरी पिच, विकेट, बल्ला और सुनहरी ट्रॉफी।",
    "neon-arcade": "खेलों की रात के लिए नियॉन रोशनी, गेम पैड और पॉपकॉर्न।",
    "retro-bollywood": "फ़िल्मी रात के लिए जगमग बत्तियाँ, लाल पर्दा और फ़िल्म रील।",
    "pink-haveli": "जयपुर की गुलाबी हवेली, हर रस्म के लिए शीशे के काम वाली तख़्ती।",
    "char-bagh": "लंबे हौज़ और फ़व्वारों वाला मुग़ल बाग़, जड़ाऊ संगमरमर की तख़्ती के साथ।",
    "kashi-ghat": "सूर्योदय में गंगा के घाट, फूलों से घिरी पीतल की थाली के साथ।",
    "temple-pond": "कमलों वाला केरल का मंदिर-तालाब, कसवु की सुनहरी किनारी वाले ताड़पत्र के साथ।",
    "kovil-corridor":
      "तमिल मंदिर का सुनहरा पत्थर का गलियारा, कोलम बिंदुओं वाली पीतल की थाली के साथ।",
    "arati-mandap": "केले के पत्तों वाला तेलुगु मंडप, आम के पत्तों के तोरण तले हल्दी रंग का कपड़ा।",
    "zamindar-bari": "बंगाल का लाल आँगन, सफ़ेद शोला की तख़्ती के साथ।",
    "kutch-bhunga": "कच्छ का सफ़ेद भूंगा, मिट्टी और शीशों के लिप्पन काम के साथ।",
    "punjab-haveli": "सुनहरे सरसों के खेतों पर पंजाबी हवेली, फुलकारी के साथ।",
    "pune-wada": "महाराष्ट्र के वाडे का आँगन, मोर किनारी वाले पैठणी रेशम के साथ।",
    "chinar-dal": "पतझड़ की डल झील, चिनार के पत्तों के बीच नक़्क़ाशीदार अखरोट का पट।",
    classic: "आपके कार्ड के ही काग़ज़ और रंगों में पन्ने, हर रस्म का अपना दृश्य।",
  },
};

export const studioCopy: Translation<typeof en.studioCopy> = {
  pagesHint: "आप जो पन्ना भर रहे हैं, वह लिखते-लिखते यहाँ दिखता है।",
  pageNames: {
    blessing: "आशीर्वाद",
    cover: "मुखपृष्ठ",
    couple: "फ़ोटो",
    family: "परिवार",
    "family-more": "परिवार, आगे",
    invite: "निमंत्रण",
    reply: "जवाब",
  },
  pageList: "निमंत्रण के पन्ने",
  showPage: (name) => `${name} का पन्ना दिखाएँ`,
  phone: (name) => `${name} का पन्ना, जैसा मेहमान देखेंगे`,
  lettering: "अक्षर",
  letteringIntro:
    "हर पन्ने पर शब्द कैसे दिखें, चुनें। सिर्फ़ वही फ़ॉन्ट दिखते हैं जो आपके कार्ड की भाषा लिख सकते हैं।",
  namesFont: "नाम",
  wordsFont: "बाक़ी शब्द",
  themeFont: "थीम का अपना",
  size: "आकार",
  sizes: { small: "छोटा", medium: "मध्यम", large: "बड़ा" },
  style: "नामों की शैली",
  bold: "मोटा",
  italic: "तिरछा",
  capitals: "बड़े अक्षर",
  colour: "नामों का रंग",
  colours: {
    theme: "थीम का अपना",
    maroon: "मरून",
    gold: "सुनहरा",
    saffron: "केसरिया",
    ink: "स्याही",
    ivory: "हाथीदाँत",
  },
  feels: {
    classic: "पारंपरिक",
    script: "बहता हुआ",
    bold: "गाढ़ा",
    clean: "सादा",
    handwritten: "हाथ से लिखा",
  },
  reset: "थीम के अक्षर वापस लाएँ",
};

export const familyCopy: Translation<typeof en.familyCopy> = {
  heading: "परिवार",
  intro:
    "माता-पिता, आशीर्वाद और मेहमान किसे फ़ोन करें। सब वैकल्पिक है: जो भरेंगे वह परिवार वाले पन्ने पर दिखेगा।",
  open: "परिवार की जानकारी जोड़ें",
  sideHeading: (name) => `${name} का परिवार`,
  sideFallback: { first: "पहला परिवार", second: "दूसरा परिवार" },
  relation: "कार्ड पर ऐसे छपेगा",
  relations: { child: "संतान", daughter: "सुपुत्री", son: "सुपुत्र" },
  parents: "माता-पिता के नाम",
  parentsExample: "श्रीमती सुनीता एवं श्री रमेश पटेल",
  parentsHint: "जैसे छपवाना चाहें वैसे लिखें, श्री, श्रीमती या स्व. के साथ।",
  town: "शहर या गाँव",
  townExample: "अहमदाबाद",
  more: "आशीर्वाद और निमंत्रक",
  examples: {
    blessingsFrom: "श्रीमती कमला देवी एवं श्री रामप्रसाद शर्मा",
    requesters: "समस्त शर्मा परिवार",
    welcome: "राहुल, प्रिया, अंकित",
    children: "मेरे चाचू की शादी में ज़रूर आना",
  },
  memory: "पुण्य स्मृति",
  memoryExample: "स्व. श्री मोहनलाल पटेल",
  memoryHint: "दिवंगत परिजन जिनका आशीर्वाद परिवार याद करता है।",
  contacts: "मेहमान किसे फ़ोन करें",
  contactName: "नाम",
  contactNameExample: "रमेश पटेल",
  phone: "फ़ोन",
  addContact: "नंबर जोड़ें",
  removeContact: (n) => `नंबर ${n} हटाएँ`,
};

export const pageWordsCopy: Translation<typeof en.pageWordsCopy> = {
  open: "यह पन्ना बदलें",
  title: (page) => `${page} का पन्ना`,
  description: "कोई भी पंक्ति बदलें, अपनी जोड़ें, और चुनें कि शब्द चित्र पर कहाँ दिखें।",
  close: "हो गया",
  words: "शब्द",
  line: (n) => `पंक्ति ${n}`,
  kind: (n) => `पंक्ति ${n} का प्रकार`,
  kinds: {
    label: "छोटा शीर्षक",
    script: "आशीर्वचन",
    display: "बड़ा",
    date: "तारीख़",
    venue: "स्थान",
    body: "सामान्य",
    small: "छोटे अक्षर",
  },
  up: (n) => `पंक्ति ${n} ऊपर करें`,
  down: (n) => `पंक्ति ${n} नीचे करें`,
  remove: (n) => `पंक्ति ${n} हटाएँ`,
  add: "पंक्ति जोड़ें",
  reset: "सुझाए गए शब्द वापस लाएँ",
  own: "यह पन्ना आपने खुद लिखा है। बाद में बदले गए नाम, तारीख़ या जगह यहाँ तभी दिखेंगे जब आप सुझाए गए शब्द वापस लाएँगे।",
  inLanguage: (language) => `ये शब्द ${language} कार्ड के लिए हैं।`,
  overflow:
    "इस चित्र के लिए शब्द बहुत ज़्यादा हैं, सबसे छोटे आकार में भी। कोई पंक्ति छोटी करें या हटाएँ।",
  placement: "जगह",
  place: "ऊँचाई",
  places: { top: "ऊपर", middle: "बीच में", bottom: "नीचे" },
  align: "संरेखण",
  aligns: { center: "बीच में", start: "बाईं ओर" },
  box: "शब्दों के पीछे डिब्बा",
  boxes: { theme: "बाकी पन्नों जैसा", on: "डिब्बा", off: "चित्र पर छपा" },
  hide: "यह पन्ना हटाएँ",
  hideHint: "मेहमानों को नहीं दिखेगा। कभी भी वापस चालू करें।",
  hidden: "हटाया गया",
};

export const aiCopy: Translation<typeof en.aiCopy> = {
  open: "AI से लिखवाएँ",
  title: "AI से शब्द लिखवाएँ",
  description:
    "AI आपके नाम, परिवार और रस्मों से पन्ने कार्ड की भाषा में लिखता है। बाद में कुछ भी बदलें।",
  close: "बंद करें",
  tone: "अंदाज़",
  tones: { traditional: "पारंपरिक", warm: "आत्मीय", fun: "मज़ेदार" },
  scope: "पन्ने",
  scopes: { all: "सभी पन्ने", page: (page) => `सिर्फ़ ${page} का पन्ना` },
  write: "लिखें",
  again: "फिर से लिखें",
  shorten: "AI से छोटा करें",
  busy: "लिखा जा रहा है…",
  done: "लिख दिया। शब्द बदलने के लिए कोई भी पन्ना खोलें।",
  left: (n) => `इस निमंत्रण पर ${n} मुफ़्त ड्राफ़्ट बाकी हैं।`,
  languages: (language) =>
    `${language} कार्ड के लिए लिखा गया। दूसरी भाषा के लिए ऊपर कार्ड की भाषा बदलें।`,
  errors: {
    "sign-in": "साइन इन करें ताकि निमंत्रण सेव हो, फिर AI उसके लिए लिख सकेगा।",
    off: "AI से लिखवाना अभी चालू नहीं है।",
    "not-found": "साइन इन करें ताकि निमंत्रण सेव हो, फिर AI उसके लिए लिख सकेगा।",
    "used-up":
      "इस निमंत्रण के 3 मुफ़्त ड्राफ़्ट पूरे हो गए। किसी भी पैकेज में जितनी बार चाहें लिखवाएँ।",
    failed: "अभी शब्द नहीं लिखे जा सके। फिर से कोशिश करें।",
  },
};

export const openingCopy: Translation<typeof en.openingCopy> = {
  heading: "निमंत्रण कैसे खुले",
  intro:
    "मेहमान सबसे पहले यही देखेंगे, पूरी स्क्रीन पर, आपके नाम और उलटी गिनती के साथ। खुलते हुए देखने के लिए कोई शैली चुनें।",
  styles: {
    doors: {
      name: "थीम के द्वार",
      description: "आपकी थीम की पेंटिंग बीच से दो दरवाज़ों की तरह खुलती है।",
    },
    palace: {
      name: "महल के द्वार",
      description: "तोरण वाली मेहराब के नीचे नक्काशीदार दरवाज़े सुनहरी रोशनी में खुलते हैं।",
    },
    temple: {
      name: "मंदिर के द्वार",
      description: "सुनहरे गोपुरम के नीचे घंटियों और दीयों वाले पीतल के दरवाज़े।",
    },
    curtain: {
      name: "रेशमी पर्दे",
      description: "झिलमिल रोशनियों वाले मखमली पर्दे मंच की तरह हटते हैं।",
    },
    envelope: {
      name: "शाही लिफ़ाफ़ा",
      description: "आपके नाम के अक्षरों वाली मोहर टूटती है और कार्ड बाहर आता है।",
    },
    lotus: {
      name: "खिलता कमल",
      description: "आपके नामों के चारों ओर बड़ा कमल पंखुड़ी-दर-पंखुड़ी खिलता है।",
    },
    mandap: {
      name: "विवाह मंडप",
      description: "केले के पत्तों वाले खंभों और मोगरे की लड़ियों के बीच झीने पर्दे ऊपर उठते हैं।",
    },
    jharokha: {
      name: "झरोखा",
      description: "बलुआ पत्थर के झरोखे की चार जाली वाली खिड़कियाँ मुड़कर खुलती हैं।",
    },
    phool: {
      name: "फूलों का पर्दा",
      description: "गेंदे, गुलाब और मोगरे की लड़ियाँ बीच से हटती हैं।",
    },
    scroll: {
      name: "शाही फ़रमान",
      description: "रिबन खुलता है और फ़रमान अपने आप लिपट जाता है।",
    },
    diyas: {
      name: "दीयों की कतार",
      description: "दीये एक-एक कर जलते हैं, फिर सुनहरी रोशनी फैल जाती है।",
    },
    rangoli: {
      name: "रंगोली",
      description: "रंगोली अपने आप रंगों में बनती है, फिर रोशनी में घूमकर खुलती है।",
    },
    peacock: {
      name: "मोर पंख",
      description: "आपके नामों के पीछे मोर के पंख फैलते हैं, फिर सिमट जाते हैं।",
    },
    storybook: {
      name: "कहानी की किताब",
      description: "सुनहरी कढ़ाई वाला कवर पहले पन्ने तक खुलता है।",
    },
    lanterns: {
      name: "आसमानी कंदील",
      description: "रात में चमकती कागज़ की कंदीलें तैरती हैं, फिर ऊपर उड़ जाती हैं।",
    },
    moonlit: {
      name: "चाँदनी रात",
      description: "मेहराबों के ऊपर अर्धचंद्र, तारे और झूलती कंदीलें।",
    },
    fireworks: {
      name: "आतिशबाज़ी",
      description: "गुंबदों के ऊपर आतिशबाज़ी होती है।",
    },
    balloons: {
      name: "गुब्बारे",
      description: "गुब्बारों से भरा आसमान ऊपर उड़ जाता है।",
    },
    gift: {
      name: "उपहार का डिब्बा",
      description: "रिबन खुलता है और ढक्कन उठ जाता है।",
    },
    none: {
      name: "सीधे अंदर",
      description: "कोई द्वार नहीं: मेहमान सीधे दृश्य पर पहुँचते हैं।",
    },
  },
  groups: {
    doors: "दरवाज़े और द्वार",
    reveals: "पर्दे और खुलते पल",
    light: "रोशनी और फूल",
    party: "पार्टी",
  },
  godHeading: "ऊपर भगवान या शुभ चिह्न",
  godIntro:
    "ऊपर बीच में पूरा दिखता है, किसी शब्द के नीचे नहीं। बिना भगवान के खोलना हो तो इसे बंद रखें।",
  noGod: "कोई नहीं",
  gods: {
    ganesha: "गणेश जी",
    "ganesha-gold": "सुनहरे गणेश जी",
    "lakshmi-ganesha": "लक्ष्मी-गणेश",
    shrinathji: "श्रीनाथजी",
    venkateswara: "वेंकटेश्वर",
    jagannath: "जगन्नाथ",
    om: "ॐ",
    swastik: "स्वस्तिक",
    kalash: "मंगल कलश",
  },
};
