import type { GuestText } from "@/i18n/copy/guest";
import { site } from "@/lib/site";

/*
 * ગુજરાતી: મહેમાનનું પાનું, જવાબ અને ફોટો દીવાલ. English: src/content/publish.ts and
 * src/content/photo-wall.ts. Drafts for a native proofreader.
 */

const photos = (count: number) =>
  count === 1 ? "1 ફોટો" : `${count.toLocaleString("en-IN")} ફોટા`;

export const guestText: GuestText = {
  guestCopy: {
    metaTitle: (names, occasion) => `${names} · ${occasion} આમંત્રણ`,
    metaDescription: (when, where) =>
      [when, where].filter(Boolean).join(" · ") || "આપને આમંત્રણ છે. વિગતો જોવા આમંત્રણ ખોલો.",
    invited: "આપને આમંત્રણ છે",
    openHint: "ખોલવા માટે કાર્ડ પર ટૅપ કરો",
    doorway: {
      open: "આમંત્રણ ખોલો",
      again: "ફરી ખોલો",
      counting: "ઉજવણીની ઊલટી ગણતરી",
      details: "વિગતો જુઓ",
      skip: "આગળ વધો",
    },
    countdown: {
      days: (n) => `હજુ ${n} દિવસ`,
      tomorrow: "આવતીકાલે",
      today: "આજે",
    },
    reply: "આમંત્રણનો જવાબ આપો",
    functions: "પ્રસંગો",
    family: "પરિવાર તરફથી સપ્રેમ",
    cardLanguage: "કાર્ડની ભાષા",
    timeRange: (start, end) => `${start} થી ${end}`,
    when: "ક્યારે",
    where: "ક્યાં",
    dressCode: "પહેરવેશ",
    directions: "રસ્તો",
    parking: "પાર્કિંગ",
    showMap: "નકશો",
    hideMap: "નકશો છુપાવો",
    mapTitle: (place) => `${place} નો નકશો`,
    eventDay: {
      now: "અત્યારે ચાલુ છે",
      later: "આજે પછીથી",
      at: (name, time) => (time ? `${name}, ${time}` : name),
      details: "વિગતો",
      dismiss: "આ પટ્ટી છુપાવો",
    },
    addToCalendar: "કૅલેન્ડરમાં ઉમેરો",
    googleCalendar: "Google કૅલેન્ડર",
    appleCalendar: "Apple, Outlook અને અન્ય",
    addAll: "બધું કૅલેન્ડરમાં ઉમેરો",
    photos: "ફોટા",
    photoAlt: (index) => `પરિવારનો ફોટો ${index}`,
    madeWith: `${site.name} વડે બનાવેલું`,
    createYours: "આપનું પોતાનું આમંત્રણ બનાવો",
    notFoundTitle: "આ આમંત્રણ ઉપલબ્ધ નથી",
    notFoundBody:
      "લિંક કદાચ ખોટી લખાઈ છે, અથવા પરિવારે તે મોકલવાનું બંધ કર્યું છે. તેમને ફરી મોકલવા કહો.",
    home: `${site.name} પર જાઓ`,
    scene: {
      label: "એક પછી એક બધા પ્રસંગો",
      previous: "પાછલો પ્રસંગ",
      next: "આગલો પ્રસંગ",
      pause: "પ્રસંગો રોકો",
      play: "પ્રસંગો ચલાવો",
      position: (n, total) => `${total} માંથી ${n}`,
      details: "બધી વિગતો",
      initials: "અહીં આપનો ફોટો આવશે",
    },
    themed: {
      invitedTo: "આનંદ સાથે આપને ઉજવણીમાં આમંત્રણ",
      shower: "જોડી પર ફૂલ વરસાવો",
      showered: "આપનાં ફૂલ જોડી સુધી પહોંચી રહ્યાં છે.",
      music: { play: "સંગીત વગાડો", pause: "સંગીત રોકો" },
      lamps: {
        diyas: "દીવા પ્રગટાવો",
        lanterns: "ફાનસ પ્રગટાવો",
        nilavilakku: "દીપ પ્રગટાવો",
        fairy: "રોશની ચાલુ કરો",
      },
      lampsLabel: "જોડી માટે એક દીવો પ્રગટાવો",
      lit: "આભાર. જોડી માટે આપનો દીવો પ્રગટી ગયો છે.",
      blessingLabel: "વડીલોના આશીર્વાદ સાથે",
      eventsLabel: "સવારથી રાત સુધી",
      saveDateLabel: "તારીખ યાદ રાખજો",
      saveDate: "શુભ તિથિ",
      photosLabel: "યાદો",
      familyLabel: "પરિવાર સાથે",
      replyLabel: "આપનો જવાબ",
      closing: "આપની હાજરી જ અમારા માટે સૌથી મોટી ભેટ છે. આપની સાથે ઉજવણી કરવાની રાહ જોઈએ છીએ.",
    },
  },
  rsvpCopy: {
    heading: "આપ જરૂર પધારશો ને?",
    intro: "દરેક પ્રસંગ માટે જવાબ આપો. આપ આ પાના પરથી ગમે ત્યારે જવાબ બદલી શકો છો.",
    yourName: "આપનું નામ",
    namePlaceholder: "પરિવાર આપને જે નામથી ઓળખે છે",
    nameRequired: "કૃપા કરી આપનું નામ લખો",
    acceptAll: "બધા પ્રસંગોમાં આવીએ છીએ",
    statuses: {
      attending: { label: "આનંદ સાથે આવીશું", short: "આવીએ છીએ" },
      maybe: { label: "હજુ નક્કી નથી", short: "કદાચ" },
      declined: { label: "દિલગીર છીએ, નહીં આવી શકીએ", short: "નહીં આવી શકીએ" },
    },
    statusGroup: (name) => `${name} માટે આપનો જવાબ`,
    chooseOne: "એક જવાબ પસંદ કરો",
    adults: "મોટા",
    children: "બાળકો",
    fewer: (what) => `${what} ઓછા કરો`,
    more: (what) => `${what} વધારો`,
    questionsHeading: "પરિવાર માટે થોડી વિગતો",
    optional: "વૈકલ્પિક",
    yes: "હા",
    no: "ના",
    choose: "પસંદ કરો",
    meal: { veg: "શાકાહારી", jain: "જૈન", "non-veg": "માંસાહારી", vegan: "વીગન" },
    message: "પરિવાર માટે સંદેશ",
    messagePlaceholder: "આશીર્વાદ, શુભેચ્છા, અથવા તેમને જાણવા જેવું કંઈ પણ",
    send: "જવાબ મોકલો",
    update: "જવાબ બદલો",
    sending: "મોકલી રહ્યા છીએ…",
    failed: "આપનો જવાબ મોકલી શકાયો નહીં. ઇન્ટરનેટ તપાસો અને ફરી પ્રયત્ન કરો.",
    missing: "આ આમંત્રણ હવે જવાબ સ્વીકારતું નથી.",
    notInvited: "આ લિંક તેમાંના કોઈ પ્રસંગ માટે નથી. પરિવારને તપાસવા કહો.",
    fixErrors: (count) => (count === 1 ? "એક જવાબ હજુ બાકી છે." : `${count} જવાબ હજુ બાકી છે.`),
    previewOnly:
      "આ તમારું પ્રીવ્યૂ છે, તેથી કંઈ મોકલાયું નથી. પ્રકાશિત કર્યા પછી મહેમાનો જવાબ આપી શકશે.",
    full: "આ આમંત્રણ પર હમણાં વધુ જવાબ ઉમેરી શકાતા નથી. તમારો જવાબ સીધો પરિવારને મોકલો.",
    thanksTitle: (name) => `આભાર, ${name}!`,
    thanksBody: "આપનો જવાબ પરિવાર સુધી પહોંચી ગયો. આપ અહીં ગમે ત્યારે બદલી શકો છો.",
    change: "મારો જવાબ બદલો",
    people: (count) => (count === 1 ? "1 વ્યક્તિ" : `${count} વ્યક્તિ`),
  },
  wallCopy: {
    heading: "ફોટો દીવાલ",
    intro: "ઉજવણીના આપના ફોટા ઉમેરો. આ આમંત્રણ ધરાવતા સૌ તે જોઈ શકે છે.",
    soon: (date) => `ફોટો દીવાલ ${date} ના રોજ ખૂલશે. તે દિવસે આવીને આપના ફોટા શેર કરજો.`,
    closed: "ફોટો દીવાલ બંધ થઈ ગઈ છે. ફોટા શેર કરવા બદલ આભાર.",
    name: "આપનું નામ",
    nameHint: "આપના ફોટા નીચે દેખાશે.",
    optional: "વૈકલ્પિક",
    add: "ફોટા ઉમેરો",
    adding: (done, of) => `${of} માંથી ${done} ફોટો ઉમેરી રહ્યા છીએ…`,
    added: (count) => `${photos(count)} ઉમેર્યા. આભાર!`,
    failed: "કેટલાક ફોટા ઉમેરી શકાયા નહીં. ઇન્ટરનેટ તપાસો અને ફરી પ્રયત્ન કરો.",
    unreadable: "આ ફોન તેમાંનો એક ફોટો વાંચી શક્યો નહીં. JPEG કે PNG અજમાવી જુઓ.",
    full: "ફોટો દીવાલ ભરાઈ ગઈ છે.",
    share: "એક ફોનથી ઉમેરી શકાય તેટલા ફોટા આપે ઉમેરી દીધા છે.",
    tooMany: (max) => `એક વખતે વધુમાં વધુ ${max} ફોટા પસંદ કરો.`,
    empty: "હજુ એક પણ ફોટો નથી. પહેલો ફોટો આપ જ શેર કરો.",
    loading: "ફોટા આવી રહ્યા છે…",
    loadFailed: "ફોટા લાવી શકાયા નહીં.",
    retry: "ફરી પ્રયત્ન કરો",
    by: (name) => `${name} એ શેર કર્યો`,
    byGuest: "એક મહેમાને શેર કર્યો",
    photoAlt: (name, index) =>
      name ? `${name} એ શેર કરેલો ફોટો ${index}` : `એક મહેમાને શેર કરેલો ફોટો ${index}`,
    view: (index) => `ફોટો ${index} જુઓ`,
    remove: "કાઢો",
    removeLabel: (index) => `આપનો ફોટો ${index} કાઢો`,
    removed: "આપનો ફોટો કાઢી નાખ્યો.",
    removeFailed: "ફોટો કાઢી શકાયો નહીં. ફરી પ્રયત્ન કરો.",
    more: "વધુ ફોટા બતાવો",
    count: photos,
    close: "બંધ કરો",
    previous: "પાછલો ફોટો",
    next: "આગલો ફોટો",
    viewerTitle: (index, of) => `${of} માંથી ફોટો ${index}`,
  },
  questionLabels: {
    meal: "ભોજનની પસંદ",
    arrival: "પહોંચવાની તારીખ",
    stay: "રૂમ જોઈએ છે",
    pickup: "સ્ટેશન કે એરપોર્ટથી લેવા આવવું",
    song: "ગીતની ફરમાઈશ",
    message: "જોડી માટે સંદેશ",
  },
  invitation: {
    open: "આમંત્રણ ખોલો",
    close: "આમંત્રણ બંધ કરો",
    playMusic: "સંગીત વગાડો",
    pauseMusic: "સંગીત રોકો",
    preparing: "3D તૈયાર થઈ રહ્યું છે",
    skip: "ઍનિમેશન છોડો",
    and: "અને",
    story: {
      story: "આમંત્રણ, એક પછી એક પાનું",
      pause: "પાનાં રોકો",
      play: "આગળ ચલાવો",
      next: "આગલું પાનું",
      previous: "પાછલું પાનું",
      skip: "સીધા કાર્ડ પર જાઓ",
      done: "કાર્ડ જુઓ",
      replay: "આમંત્રણનાં પાનાં ચલાવો",
      directions: "રસ્તો જુઓ",
      calendar: "કૅલેન્ડરમાં ઉમેરો",
      textBox: "શબ્દો પાછળ ચોકઠું",
    },
  },
  theme: { group: "રંગ થીમ", system: "ડિવાઇસ પ્રમાણે", light: "આછી", dark: "ઘેરી" },
};
