import type { GuestText } from "@/i18n/copy/guest";
import { site } from "@/lib/site";

/*
 * বাংলা: অতিথির পাতা, উত্তর আর ছবির দেওয়াল। English: src/content/publish.ts and
 * src/content/photo-wall.ts. Drafts for a native proofreader.
 */

const photos = (count: number) =>
  count === 1 ? "1টি ছবি" : `${count.toLocaleString("en-IN")}টি ছবি`;

export const guestText: GuestText = {
  guestCopy: {
    metaTitle: (names, occasion) => `${names} · ${occasion} নিমন্ত্রণ`,
    metaDescription: (when, where) =>
      [when, where].filter(Boolean).join(" · ") ||
      "আপনি আমন্ত্রিত। বিস্তারিত দেখতে নিমন্ত্রণপত্রটি খুলুন।",
    invited: "আপনি আমন্ত্রিত",
    openHint: "খুলতে কার্ডে ট্যাপ করুন",
    doorway: {
      open: "নিমন্ত্রণপত্র খুলুন",
      again: "আবার খুলুন",
      counting: "উৎসবের দিন গোনা",
      details: "বিস্তারিত দেখুন",
      skip: "এগিয়ে চলুন",
    },
    countdown: {
      days: (n) => `আর ${n} দিন`,
      tomorrow: "আগামীকাল",
      today: "আজ",
    },
    reply: "নিমন্ত্রণের উত্তর দিন",
    functions: "অনুষ্ঠানসমূহ",
    family: "পরিবারের পক্ষ থেকে সাদরে",
    cardLanguage: "কার্ডের ভাষা",
    timeRange: (start, end) => `${start} থেকে ${end}`,
    when: "কবে",
    where: "কোথায়",
    dressCode: "পোশাক",
    directions: "পথ",
    parking: "পার্কিং",
    showMap: "মানচিত্র",
    hideMap: "মানচিত্র লুকান",
    mapTitle: (place) => `${place}-এর মানচিত্র`,
    eventDay: {
      now: "এখন চলছে",
      later: "আজ পরে",
      at: (name, time) => (time ? `${name}, ${time}` : name),
      details: "বিস্তারিত",
      dismiss: "এই ফালিটি লুকান",
    },
    addToCalendar: "ক্যালেন্ডারে যোগ করুন",
    googleCalendar: "Google ক্যালেন্ডার",
    appleCalendar: "Apple, Outlook ও অন্যান্য",
    addAll: "সব ক্যালেন্ডারে যোগ করুন",
    photos: "ছবি",
    photoAlt: (index) => `পরিবারের ছবি ${index}`,
    madeWith: `${site.name} দিয়ে তৈরি`,
    createYours: "নিজের নিমন্ত্রণপত্র তৈরি করুন",
    notFoundTitle: "এই নিমন্ত্রণপত্রটি পাওয়া যাচ্ছে না",
    notFoundBody:
      "লিংকটি হয়তো ভুল লেখা হয়েছে, বা পরিবার এটি পাঠানো বন্ধ করেছে। তাঁদের আবার পাঠাতে বলুন।",
    home: `${site.name}-এ যান`,
    scene: {
      label: "একে একে সব অনুষ্ঠান",
      previous: "আগের অনুষ্ঠান",
      next: "পরের অনুষ্ঠান",
      pause: "অনুষ্ঠান থামান",
      play: "অনুষ্ঠান চালান",
      position: (n, total) => `${total}টির মধ্যে ${n}`,
      details: "সব বিস্তারিত",
      initials: "এখানে আপনার ছবি থাকবে",
    },
    themed: {
      invitedTo: "আনন্দের সঙ্গে আপনাকে উৎসবে আমন্ত্রণ জানাই",
      shower: "নবদম্পতির ওপর ফুল ছড়ান",
      showered: "আপনার ফুল নবদম্পতির কাছে পৌঁছে যাচ্ছে।",
      music: { play: "গান চালান", pause: "গান থামান" },
      lamps: {
        diyas: "প্রদীপ জ্বালান",
        lanterns: "লণ্ঠন জ্বালান",
        nilavilakku: "দীপ জ্বালান",
        fairy: "আলো জ্বালান",
      },
      lampsLabel: "নবদম্পতির জন্য একটি প্রদীপ জ্বালান",
      lit: "ধন্যবাদ। নবদম্পতির জন্য আপনার প্রদীপ জ্বলছে।",
      blessingLabel: "গুরুজনদের আশীর্বাদে",
      eventsLabel: "সকাল থেকে রাত",
      saveDateLabel: "তারিখটি মনে রাখবেন",
      saveDate: "শুভ দিন",
      photosLabel: "স্মৃতি",
      familyLabel: "পরিবারের সঙ্গে",
      replyLabel: "আপনার উত্তর",
      closing: "আপনার উপস্থিতিই আমাদের সবচেয়ে বড় উপহার। আপনার সঙ্গে উৎসব পালনের অপেক্ষায় রইলাম।",
    },
  },
  rsvpCopy: {
    heading: "আপনি আসবেন তো?",
    intro: "প্রতিটি অনুষ্ঠানের জন্য উত্তর দিন। এই পাতা থেকে যেকোনো সময় উত্তর বদলাতে পারবেন।",
    yourName: "আপনার নাম",
    namePlaceholder: "পরিবার যে নামে আপনাকে চেনে",
    nameRequired: "অনুগ্রহ করে আপনার নাম লিখুন",
    acceptAll: "সব অনুষ্ঠানে আসছি",
    statuses: {
      attending: { label: "সানন্দে আসছি", short: "আসছি" },
      maybe: { label: "এখনও নিশ্চিত নই", short: "হয়তো" },
      declined: { label: "দুঃখিত, আসতে পারব না", short: "আসতে পারব না" },
    },
    statusGroup: (name) => `${name}-এর জন্য আপনার উত্তর`,
    chooseOne: "একটি উত্তর বেছে নিন",
    adults: "প্রাপ্তবয়স্ক",
    children: "শিশু",
    fewer: (what) => `${what} কমান`,
    more: (what) => `${what} বাড়ান`,
    questionsHeading: "পরিবারের জন্য কিছু তথ্য",
    optional: "ঐচ্ছিক",
    yes: "হ্যাঁ",
    no: "না",
    choose: "বেছে নিন",
    meal: { veg: "নিরামিষ", jain: "জৈন", "non-veg": "আমিষ", vegan: "ভেগান" },
    message: "পরিবারের জন্য বার্তা",
    messagePlaceholder: "আশীর্বাদ, শুভেচ্ছা, বা তাঁদের জানা দরকার এমন কিছু",
    send: "উত্তর পাঠান",
    update: "উত্তর বদলান",
    sending: "পাঠানো হচ্ছে…",
    failed: "আপনার উত্তর পাঠানো গেল না। ইন্টারনেট দেখে আবার চেষ্টা করুন।",
    missing: "এই নিমন্ত্রণপত্র আর উত্তর নিচ্ছে না।",
    notInvited: "এই লিংকটি ওই অনুষ্ঠানগুলোর কোনোটির জন্য নয়। পরিবারকে দেখে নিতে বলুন।",
    fixErrors: (count) => (count === 1 ? "একটি উত্তর এখনও বাকি।" : `${count}টি উত্তর এখনও বাকি।`),
    previewOnly:
      "এটি আপনার প্রিভিউ, তাই কিছু পাঠানো হয়নি। প্রকাশ করার পরে অতিথিরা উত্তর দিতে পারবেন।",
    full: "এই নিমন্ত্রণে এখন আর উত্তর যোগ করা যাচ্ছে না। আপনার উত্তর সরাসরি পরিবারকে পাঠান।",
    thanksTitle: (name) => `ধন্যবাদ, ${name}!`,
    thanksBody: "আপনার উত্তর পরিবারের কাছে পৌঁছেছে। এখানে যেকোনো সময় বদলাতে পারবেন।",
    change: "আমার উত্তর বদলান",
    people: (count) => (count === 1 ? "1 জন" : `${count} জন`),
  },
  wallCopy: {
    heading: "ছবির দেওয়াল",
    intro: "উৎসবের আপনার ছবি যোগ করুন। এই নিমন্ত্রণ যাঁদের কাছে আছে, সবাই দেখতে পাবেন।",
    soon: (date) => `ছবির দেওয়াল খুলবে ${date}। সেদিন এসে আপনার ছবি শেয়ার করুন।`,
    closed: "ছবির দেওয়াল বন্ধ হয়ে গেছে। ছবি শেয়ার করার জন্য ধন্যবাদ।",
    name: "আপনার নাম",
    nameHint: "আপনার ছবির নিচে দেখা যাবে।",
    optional: "ঐচ্ছিক",
    add: "ছবি যোগ করুন",
    adding: (done, of) => `${of}টির মধ্যে ${done} নম্বর ছবি যোগ হচ্ছে…`,
    added: (count) => `${photos(count)} যোগ হয়েছে। ধন্যবাদ!`,
    failed: "কিছু ছবি যোগ করা গেল না। ইন্টারনেট দেখে আবার চেষ্টা করুন।",
    unreadable: "এই ফোন ওর একটি ছবি পড়তে পারেনি। JPEG বা PNG দিয়ে চেষ্টা করুন।",
    full: "ছবির দেওয়াল ভরে গেছে।",
    share: "একটি ফোন থেকে যত ছবি যোগ করা যায়, আপনি সব যোগ করে ফেলেছেন।",
    tooMany: (max) => `একবারে সর্বাধিক ${max}টি ছবি বেছে নিন।`,
    empty: "এখনও কোনো ছবি নেই। প্রথম ছবিটি আপনিই শেয়ার করুন।",
    loading: "ছবি আসছে…",
    loadFailed: "ছবিগুলো আনা গেল না।",
    retry: "আবার চেষ্টা করুন",
    by: (name) => `${name} শেয়ার করেছেন`,
    byGuest: "একজন অতিথি শেয়ার করেছেন",
    photoAlt: (name, index) =>
      name ? `${name}-এর শেয়ার করা ছবি ${index}` : `একজন অতিথির শেয়ার করা ছবি ${index}`,
    view: (index) => `ছবি ${index} দেখুন`,
    remove: "সরান",
    removeLabel: (index) => `আপনার ছবি ${index} সরান`,
    removed: "আপনার ছবি সরানো হয়েছে।",
    removeFailed: "ছবিটি সরানো গেল না। আবার চেষ্টা করুন।",
    more: "আরও ছবি দেখান",
    count: photos,
    close: "বন্ধ করুন",
    previous: "আগের ছবি",
    next: "পরের ছবি",
    viewerTitle: (index, of) => `${of}টির মধ্যে ছবি ${index}`,
  },
  questionLabels: {
    meal: "খাবারের পছন্দ",
    arrival: "পৌঁছনোর তারিখ",
    stay: "থাকার ঘর লাগবে",
    pickup: "স্টেশন বা বিমানবন্দর থেকে আনা",
    song: "গানের অনুরোধ",
    message: "নবদম্পতির জন্য বার্তা",
  },
  invitation: {
    open: "নিমন্ত্রণপত্র খুলুন",
    close: "নিমন্ত্রণপত্র বন্ধ করুন",
    playMusic: "গান চালান",
    pauseMusic: "গান থামান",
    preparing: "3D তৈরি হচ্ছে",
    skip: "অ্যানিমেশন বাদ দিন",
    and: "ও",
    story: {
      story: "নিমন্ত্রণপত্র, পাতায় পাতায়",
      pause: "পাতা থামান",
      play: "আবার চালান",
      next: "পরের পাতা",
      previous: "আগের পাতা",
      skip: "সরাসরি কার্ডে যান",
      done: "কার্ড দেখুন",
      replay: "নিমন্ত্রণের পাতাগুলো চালান",
      directions: "পথ দেখুন",
      calendar: "ক্যালেন্ডারে যোগ করুন",
      textBox: "লেখার পেছনে বাক্স",
    },
  },
  theme: { group: "রঙের থিম", system: "ডিভাইসের মতো", light: "হালকা", dark: "গাঢ়" },
};
