import type { EditorStep, FunctionId } from "@/lib/editor/draft";
import { TEMPLATES } from "@/lib/templates/catalog";
import { TEMPLATE_IDS, type TemplateId } from "@/lib/templates/ids";

/*
 * English copy for the invite editor (/create). Moves into next-intl in Step 12.
 * Slot names come from slotLabels in templates-review.ts.
 */

export const editor = {
  metaTitle: "Create your invitation",
  metaDescription:
    "Choose a 3D design, add your names and functions, then preview your invitation.",
  headerLabel: "Invite editor",
  progressLabel: "Invite progress",
  progress: (step: number, total: number) => `Step ${step} of ${total}`,
  done: "done",
  designChosen: "Your design",
  changeDesign: "Change design",
  back: "Back",
  next: "Continue",
  toPreview: "Preview invitation",
  preview: "Invitation preview",
  showPreview: "Preview",
  previewTitle: "Your invitation",
  livePreview: "Live preview, open it large",
  hideLivePreview: "Hide the live preview",
  showLivePreview: "Show the live preview",
  close: "Close",
  optional: "Optional",
  characters: (used: number, max: number) => `${used} of ${max} characters used`,
  fixErrors: (count: number) =>
    count === 1 ? "One thing needs your attention" : `${count} things need your attention`,
  errors: {
    required: "Please fill this in",
    "too-long": "This is too long for the card",
    "no-functions": "Choose at least one function",
  },
  save: {
    idle: "Drafts save on this device",
    saving: "Saving…",
    saved: "Draft saved",
    unavailable: "Can't save on this device",
  },
} as const;

/** The header's save status once signed in, and moving between invites. */
export const syncCopy = {
  idle: "Saves to your account",
  syncing: "Saving…",
  synced: "Saved to your account",
  offline: "Saved on this device, retrying",
  missing: "That invite isn't in your account. It may have been deleted.",
  switchFailed: "Couldn't save the invite that's open, so it stays open. Try again in a moment.",
} as const;

export const stepCopy: Record<
  EditorStep,
  { label: string; eyebrow: string; title: string; intro: string }
> = {
  occasion: {
    label: "Occasion",
    eyebrow: "Choose an occasion",
    title: "What are you celebrating?",
    intro:
      "The occasion sets up your invite: the functions it plans, its wording and the designs that suit it. Switch later and nothing you've typed is lost.",
  },
  tradition: {
    label: "Tradition",
    eyebrow: "Choose a tradition",
    title: "Whose tradition should the card follow?",
    intro:
      "A tradition sets the sacred symbol, the invocation, local ceremony names and the family wording. Everything stays editable, and you can skip this step.",
  },
  design: {
    label: "Design",
    eyebrow: "Choose a design",
    title: "Pick the card your guests will open",
    intro:
      "Every design opens in 3D with its own ornaments, petals and raga. You can switch at any time without losing your words.",
  },
  couple: {
    label: "Couple",
    eyebrow: "The couple",
    title: "Who is the couple?",
    intro:
      "Names appear large on the card. The other lines start with wording for your occasion; change them to sound like your family.",
  },
  functions: {
    label: "Functions",
    eyebrow: "Functions",
    title: "When and where is everything?",
    intro:
      "Choose the functions you're inviting guests to. The card shows the main function's date and venue; guests see every function when they open it.",
  },
  extras: {
    label: "Photos & music",
    eyebrow: "Photos and music",
    title: "Make it yours",
    intro:
      "Add a few photos for your guests, choose the raga that plays as the card opens, and pick what the RSVP asks.",
  },
  preview: {
    label: "Preview",
    eyebrow: "Preview",
    title: "Here's what your guests will see",
    intro: "Open the card, play the music and read it through once more.",
  },
};

export const functionCopy: Record<
  FunctionId,
  { name: string; description: string; dressIdeas: string[] }
> = {
  roka: {
    name: "Roka",
    description: "The families bless the match and exchange gifts",
    dressIdeas: ["Festive ethnic", "Reds and golds", "Pastel suits and sarees"],
  },
  engagement: {
    name: "Engagement",
    description: "The ring ceremony, sagai or nischayathartham",
    dressIdeas: ["Indo-western", "Pastels and ivory", "Festive ethnic"],
  },
  tilak: {
    name: "Tilak",
    description: "The bride's family blesses the groom with a tilak and gifts",
    dressIdeas: ["Festive ethnic", "Kurta and bandhgala", "Reds and golds"],
  },
  "ganesh-puja": {
    name: "Ganesh puja",
    description: "Ganesh sthapana or pujan, so the celebrations begin without obstacles",
    dressIdeas: ["Traditional Indian", "Yellows and reds", "Simple and elegant"],
  },
  "grah-shanti": {
    name: "Griha shanti",
    description: "A havan at home to bless the family before the wedding",
    dressIdeas: ["Traditional Indian", "Cotton and silk", "Soft pastels"],
  },
  mandap: {
    name: "Mandap muhurat",
    description: "The mandap is raised and blessed; panthakal in the south",
    dressIdeas: ["Traditional Indian", "Bright and colourful", "Comfortable ethnic"],
  },
  mameru: {
    name: "Mameru",
    description: "The maternal uncle's family brings gifts; mayra or bhaat in the north",
    dressIdeas: ["Bandhani and leheriya", "Festive ethnic", "Reds and pinks"],
  },
  haldi: {
    name: "Haldi",
    description: "Turmeric blessings, usually the morning before",
    dressIdeas: ["Shades of yellow", "Whites and pastels", "Clothes you don't mind staining"],
  },
  mehendi: {
    name: "Mehendi",
    description: "Henna, music and an easy afternoon",
    dressIdeas: ["Greens and florals", "Bright and colourful", "Comfortable ethnic"],
  },
  sangeet: {
    name: "Sangeet",
    description: "An evening of songs, dance and performances",
    dressIdeas: ["Indo-western", "Sequins and sparkle", "Jewel tones"],
  },
  garba: {
    name: "Garba night",
    description: "Raas, garba and dandiya till late",
    dressIdeas: ["Chaniya choli and kediyu", "Mirror work", "Bright and colourful"],
  },
  bhoj: {
    name: "Family feast",
    description: "A meal for family and friends: kelvan, aiburobhat or bhojan samarambh",
    dressIdeas: ["Festive ethnic", "Comfortable ethnic", "Smart casual"],
  },
  baraat: {
    name: "Baraat",
    description: "The groom's procession sets out with music and dancing",
    dressIdeas: ["Safas and turbans", "Sherwani and kurta", "Festive ethnic"],
  },
  "baraat-welcome": {
    name: "Baraat welcome",
    description: "The bride's family welcomes the groom's party: milni or jaan aagman",
    dressIdeas: ["Traditional Indian", "Silk and zari", "Festive ethnic"],
  },
  wedding: {
    name: "Wedding",
    description: "The pheras, vows and ceremony",
    dressIdeas: ["Traditional Indian", "Pastels, no black or white", "Silk and zari"],
  },
  vidaai: {
    name: "Vidaai",
    description: "The bride's farewell as she leaves with blessings",
    dressIdeas: ["Traditional Indian", "Soft pastels", "Silk and zari"],
  },
  reception: {
    name: "Reception",
    description: "Dinner and celebration with everyone",
    dressIdeas: ["Formal", "Black tie", "Festive evening wear"],
  },
  birthday: {
    name: "Birthday party",
    description: "Cake, games and blessings for the birthday",
    dressIdeas: ["Pastels", "Smart casual", "Come as you are"],
  },
  anniversary: {
    name: "Anniversary dinner",
    description: "An evening to celebrate the years together",
    dressIdeas: ["Formal", "Festive ethnic", "Reds and golds"],
  },
  party: {
    name: "Party",
    description: "Music, food and friends",
    dressIdeas: ["Smart casual", "Cocktail", "Something that sparkles"],
  },
  "baby-shower": {
    name: "Baby shower",
    description: "Blessings, songs and gifts for the mother-to-be",
    dressIdeas: ["Pastels", "Festive ethnic", "Greens and yellows"],
  },
  diwali: {
    name: "Diwali party",
    description: "Lakshmi puja, diyas, sweets and dinner",
    dressIdeas: ["Festive ethnic", "Reds and golds", "Something that sparkles"],
  },
  housewarming: {
    name: "Griha pravesh",
    description: "Puja, havan and a meal in the new home",
    dressIdeas: ["Festive ethnic", "Pastels", "Comfortable traditional"],
  },
  puja: {
    name: "Puja",
    description: "Katha, aarti and prasad",
    dressIdeas: ["Festive ethnic", "Whites and yellows", "Traditional"],
  },
  "thread-ceremony": {
    name: "Thread ceremony",
    description: "Upanayan, havan and a family meal",
    dressIdeas: ["Traditional", "Whites and golds", "Festive ethnic"],
  },
  annaprashan: {
    name: "First rice ceremony",
    description: "The baby's first taste of rice, with blessings",
    dressIdeas: ["Pastels", "Festive ethnic", "Yellows and whites"],
  },
  christening: {
    name: "Christening",
    description: "Church service and lunch with family",
    dressIdeas: ["Whites and pastels", "Sunday best", "Smart casual"],
  },
  "prayer-meet": {
    name: "Prayer meeting",
    description: "Prayers, bhajans and a moment of remembrance",
    dressIdeas: ["Whites", "Light colours", "Simple and quiet"],
  },
  retirement: {
    name: "Retirement party",
    description: "Dinner and toasts for a career well lived",
    dressIdeas: ["Smart casual", "Formal", "Festive ethnic"],
  },
  "farewell-party": {
    name: "Farewell party",
    description: "Music, memories and a warm goodbye",
    dressIdeas: ["Formal", "Smart casual", "Something that sparkles"],
  },
  "shop-opening": {
    name: "Opening",
    description: "Ribbon cutting, puja and refreshments",
    dressIdeas: ["Festive ethnic", "Smart casual", "Formal"],
  },
  launch: {
    name: "Launch",
    description: "A first look, a few words and dinner",
    dressIdeas: ["Business formal", "Smart casual", "Black tie"],
  },
  "ganesh-chaturthi": {
    name: "Ganpati darshan",
    description: "Aarti, darshan and prasad",
    dressIdeas: ["Festive ethnic", "Yellows and reds", "Traditional"],
  },
  navratri: {
    name: "Navratri night",
    description: "Garba, aarti and bhog",
    dressIdeas: ["Chaniya choli", "Festive ethnic", "Bright colours"],
  },
  janmashtami: {
    name: "Janmashtami",
    description: "Bhajans, jhanki and midnight aarti",
    dressIdeas: ["Festive ethnic", "Yellows and blues", "Little Krishna outfits"],
  },
  onam: {
    name: "Onam sadhya",
    description: "Pookalam, sadhya and songs",
    dressIdeas: ["Kasavu", "Whites and golds", "Festive ethnic"],
  },
  sankranti: {
    name: "Sankranti",
    description: "Kites, til laddoos and pongal",
    dressIdeas: ["Bright colours", "Festive ethnic", "Comfortable for the terrace"],
  },
  lohri: {
    name: "Lohri bonfire",
    description: "Bonfire, rewari, bhangra and dinner",
    dressIdeas: ["Phulkari", "Bright colours", "Something warm"],
  },
  eid: {
    name: "Iftar dawat",
    description: "Breaking the fast, dinner and Eid wishes",
    dressIdeas: ["Festive ethnic", "Whites and greens", "Something elegant"],
  },
};

export const functionFields = {
  group: "Functions",
  date: "Date",
  datePlaceholder: "Pick a date",
  time: "Starts at",
  timePlaceholder: "Pick a time",
  venue: "Venue",
  venuePlaceholder: "e.g. Pichola Lakeside Gardens, Udaipur",
  city: "City or venue",
  cityPlaceholder: "e.g. Udaipur",
  cityHint:
    "A save-the-date needs only the date and the city. Times and venues follow in the invite.",
  suggested: (occasion: string) => `${occasion} functions`,
  more: "More functions",
  moreHint: "Add any other function you're inviting guests to.",
  showMore: (count: number) => `Show ${count} more functions`,
  address: "Address",
  addressHint: "Guests see it under the venue's name.",
  pin: "Google Maps pin",
  pinHint:
    "In Google Maps, open the venue, tap Share and paste the link here. Guests get a map and one-tap directions to the exact spot.",
  pinInvalid: "That isn't a Google Maps link. Copy it from Share in Google Maps.",
  parking: "Parking",
  parkingPlaceholder: "Valet at the main gate, free parking behind the hall",
  dressCode: "Dress code",
  dressIdeas: "Dress code ideas",
  onCard: "On the card",
  endTime: "Ends at",
  endHint: "Leave it empty if the evening runs open.",
  muhuratHint:
    "choose the exact start and end, to the minute. Guests see them just as you set them.",
} as const;

export const coupleCopy = {
  namesHeading: "Names",
  wordingHeading: "Wording",
  example: (sample: string) => `e.g. ${sample}`,
  joinerHint: "The word between the names, like &, weds or संग.",
  doorsHint: "Two short words painted on the gates.",
  anyScript: "Type in any script. Hindi, Tamil, Bengali and more all fit the card.",
  latinOnCard: (language: string) =>
    `Your card is in ${language}, so guests will see this name in English letters. Pick a ${language} spelling below, or type it with a ${language} keyboard.`,
  spellings: (language: string) => `In ${language} letters`,
  useSpelling: (name: string) => `Use ${name}`,
  languagesHeading: "Card language",
  languagesHint: "With two languages, guests switch between them on the invitation.",
  bothLanguages: (main: string, second: string) => `${main} and ${second}`,
  secondHeading: (language: string) => `The card in ${language}`,
  secondHint: (main: string) => `Leave a line empty to repeat the ${main} card's words.`,
} as const;

/**
 * The names step for occasions beyond weddings (Step 12p): its own title, and for a card
 * led by one name (a birthday, a party), what that name is.
 */
export const namesCopy = {
  steps: {
    birthday: { label: "Birthday", eyebrow: "The birthday", title: "Whose birthday is it?" },
    anniversary: { label: "Couple", eyebrow: "The couple", title: "Who is celebrating?" },
    party: { label: "Party", eyebrow: "The party", title: "What's the party called?" },
    "baby-shower": {
      label: "Mother-to-be",
      eyebrow: "The baby shower",
      title: "Who is the mother-to-be?",
    },
    diwali: { label: "Diwali", eyebrow: "Diwali", title: "What's your Diwali party called?" },
    housewarming: { label: "Home", eyebrow: "The new home", title: "What's the new home called?" },
    puja: { label: "Puja", eyebrow: "The puja", title: "Which puja are you holding?" },
    "thread-ceremony": {
      label: "Boy",
      eyebrow: "The thread ceremony",
      title: "Whose thread ceremony is it?",
    },
    annaprashan: { label: "Baby", eyebrow: "The annaprashan", title: "What's the baby's name?" },
    christening: { label: "Baby", eyebrow: "The christening", title: "What's the baby's name?" },
    "prayer-meet": {
      label: "In memory",
      eyebrow: "The prayer meeting",
      title: "Who are you remembering?",
    },
    retirement: { label: "Retiree", eyebrow: "The retirement", title: "Who is retiring?" },
    "farewell-party": {
      label: "Farewell",
      eyebrow: "The farewell",
      title: "Who are you saying goodbye to?",
    },
    "shop-opening": {
      label: "Business",
      eyebrow: "The opening",
      title: "What's the business called?",
    },
    launch: { label: "Event", eyebrow: "The launch", title: "What are you launching?" },
    "ganesh-chaturthi": {
      label: "Ganpati",
      eyebrow: "Ganesh Chaturthi",
      title: "What do you call your Ganpati celebration?",
    },
    navratri: {
      label: "Celebration",
      eyebrow: "Navratri",
      title: "What's your Navratri celebration called?",
    },
    janmashtami: {
      label: "Celebration",
      eyebrow: "Janmashtami",
      title: "What's your Janmashtami celebration called?",
    },
    onam: { label: "Celebration", eyebrow: "Onam", title: "What's your Onam gathering called?" },
    sankranti: {
      label: "Celebration",
      eyebrow: "Sankranti",
      title: "What's your Sankranti gathering called?",
    },
    lohri: { label: "Celebration", eyebrow: "Lohri", title: "What's your Lohri night called?" },
    eid: { label: "Dawat", eyebrow: "Eid and iftar", title: "What's your dawat called?" },
  },
  one: {
    birthday: { label: "Birthday name", example: "Aarav" },
    party: { label: "Party name", example: "Diwali Night" },
    "baby-shower": { label: "Her name", example: "Priya" },
    diwali: { label: "Party name", example: "Sharma Family Diwali" },
    housewarming: { label: "Home or family name", example: "Sharma Niwas" },
    puja: { label: "Puja name", example: "Satyanarayan Katha" },
    "thread-ceremony": { label: "His name", example: "Aarav" },
    annaprashan: { label: "Baby's name", example: "Anaya" },
    christening: { label: "Baby's name", example: "Aaron" },
    "prayer-meet": { label: "Their name", example: "Shri R. K. Sharma" },
    retirement: { label: "Their name", example: "R. K. Sharma" },
    "farewell-party": { label: "Name or batch", example: "Batch of 2026" },
    "shop-opening": { label: "Business name", example: "Sharma Jewellers" },
    launch: { label: "Event name", example: "The Aurora Launch" },
    "ganesh-chaturthi": { label: "Celebration name", example: "Sharma Family Ganpati" },
    navratri: { label: "Celebration name", example: "Navratri Utsav" },
    janmashtami: { label: "Celebration name", example: "Krishna Janmotsav" },
    onam: { label: "Celebration name", example: "Onam Sadhya" },
    sankranti: { label: "Celebration name", example: "Kite Day" },
    lohri: { label: "Celebration name", example: "Lohri Night" },
    eid: { label: "Dawat name", example: "Iftar Dawat" },
  },
  oneHint: "It's printed large on the cover. Say who invites and why in the wording below.",
} as const;

export const extrasCopy = {
  photosHeading: "Photos",
  photosHint: (max: number) =>
    `Up to ${max} photos. They're shrunk on your phone before saving, so they load fast for guests.`,
  addPhotos: "Add photos",
  dropHere: "or drop them here",
  photo: (index: number) => `Photo ${index}`,
  removePhoto: (index: number) => `Remove photo ${index}`,
  moveEarlier: (index: number) => `Move photo ${index} earlier`,
  full: (max: number) => `That's all ${max}. Remove one to add another.`,
  processing: "Preparing photos…",
  photoFailed: "That photo couldn't be read. Try a JPEG or PNG.",
  storageFailed: "Photos can't be saved in this browser, for example in private mode.",
  emptyPhotos: "No photos yet",
  emptyPhotosBody: "Couple portraits and pre-wedding shots work best.",
  coupleHeading: "Photo page",
  coupleHint:
    "Your photo inside the theme's own frame, on the page after your names. Every theme has its own frame shape.",
  coupleLayouts: {
    none: "No photo page",
    one: "One photo of you both",
    two: "Two photos, one each",
  },
  /** A birthday or party has one guest of honour. */
  photoHintOne: "A photo inside the theme's own frame, on the page after the name.",
  photoLayoutsOne: {
    none: "No photo page",
    one: "One photo",
  },
  coupleAddFirst: "Add a photo above and it fills the frame.",
  coupleFrame: (index: number, frames: number) =>
    frames === 1 ? "Photo in the frame" : index === 1 ? "First frame" : "Second frame",
  useThisPhoto: (index: number) => `Photo ${index}`,
  fitHeading: "Fit your photos",
  fitHint: "Move, zoom and straighten each photo so it sits well in its frame.",
  adjust: "Adjust",
  adjustLabel: (frame: string) => `Adjust the photo: ${frame}`,
  adjusted: "Adjusted",
  adjustTitle: "Adjust photo",
  adjustDescription: "Drag the photo to move it. Pinch, scroll or use the slider to zoom.",
  adjustStage: "The photo in its frame. Use the arrow keys to move it, and plus or minus to zoom.",
  zoom: "Zoom",
  straighten: "Straighten",
  turn: "Turn",
  turnLabel: "Turn the photo a quarter to the right",
  resetPhoto: "Reset",
  savePhoto: "Save",
  cancelPhoto: "Cancel",
  closePhoto: "Close",
  musicHeading: "Music",
  musicHint: "A raga composed live as the card opens, or a short clip of your own music.",
  musicSource: { raga: "A raga", own: "Your own music" },
  ragaHint: "Composed live, so it costs your guests no data.",
  ownHint:
    "Pick a song or a recording from your phone and keep the part you love, up to 30 seconds. Guests hear it when the card opens, and it plays in your video too.",
  chooseSong: "Choose a song",
  songTypes: "MP3, M4A, WAV or AAC",
  readingSong: "Reading your song…",
  songFailed: "That file couldn't be read. Try an MP3 or M4A file.",
  clipFailed: "The clip couldn't be made in this browser. Try Chrome or Safari.",
  clipStorageFailed: "Music can't be saved in this browser, for example in private mode.",
  trimHeading: "Keep the part you love",
  waveformLabel: (name: string) => `The shape of ${name}, with the part you keep lit`,
  startAt: "Starts at",
  clipLength: "Length",
  seconds: (n: number) => `${n} seconds`,
  secondsShort: (n: number) => `${n}s`,
  playPart: "Play this part",
  stopPart: "Stop",
  rights: "I have the right to use this music",
  rightsHint:
    "Use your own recording, a song you've licensed, or royalty-free music. Clips downloaded from Instagram or YouTube usually aren't allowed, and we remove music when its owner asks.",
  useClip: "Use this music",
  makingClip: "Making your clip…",
  cancelTrim: "Cancel",
  changeClip: "Change",
  removeClip: "Remove",
  listenClip: "Listen",
  clipMeta: (n: number) => `Your music · ${n} seconds`,
  listen: (raga: string) => `Listen to ${raga}`,
  stopListening: "Stop listening",
  designsOwn: "Design's own",
  playOnOpen: "Play music when guests open the card",
  playOnOpenHint: "Guests can pause it at any time.",
  questionsHeading: "Questions for guests",
  questionsHint:
    "Every reply says who's coming to each function and can include a note. Tick anything else you'd like to know.",
  questionHints: {
    meal: "Vegetarian, Jain, non-vegetarian or vegan",
    arrival: "The day they reach the city",
    stay: "Whether they need a room",
    pickup: "Whether they need picking up from the station or airport",
    song: "A song they'd love to hear",
  },
  ragaNames: {
    yaman: "Raag Yaman",
    khamaj: "Raag Khamaj",
    bihag: "Raag Bihag",
    desh: "Raag Desh",
    bhupali: "Raag Bhupali",
    madhyamavati: "Raag Madhyamavati",
    mand: "Raag Mand",
    bhimpalasi: "Raag Bhimpalasi",
    pilu: "Raag Pilu",
    bhairavi: "Raag Bhairavi",
    hamsadhwani: "Raag Hamsadhwani",
    kafi: "Raag Kafi",
  },
  ragaMoods: {
    yaman: "Evening, romantic",
    khamaj: "Light and tender",
    bihag: "Late evening, a wedding raga",
    desh: "Monsoon, festive",
    bhupali: "Bright and joyful",
    madhyamavati: "Auspicious, Carnatic",
    mand: "Rajasthani folk, royal",
    bhimpalasi: "Warm afternoon, devotional",
    pilu: "Folk-bright and playful",
    bhairavi: "Tender, for farewells",
    hamsadhwani: "Auspicious, for Ganapati",
    kafi: "Festive folk, Holi colours",
  },
} as const;

export const traditionCopy = {
  group: "Traditions",
  none: "No tradition",
  noneHint: "The design's own wording, no symbol",
  nearYou: "Near you",
  draftNote:
    "These traditions are early drafts. People from each community are checking the wording, symbols and ceremony names before launch, so please tell us if something is not right.",
  names: {
    "north-hindu": "North Indian Hindu",
    rajasthani: "Rajasthani and Marwari",
    marathi: "Marathi",
    gujarati: "Gujarati",
    bengali: "Bengali Hindu",
    tamil: "Tamil Hindu",
    modern: "Modern",
  },
  hints: {
    "north-hindu": "Shri Ganeshaya Namah, Darshanabhilashi and Swagatotsuk",
    rajasthani: "Shri Ganeshaya Namah, Pithi and Mahila Sangeet",
    marathi: "Shri Ganeshaya Namah, Sakharpuda and Halad",
    gujarati: "Kankotri wording, Gol Dhana, Pithi and a tahuko for the children",
    bengali: "Prajapataye Namah, Gaye Holud and Bou Bhaat",
    tamil: "The Pillaiyar suzhi, Nichayathartham and Varaverpu",
    modern: "No religious symbols, for any couple or an interfaith wedding",
  },
  elements: "Religious elements",
  symbol: "Symbol at the top of the card",
  symbolNames: {
    om: "Om",
    kalash: "Mangal kalash",
    swastik: "Swastik",
    diya: "Diya",
    prajapati: "Prajapati",
    suzhi: "Pillaiyar suzhi",
  },
  noSymbol: "No symbol",
  symbolNote: "Deity artwork is being drawn by Indian artists and arrives later.",
  invocation: "Invocation",
  invocationModes: { script: "In its script", latin: "In English letters", off: "Leave it off" },
  meanings: {
    "Shri Ganeshaya Namah": "Salutations to Lord Ganesha",
    "Prajapataye Namah": "Salutations to Prajapati, lord of marriage",
    "Sri Vinayagar Thunai": "With the grace of Lord Vinayagar",
  } as Record<string, string>,
  wording: "Family wording",
  wordingIntro: "Guests read these under the card. Leave any of them empty.",
  wordingLabels: {
    blessingsFrom: "Blessings from",
    requesters: "Hosted by",
    welcome: "Waiting to welcome you",
    children: "The children's line",
  },
  ceremonies: "Ceremony names",
  ceremoniesIntro: "Functions take their local names on the guest page.",
};

/** Each design's name and one line about it, as the design step shows them. */
export const designCopy: Record<TemplateId, { name: string; description: string }> =
  Object.fromEntries(
    TEMPLATE_IDS.map((id) => [
      id,
      { name: TEMPLATES[id].name, description: TEMPLATES[id].description },
    ]),
  ) as Record<TemplateId, { name: string; description: string }>;

export const occasionCopy = {
  group: "Occasions",
  setsUp: "What this sets up",
  planned: "Functions planned",
  questions: "Guests are asked",
  noQuestions: "Just whether they're coming and how many",
  designs: (count: number) => (count === 1 ? "1 suggested design" : `${count} suggested designs`),
  suggestedBadge: "Suggested",
  suggestedFor: (occasion: string) => `Suggested for ${occasion.toLowerCase()}`,
  moreDesigns: "More designs",
} as const;

export const previewCopy = {
  ready: "Your invitation is ready",
  live: "Your invitation is live",
  liveBody: (link: string) =>
    `Guests open it at ${link}. Changes you make here show there straight away.`,
  readyBody:
    "It's saved on this device. Sign in to keep it in your account and publish it, then share the link on WhatsApp.",
  readyBodyAccount:
    "It's saved to your account, photos included. Publish it to get your link, then share it on WhatsApp.",
  notReady: "A few details are missing",
  fix: (label: string) => `Finish ${label.toLowerCase()}`,
  occasionHeading: "Occasion",
  functionsHeading: "Functions",
  photosHeading: "Photos",
  noPhotos: "No photos added",
  musicHeading: "Music",
  playsOnOpen: "plays as guests open the card",
  dressCode: "Dress code",
  edit: "Edit",
  editStep: (label: string) => `Edit ${label.toLowerCase()}`,
  startOver: "Start a new invite",
  startOverTitle: "Start a new invite?",
  startOverBody: "This clears the names, functions and photos saved on this device.",
  startOverConfirm: "Clear and start again",
  startOverKeepBody:
    "This invite stays in My invites, so you can come back to it. The new one starts empty.",
  startOverKeepConfirm: "Start a new invite",
  cancel: "Keep this invite",
  cleared: "Started a new invite",
} as const;

/** The event pages' themes (Step 12e): a name, the place it paints, and its fit. */
export const suiteCopy = {
  heading: "Event pages",
  intro:
    "After the doors open, each function gets its own full-screen page in this theme. Your tradition's ceremony names, blessing and symbol stay the same in every theme.",
  suggested: "Suits your tradition",
  pairs: (design: string) => `Also switches the card to ${design}`,
  preview: "Play the pages",
  textBox: "Box behind the words",
  textBoxHint:
    "Off, the words sit straight on the painting. On, they sit in a soft card-coloured box. Play the pages to compare; the same switch is on the pages too.",
  formatHeading: "Kind of invitation",
  formats: {
    scene: {
      name: "Scene",
      description:
        "Everything on one painting: your photos, names and every celebration flying in by turn. Quick for guests to take in.",
    },
    story: {
      name: "Story",
      description: "A full-screen painted page for every celebration, one after another.",
    },
  },
  blessingPage: "Open with the blessing page",
  blessingPageHint:
    "This theme opens with a painting of the god and your blessing beneath it, before your names.",
  names: {
    "rajwada-bagh": "Rajwada Bagh",
    "shahi-savari": "Shahi Savari",
    kayal: "Kayal",
    "noor-bagh": "Noor Bagh",
    "phulkari-haveli": "Phulkari Haveli",
    rajbari: "Rajbari",
    "peshwai-wada": "Peshwai Wada",
    "kutch-toran": "Kutch Toran",
    gubbara: "Gubbara",
    saath: "Saath",
    rooftop: "Rooftop",
    "ivory-arch": "Ivory Arch",
    gulaab: "Gulaab",
    "deco-noir": "Deco Noir",
    taara: "Taara",
    kaagaz: "Kaagaz",
    mitti: "Mitti",
    neel: "Neel",
    pichwai: "Pichwai",
    tanjore: "Tanjore",
    kashi: "Kashi",
    sagar: "Sagar",
    mysuru: "Mysuru",
    kalamkari: "Kalamkari",
    pattachitra: "Pattachitra",
    chinar: "Chinar",
    "chai-bagan": "Chai Bagan",
    "sufi-raat": "Sufi Raat",
    chapel: "Chapel",
    sakura: "Sakura",
    vigna: "Vigna",
    himani: "Himani",
    van: "Van",
    riad: "Riad",
    palna: "Palna",
    deepotsav: "Deepotsav",
    "jungle-party": "Jungle Party",
    "udaipur-lake": "Udaipur Lake",
    "space-voyage": "Space Voyage",
    "rainbow-unicorn": "Rainbow Unicorn",
    "dino-jungle": "Dino Jungle",
    "ocean-pearl": "Ocean Pearl",
    "boho-onederland": "Boho Onederland",
    "fairytale-castle": "Fairytale Castle",
    "little-racer": "Little Racer",
    "gold-gala": "Gold Gala",
    "amrit-utsav": "Amrit Utsav",
    "silver-jubilee": "Silver Jubilee",
    "golden-jubilee": "Golden Jubilee",
    "oh-baby": "Oh Baby",
    "new-year-eve": "New Year's Eve",
    "kitty-tea": "Kitty Tea",
    "pool-party": "Pool Party",
    "baraat-band": "Baraat Band",
    "roka-shagun": "Roka Shagun",
    "chooda-ceremony": "Chooda Ceremony",
    "rishikesh-ganga": "Rishikesh Ganga",
    "jaisalmer-dunes": "Jaisalmer Dunes",
    "fort-night": "Fort Night",
    "sheesh-mahal": "Sheesh Mahal",
    "white-rann": "White Rann",
    annaprashan: "Annaprashan",
    "christening-lilies": "Christening Lilies",
    "new-home-modern": "New Home",
    satyanarayan: "Satyanarayan Katha",
    "mata-ki-chowki": "Mata ki Chowki",
    upanayana: "Upanayana",
    shraddhanjali: "Shraddhanjali",
    "retirement-garden": "Retirement Garden",
    "farewell-night": "Farewell Night",
    "grand-opening": "Grand Opening",
    "launch-stage": "Launch Stage",
    "ganesh-utsav": "Ganesh Utsav",
    "durga-pujo": "Durga Pujo",
    janmashtami: "Janmashtami",
    "onam-pookalam": "Onam Pookalam",
    "pongal-kolam": "Pongal Kolam",
    "uttarayan-kites": "Uttarayan Kites",
    "lohri-bonfire": "Lohri Bonfire",
    "iftar-dawat": "Iftar Dawat",
    "mameru-bandhani": "Mameru Bandhani",
    "sindhi-ajrak": "Sindhi Ajrak",
    "hampi-ruins": "Hampi Ruins",
    "coorg-estate": "Coorg Estate",
    "bali-garden": "Bali Garden",
    "santorini-white": "Santorini White",
    "glass-house": "Glass House",
    "minimal-white": "Minimal White",
    "fairy-forest": "Fairy Forest",
    "love-letter": "Love Letter",
    "parsi-chalk": "Parsi Chalk",
    "jazz-lounge": "Jazz Lounge",
    "bride-squad": "Bride Squad",
    "teej-jhoola": "Teej Jhoola",
    "cricket-stadium": "Cricket Stadium",
    "neon-arcade": "Neon Arcade",
    "retro-bollywood": "Retro Bollywood",
    "pink-haveli": "Gulabi Haveli",
    "char-bagh": "Char Bagh",
    "kashi-ghat": "Kashi Ghat",
    "temple-pond": "Temple Pond",
    "kovil-corridor": "Kovil",
    "arati-mandap": "Pelli Pandiri",
    "zamindar-bari": "Zamindar Bari",
    "kutch-bhunga": "Bhunga",
    "punjab-haveli": "Sarson Haveli",
    "pune-wada": "Wada Angan",
    "chinar-dal": "Dal Lake",
    classic: "Card colours",
  },
  descriptions: {
    "rajwada-bagh": "A palace garden seen through a Mughal arch, fountains and lanterns.",
    "shahi-savari": "A royal elephant procession before a desert fort, bunting overhead.",
    kayal: "A houseboat on the Kerala backwaters, palms and floating lamps.",
    "noor-bagh": "A Mughal garden of white marble, jaali screens and a long water channel.",
    "phulkari-haveli":
      "A Punjab haveli dressed in phulkari, with dhol, marigolds and mustard fields.",
    rajbari: "An old Bengal mansion in red and white, with banana plants and shola flowers.",
    "peshwai-wada": "A Peshwa-era wooden wada in paithani colours, with rangoli and mango leaves.",
    "kutch-toran": "A Kutch bhunga courtyard in mirror work and bandhani, the white Rann beyond.",
    gubbara: "A pastel garden arch of balloons and bunting, with the cake table beneath.",
    saath: "Red roses and candlelight over a lake at sunset, for years together.",
    rooftop: "A city rooftop at night with fairy lights, floor cushions and fireworks.",
    "ivory-arch": "Modern and calm: ivory arches, pampas grass and soft sunlight by the sea.",
    gulaab: "Loose watercolour roses and peonies on white paper.",
    "deco-noir": "Black and gold art deco, like a grand 1920s hotel ballroom.",
    taara: "A midnight sky of gold moons, stars and soft clouds.",
    kaagaz: "Layers of pastel cut paper, with lotuses, jaali and real depth.",
    mitti: "A boho desert wedding: terracotta arches, pampas grass and the dunes.",
    neel: "Jaipur blue pottery: cobalt and turquoise tiles on white marble.",
    pichwai: "A Nathdwara Pichwai of lotus ponds and cows, opening with Shrinathji.",
    tanjore: "A Thanjavur painting in gold leaf and gems, opening with Ganesha.",
    kashi: "The ghats of Banaras at dawn, opening with Ganesha, lamps on the Ganga.",
    sagar: "A beach wedding: white drapes, palms and a pastel sunset over the sea.",
    mysuru: "Mysuru Palace lit for Dasara in Mysore gold painting, opening with Ganesha.",
    kalamkari:
      "Hand-painted Kalamkari cloth of lotuses and peacocks, opening with Lord Venkateswara.",
    pattachitra: "A bright Odisha Pattachitra scroll, opening with Lord Jagannath.",
    chinar: "Kashmir in autumn: Dal Lake, shikaras, chinar leaves and carved walnut wood.",
    "chai-bagan": "Assam's tea gardens in gamosa red and white, with Bihu drums by the river.",
    "sufi-raat": "A moonlit Sufi courtyard of lanterns, roses and still water.",
    chapel: "A white garden chapel with lilies, opening with a stained glass window.",
    sakura: "Cherry blossoms over a wooden bridge, a still pond and paper lanterns.",
    vigna: "A Tuscan vineyard at golden hour, with olive trees and a stone villa.",
    himani: "Snowy mountains, a pine forest and warm winter lights.",
    van: "An enchanted forest of moss, ferns, fairy lights and fireflies.",
    riad: "A Moroccan riad of tiled fountains, arches and brass lanterns.",
    palna: "A flower swing cradle among soft pastel clouds.",
    deepotsav: "A Diwali night of diyas, rangoli and fireworks, opening with Lakshmi and Ganesha.",
    "jungle-party": "A storybook jungle of friendly animals, balloons and big leaves.",
    "udaipur-lake": "Lake Pichola at dusk, with a white marble jharokha for each celebration.",
    "space-voyage": "A porthole among the planets, with a starship plaque for each celebration.",
    "rainbow-unicorn": "Candy clouds and a rainbow, with a unicorn keeping watch.",
    "dino-jungle": "A volcano jungle with a friendly dinosaur and a wooden sign.",
    "ocean-pearl": "Under the sea in shells and pearls, with sunlight from above.",
    "boho-onederland": "Soft neutrals, pampas grass and a rattan mirror for a first birthday.",
    "fairytale-castle": "A pink sunset castle with a carriage and a gilded scroll.",
    "little-racer": "A race track with checkered flags, trophies and two little cars.",
    "gold-gala": "Black and gold art deco, with candles and white roses.",
    "amrit-utsav": "Brass lamps and marigolds for a 60th, 75th or 100th birthday.",
    "silver-jubilee": "Silver, white roses and a lake at dusk for 25 years together.",
    "golden-jubilee": "A gold frame, a gramophone and sunset light for 50 years together.",
    "oh-baby": "Hot air balloons in a pastel sky, with teddies below.",
    "new-year-eve": "Fireworks over the city, with champagne and gold balloons.",
    "kitty-tea": "Peonies, macarons and fine china for a ladies' afternoon.",
    "pool-party": "A blue pool, hibiscus and a float ring on a summer day.",
    "baraat-band": "A palace street at dusk, with the band, the brass and a white mare waiting.",
    "roka-shagun": "A red wall, shagun trays and gold for the first promise.",
    "chooda-ceremony": "Red and ivory bangles, kaleere and marigolds in a haveli courtyard.",
    "rishikesh-ganga": "Marigold garlands over the Ganga, with diyas floating at dusk.",
    "jaisalmer-dunes": "Golden sand, a carved jharokha and lanterns under a desert sky.",
    "fort-night": "A lit fort across a dark lake, with marigolds and lamps.",
    "sheesh-mahal": "A hall of mirrors glowing gold, with a red carpet and lamps.",
    "white-rann": "The salt desert of Kutch under a soft sky, with lanterns and jasmine.",
    annaprashan: "A banana-leaf wreath, a silver bowl of kheer and soft morning light.",
    "christening-lilies": "White lilies, olive leaves and a fountain by the sea.",
    "new-home-modern": "A sunlit balcony with plants, lanterns and a swing.",
    satyanarayan: "Brass kalash, banana leaves and marigolds for the katha.",
    "mata-ki-chowki": "Red velvet, marigold garlands and rows of diyas for the jagran.",
    upanayana: "Carved stone, jasmine and morning calm for the sacred thread.",
    shraddhanjali: "White tuberoses and soft light for a prayer meeting.",
    "retirement-garden": "A garden terrace at sunset, looking over the hills.",
    "farewell-night": "Fairy lights over a college courtyard under the stars.",
    "grand-opening": "A red ribbon, marigold pillars and brass urns for the first day.",
    "launch-stage": "A dark stage, a glowing screen and rows of seats.",
    "ganesh-utsav": "Marigolds, roses and banana leaves to welcome Bappa.",
    "durga-pujo": "Red and white shola work, dhak and diyas for the pujo.",
    janmashtami: "Peacock feathers, a flute and a midnight sky for Kanha.",
    "onam-pookalam": "A pookalam, a flower garland and the backwaters in the sun.",
    "pongal-kolam": "Clay pots of pongal, sugarcane and a kolam at the door.",
    "uttarayan-kites": "Bright kites over the rooftops on a clear January sky.",
    "lohri-bonfire": "A village courtyard at night, phulkari and the bonfire glow.",
    "iftar-dawat": "A jali arch, lanterns and dates at sunset for the iftar.",
    "mameru-bandhani": "Bandhani silks, brass and gifts for the mameru.",
    "sindhi-ajrak": "Indigo and madder ajrak, roses and tassels for a Sindhi wedding.",
    "hampi-ruins": "Stone steps, brass lamps and jasmine among the old temples.",
    "coorg-estate": "Mist over a coffee estate, with berries and white blossoms.",
    "bali-garden": "A lotus pond, frangipani and floating candles in the tropics.",
    "santorini-white": "White walls, blue sea and bougainvillea at sunset.",
    "glass-house": "A sunlit conservatory with eucalyptus, roses and candles.",
    "minimal-white": "White flowers, a marble ledge and quiet candlelight.",
    "fairy-forest": "Fireflies, a misty lake and old trees wrapped in lights.",
    "love-letter": "A sealed envelope, roses and an old pen, to save the date.",
    "parsi-chalk": "Sage walls, lace and roses, with chalk patterns on the floor.",
    "jazz-lounge": "Emerald velvet, brass and coupes for a night of music.",
    "bride-squad": "Blush peonies, macarons and a pink bow for the bride's friends.",
    "teej-jhoola": "A flower swing in the monsoon, with a peacock and green bangles.",
    "cricket-stadium": "A green pitch, stumps, a bat and a gold trophy.",
    "neon-arcade": "Neon lights, game pads and popcorn for a night of games.",
    "retro-bollywood": "Marquee lights, a red curtain and film reels for a filmi night.",
    "pink-haveli": "Jaipur's pink sandstone walls, with a mirror-work tablet for each celebration.",
    "char-bagh": "A Mughal garden of long pools and fountains, with an inlaid marble plaque.",
    "kashi-ghat": "The Ganga's ghats at sunrise, with a brass thali ringed in petals.",
    "temple-pond": "A Kerala temple pond with lotuses, and a palm leaf edged in kasavu gold.",
    "kovil-corridor":
      "A Tamil temple's golden stone corridor, with a brass plate edged in kolam dots.",
    "arati-mandap": "A Telugu banana-leaf mandap, with a turmeric cloth under a mango-leaf toran.",
    "zamindar-bari": "A red Bengal courtyard, with a white shola-pith plaque.",
    "kutch-bhunga": "A white Kutch bhunga, with a lippan panel of mud and mirrors.",
    "punjab-haveli": "A Punjab haveli over golden mustard fields, with a phulkari cloth.",
    "pune-wada":
      "A Maharashtrian wada courtyard, with a Paithani silk panel and its peacock border.",
    "chinar-dal": "Autumn on Dal Lake, with a carved walnut panel among the chinar leaves.",
    classic: "Pages in your card's own paper and colours, with a scene for each function.",
  },
} as const;

/** The editor's live page and lettering (Step 12n). */
export const studioCopy = {
  views: "Show",
  pages: "Pages",
  card: "Card",
  pagesHint: "The page you're editing comes up here as you type.",
  pageNames: {
    blessing: "Blessing",
    cover: "Cover",
    couple: "Photo",
    family: "Family",
    "family-more": "Family, more",
    invite: "Invitation",
    reply: "Reply",
  },
  pageList: "Pages of the invitation",
  showPage: (name: string) => `Show the ${name} page`,
  phone: (name: string) => `The ${name} page, as guests see it`,
  lettering: "Lettering",
  letteringIntro:
    "Choose how the words look on every page. Only fonts that can write your card's language are listed.",
  namesFont: "Names",
  wordsFont: "Other words",
  themeFont: "The theme's own",
  size: "Size",
  sizes: { small: "Small", medium: "Medium", large: "Large" },
  style: "Style of the names",
  bold: "Bold",
  italic: "Italic",
  capitals: "Capitals",
  colour: "Colour of the names",
  colours: {
    theme: "The theme's own",
    maroon: "Maroon",
    gold: "Gold",
    saffron: "Saffron",
    ink: "Ink",
    ivory: "Ivory",
  },
  feels: {
    classic: "Classic",
    script: "Flowing",
    bold: "Bold",
    clean: "Clean",
    handwritten: "Handwritten",
  },
  reset: "Back to the theme's lettering",
} as const;

/** The family section of the names step (Step 12s): parents, blessings and whom to call. */
export const familyCopy = {
  heading: "Family",
  intro:
    "Parents, blessings and whom guests can call. All optional: what you fill in appears on the family page.",
  open: "Add family details",
  sideHeading: (name: string) => `${name}'s family`,
  sideFallback: { first: "First family", second: "Second family" },
  relation: "Printed as",
  relations: { child: "Child of", daughter: "Daughter of", son: "Son of" },
  parents: "Parents' names",
  parentsExample: "Smt. Sunita & Shri Ramesh Patel",
  parentsHint: "Write them as you want them printed, with Shri, Smt. or Late.",
  town: "Home town",
  townExample: "Ahmedabad",
  more: "Blessings and hosts",
  examples: {
    blessingsFrom: "Smt. Kamla & Shri Ramprasad Sharma",
    requesters: "The Sharma family",
    welcome: "Rahul, Priya and Ankit",
    children: "Don't miss our chachu's wedding!",
  },
  memory: "In loving memory",
  memoryExample: "Late Shri Mohanlal Patel",
  memoryHint: "Late relatives whose blessings the family remembers.",
  contacts: "Whom guests can call",
  contactName: "Name",
  contactNameExample: "Ramesh Patel",
  phone: "Phone",
  addContact: "Add a number",
  removeContact: (n: number) => `Remove number ${n}`,
} as const;

/** Editing one page's words and where they sit (Step 12s part 3). */
export const pageWordsCopy = {
  open: "Edit this page",
  title: (page: string) => `The ${page} page`,
  description: "Change any line, add your own, and choose where the words sit on the painting.",
  close: "Done",
  words: "Words",
  line: (n: number) => `Line ${n}`,
  kind: (n: number) => `Kind of line ${n}`,
  kinds: {
    label: "Small heading",
    script: "Blessing",
    display: "Large",
    date: "Date",
    venue: "Venue",
    body: "Text",
    small: "Small text",
  },
  up: (n: number) => `Move line ${n} up`,
  down: (n: number) => `Move line ${n} down`,
  remove: (n: number) => `Remove line ${n}`,
  add: "Add a line",
  reset: "Back to the suggested words",
  own: "You've written this page yourself. Names, dates and places you change later won't show here until you go back to the suggested words.",
  inLanguage: (language: string) => `These words are for the ${language} card.`,
  overflow:
    "Too many words for this painting, even at the smallest size. Shorten a line or remove one.",
  placement: "Placement",
  place: "Position",
  places: { top: "Top", middle: "Middle", bottom: "Bottom" },
  align: "Alignment",
  aligns: { center: "Centred", start: "Left" },
  box: "Box behind the words",
  boxes: { theme: "Like the other pages", on: "Box", off: "Printed on the painting" },
  hide: "Leave this page out",
  hideHint: "Guests won't see it. Turn it back on any time.",
  hidden: "Left out",
} as const;

/** Writing the pages with AI (Step 12s part 4). */
export const aiCopy = {
  open: "Write with AI",
  title: "Write the words with AI",
  description:
    "AI writes the pages in the card's language from your names, family and functions. Change anything afterwards.",
  close: "Close",
  tone: "Tone",
  tones: { traditional: "Traditional", warm: "Warm", fun: "Fun" },
  scope: "Pages",
  scopes: { all: "Every page", page: (page: string) => `Only the ${page} page` },
  write: "Write",
  again: "Write again",
  shorten: "Shorten with AI",
  busy: "Writing…",
  done: "Written. Open any page to change its words.",
  left: (n: number) =>
    n === 1 ? "1 free draft left on this invite." : `${n} free drafts left on this invite.`,
  languages: (language: string) =>
    `Written for the ${language} card. Switch the card's language above to write the other.`,
  errors: {
    "sign-in": "Sign in so your invite is saved, then AI can write for it.",
    off: "AI wording isn't switched on yet.",
    "not-found": "Sign in so your invite is saved, then AI can write for it.",
    "used-up":
      "This invite has used its 3 free drafts. Premium, Royal and the Wedding bundle can write as often as you like.",
    failed: "The words couldn't be written just now. Try again.",
  },
} as const;
