import type { GuestText } from "@/i18n/copy/guest";
import { site } from "@/lib/site";

/*
 * मराठी: पाहुण्यांचे पान, उत्तर आणि फोटो भिंत. English: src/content/publish.ts and
 * src/content/photo-wall.ts. Drafts for a native proofreader.
 */

const photos = (count: number) =>
  count === 1 ? "1 फोटो" : `${count.toLocaleString("en-IN")} फोटो`;

export const guestText: GuestText = {
  guestCopy: {
    metaTitle: (names, occasion) => `${names} · ${occasion} निमंत्रण`,
    metaDescription: (when, where) =>
      [when, where].filter(Boolean).join(" · ") ||
      "आपणास निमंत्रण आहे. तपशील पाहण्यासाठी निमंत्रण उघडा.",
    invited: "आपणास निमंत्रण आहे",
    openHint: "उघडण्यासाठी कार्डवर टॅप करा",
    doorway: {
      open: "निमंत्रण उघडा",
      again: "पुन्हा उघडा",
      counting: "सोहळ्याची उलटी गणती",
      details: "सविस्तर पाहा",
      skip: "पुढे चला",
    },
    countdown: {
      days: (n) => `अजून ${n} दिवस`,
      tomorrow: "उद्या",
      today: "आज",
    },
    reply: "निमंत्रणाला उत्तर द्या",
    functions: "सोहळे",
    family: "कुटुंबाकडून सप्रेम",
    cardLanguage: "कार्डची भाषा",
    timeRange: (start, end) => `${start} ते ${end}`,
    when: "केव्हा",
    where: "कुठे",
    dressCode: "पोशाख",
    directions: "रस्ता",
    parking: "पार्किंग",
    showMap: "नकाशा",
    hideMap: "नकाशा लपवा",
    mapTitle: (place) => `${place} चा नकाशा`,
    eventDay: {
      now: "आता सुरू आहे",
      later: "आज नंतर",
      at: (name, time) => (time ? `${name}, ${time}` : name),
      details: "तपशील",
      dismiss: "ही पट्टी लपवा",
    },
    addToCalendar: "कॅलेंडरमध्ये जोडा",
    googleCalendar: "Google कॅलेंडर",
    appleCalendar: "Apple, Outlook आणि इतर",
    addAll: "सर्व कॅलेंडरमध्ये जोडा",
    photos: "फोटो",
    photoAlt: (index) => `कुटुंबाचा फोटो ${index}`,
    madeWith: `${site.nameDevanagari}ने बनवलेले`,
    createYours: "आपले स्वतःचे निमंत्रण बनवा",
    notFoundTitle: "हे निमंत्रण उपलब्ध नाही",
    notFoundBody:
      "लिंक कदाचित चुकीची आहे, किंवा कुटुंबाने ते पाठवणे थांबवले आहे. त्यांना पुन्हा पाठवायला सांगा.",
    home: `${site.nameDevanagari}वर जा`,
    scene: {
      label: "एकामागून एक सर्व सोहळे",
      previous: "मागील सोहळा",
      next: "पुढील सोहळा",
      pause: "सोहळे थांबवा",
      play: "सोहळे चालू करा",
      position: (n, total) => `${total} पैकी ${n}`,
      details: "सर्व तपशील",
      initials: "इथे आपला फोटो येईल",
    },
    themed: {
      invitedTo: "आनंदाने आपणास सोहळ्याचे निमंत्रण",
      shower: "जोडप्यावर फुले उधळा",
      showered: "आपली फुले जोडप्याकडे निघाली आहेत.",
      music: { play: "संगीत लावा", pause: "संगीत थांबवा" },
      lamps: {
        diyas: "दिवे लावा",
        lanterns: "कंदील लावा",
        nilavilakku: "समई लावा",
        fairy: "रोषणाई करा",
      },
      lampsLabel: "जोडप्यासाठी एक दिवा लावा",
      lit: "धन्यवाद. जोडप्यासाठी आपला दिवा लागला आहे.",
      blessingLabel: "वडीलधाऱ्यांच्या आशीर्वादाने",
      eventsLabel: "सकाळपासून रात्रीपर्यंत",
      saveDateLabel: "तारीख लक्षात ठेवा",
      saveDate: "शुभ तिथी",
      photosLabel: "आठवणी",
      familyLabel: "कुटुंबासह",
      replyLabel: "आपले उत्तर",
      closing:
        "आपली उपस्थिती हीच आमच्यासाठी सर्वात मोठी भेट. आपल्यासोबत सोहळा साजरा करण्याची वाट पाहत आहोत.",
    },
  },
  rsvpCopy: {
    heading: "आपण नक्की याल ना?",
    intro: "प्रत्येक सोहळ्यासाठी उत्तर द्या. आपले उत्तर या पानावरून केव्हाही बदलता येईल.",
    yourName: "आपले नाव",
    namePlaceholder: "कुटुंब आपल्याला ओळखते त्या नावाने",
    nameRequired: "कृपया आपले नाव लिहा",
    acceptAll: "सर्व सोहळ्यांना येत आहोत",
    statuses: {
      attending: { label: "आनंदाने येत आहोत", short: "येत आहोत" },
      maybe: { label: "अजून नक्की नाही", short: "कदाचित" },
      declined: { label: "क्षमस्व, येऊ शकणार नाही", short: "येऊ शकणार नाही" },
    },
    statusGroup: (name) => `${name} साठी आपले उत्तर`,
    chooseOne: "एक उत्तर निवडा",
    adults: "मोठे",
    children: "मुले",
    fewer: (what) => `${what} कमी करा`,
    more: (what) => `${what} वाढवा`,
    questionsHeading: "कुटुंबासाठी काही माहिती",
    optional: "ऐच्छिक",
    yes: "हो",
    no: "नाही",
    choose: "निवडा",
    meal: { veg: "शाकाहारी", jain: "जैन", "non-veg": "मांसाहारी", vegan: "व्हीगन" },
    message: "कुटुंबासाठी संदेश",
    messagePlaceholder: "आशीर्वाद, शुभेच्छा, किंवा त्यांना कळायला हवे असे काहीही",
    send: "उत्तर पाठवा",
    update: "उत्तर बदला",
    sending: "पाठवत आहोत…",
    failed: "आपले उत्तर पाठवता आले नाही. इंटरनेट तपासा आणि पुन्हा प्रयत्न करा.",
    missing: "हे निमंत्रण आता उत्तरे घेत नाही.",
    notInvited: "ही लिंक त्यांपैकी कोणत्याही सोहळ्यासाठी नाही. कुटुंबाला तपासायला सांगा.",
    fixErrors: (count) =>
      count === 1 ? "एक उत्तर अजून बाकी आहे." : `${count} उत्तरे अजून बाकी आहेत.`,
    thanksTitle: (name) => `धन्यवाद, ${name}!`,
    thanksBody: "आपले उत्तर कुटुंबापर्यंत पोहोचले. ते इथे केव्हाही बदलता येईल.",
    change: "माझे उत्तर बदला",
    people: (count) => (count === 1 ? "1 व्यक्ती" : `${count} व्यक्ती`),
  },
  wallCopy: {
    heading: "फोटो भिंत",
    intro: "सोहळ्याचे आपले फोटो जोडा. हे निमंत्रण असलेले सर्वजण ते पाहू शकतात.",
    soon: (date) => `फोटो भिंत ${date} रोजी उघडेल. त्या दिवशी येऊन आपले फोटो शेअर करा.`,
    closed: "फोटो भिंत बंद झाली आहे. फोटो शेअर केल्याबद्दल धन्यवाद.",
    name: "आपले नाव",
    nameHint: "आपल्या फोटोंखाली दिसेल.",
    optional: "ऐच्छिक",
    add: "फोटो जोडा",
    adding: (done, of) => `${of} पैकी ${done} फोटो जोडत आहोत…`,
    added: (count) => `${photos(count)} जोडले. धन्यवाद!`,
    failed: "काही फोटो जोडता आले नाहीत. इंटरनेट तपासा आणि पुन्हा प्रयत्न करा.",
    unreadable: "या फोनला त्यापैकी एक फोटो वाचता आला नाही. JPEG किंवा PNG वापरून पाहा.",
    full: "फोटो भिंत भरली आहे.",
    share: "एका फोनवरून जितके फोटो जोडता येतात तितके आपण जोडले आहेत.",
    tooMany: (max) => `एका वेळी जास्तीत जास्त ${max} फोटो निवडा.`,
    empty: "अजून एकही फोटो नाही. पहिला फोटो आपणच शेअर करा.",
    loading: "फोटो येत आहेत…",
    loadFailed: "फोटो आणता आले नाहीत.",
    retry: "पुन्हा प्रयत्न करा",
    by: (name) => `${name} यांनी शेअर केला`,
    byGuest: "एका पाहुण्याने शेअर केला",
    photoAlt: (name, index) =>
      name ? `${name} यांनी शेअर केलेला फोटो ${index}` : `एका पाहुण्याने शेअर केलेला फोटो ${index}`,
    view: (index) => `फोटो ${index} पाहा`,
    remove: "काढा",
    removeLabel: (index) => `आपला फोटो ${index} काढा`,
    removed: "आपला फोटो काढला.",
    removeFailed: "फोटो काढता आला नाही. पुन्हा प्रयत्न करा.",
    more: "आणखी फोटो दाखवा",
    count: photos,
    close: "बंद करा",
    previous: "मागील फोटो",
    next: "पुढील फोटो",
    viewerTitle: (index, of) => `${of} पैकी फोटो ${index}`,
  },
  questionLabels: {
    meal: "जेवणाची आवड",
    arrival: "पोहोचण्याची तारीख",
    stay: "खोली हवी",
    pickup: "स्टेशन किंवा विमानतळावरून आणायला",
    song: "गाण्याची फर्माईश",
    message: "जोडप्यासाठी संदेश",
  },
  invitation: {
    open: "निमंत्रण उघडा",
    close: "निमंत्रण बंद करा",
    playMusic: "संगीत लावा",
    pauseMusic: "संगीत थांबवा",
    preparing: "3D तयार होत आहे",
    skip: "अ‍ॅनिमेशन वगळा",
    and: "आणि",
    story: {
      story: "निमंत्रण, एकेक पान",
      pause: "पाने थांबवा",
      play: "पुढे चालू ठेवा",
      next: "पुढील पान",
      previous: "मागील पान",
      skip: "थेट कार्डवर जा",
      done: "कार्ड पाहा",
      replay: "निमंत्रणाची पाने चालवा",
      directions: "रस्ता पाहा",
      calendar: "कॅलेंडरमध्ये जोडा",
      textBox: "शब्दांमागे चौकट",
    },
  },
  theme: { group: "रंगसंगती", system: "डिव्हाइसप्रमाणे", light: "फिकट", dark: "गडद" },
};
