import type { FunctionId } from "@/lib/events/functions";
import type { CardLanguage } from "./card-languages";

/*
 * Each function's name as a card in that language prints it, for a card written in another
 * language than its tradition's (a Punjabi family's Gujarati card, or a card with no
 * tradition at all). Hindi and English use the site's own names. Drafts for a native
 * proofreader, like the tradition packs.
 */
export const CARD_FUNCTION_NAMES: Record<
  Exclude<CardLanguage, "en" | "hi">,
  Record<FunctionId, string>
> = {
  mr: {
    roka: "सोयरीक",
    engagement: "साखरपुडा",
    tilak: "टिळा",
    "ganesh-puja": "गणपती पूजन",
    "grah-shanti": "ग्रहशांती",
    mandap: "मांडव",
    mameru: "मामेरू",
    haldi: "हळद",
    mehendi: "मेहंदी",
    sangeet: "संगीत",
    garba: "गरबा",
    bhoj: "भोजन समारंभ",
    baraat: "वरात",
    "baraat-welcome": "वरात स्वागत",
    wedding: "शुभविवाह",
    vidaai: "पाठवणी",
    reception: "स्वागत समारंभ",
    birthday: "वाढदिवस",
    anniversary: "लग्नाचा वाढदिवस",
    party: "पार्टी",
    "baby-shower": "डोहाळे जेवण",
    diwali: "दिवाळी",
    housewarming: "गृहप्रवेश",
    puja: "पूजा",
    "thread-ceremony": "मुंज",
    annaprashan: "उष्टावण",
    christening: "बाप्तिस्मा",
    "prayer-meet": "श्रद्धांजली सभा",
    retirement: "सेवानिवृत्ती सोहळा",
    "farewell-party": "निरोप समारंभ",
    "shop-opening": "शुभ उद्घाटन",
    launch: "शुभारंभ",
    "ganesh-chaturthi": "गणेश चतुर्थी",
    navratri: "नवरात्र",
    janmashtami: "गोकुळाष्टमी",
    onam: "ओणम",
    sankranti: "मकर संक्रांत",
    lohri: "लोहडी",
    eid: "ईद",
  },
  gu: {
    roka: "ચાંદલો",
    engagement: "સગાઈ",
    tilak: "તિલક",
    "ganesh-puja": "ગણેશ સ્થાપના",
    "grah-shanti": "ગ્રહશાંતિ",
    mandap: "મંડપ મુહૂર્ત",
    mameru: "મામેરું",
    haldi: "પીઠી",
    mehendi: "મહેંદી",
    sangeet: "સંગીત સંધ્યા",
    garba: "રાસ ગરબા",
    bhoj: "ભોજન સમારંભ",
    baraat: "જાન પ્રસ્થાન",
    "baraat-welcome": "જાન આગમન",
    wedding: "શુભ લગ્ન",
    vidaai: "કન્યા વિદાય",
    reception: "સ્વાગત સમારંભ",
    birthday: "જન્મદિવસ",
    anniversary: "લગ્નજયંતી",
    party: "પાર્ટી",
    "baby-shower": "સીમંત",
    diwali: "દિવાળી",
    housewarming: "વાસ્તુ પૂજન",
    puja: "પૂજા",
    "thread-ceremony": "જનોઈ",
    annaprashan: "અન્નપ્રાશન",
    christening: "બાપ્તિસ્મા",
    "prayer-meet": "પ્રાર્થનાસભા",
    retirement: "નિવૃત્તિ સમારંભ",
    "farewell-party": "વિદાય સમારંભ",
    "shop-opening": "શુભ ઉદ્ઘાટન",
    launch: "શુભારંભ",
    "ganesh-chaturthi": "ગણેશ ચતુર્થી",
    navratri: "નવરાત્રિ",
    janmashtami: "જન્માષ્ટમી",
    onam: "ઓણમ",
    sankranti: "ઉત્તરાયણ",
    lohri: "લોહરી",
    eid: "ઈદ",
  },
  bn: {
    roka: "পাকা দেখা",
    engagement: "আশীর্বাদ",
    tilak: "তিলক",
    "ganesh-puja": "গণেশ পূজা",
    "grah-shanti": "গ্রহশান্তি",
    mandap: "মণ্ডপ",
    mameru: "তত্ত্ব",
    haldi: "গায়ে হলুদ",
    mehendi: "মেহেন্দি",
    sangeet: "সংগীত সন্ধ্যা",
    garba: "গরবা",
    bhoj: "প্রীতিভোজ",
    baraat: "বরযাত্রা",
    "baraat-welcome": "বরবরণ",
    wedding: "শুভ বিবাহ",
    vidaai: "কনে বিদায়",
    reception: "বউভাত",
    birthday: "জন্মদিন",
    anniversary: "বিবাহবার্ষিকী",
    party: "পার্টি",
    "baby-shower": "সাধ",
    diwali: "দীপাবলি",
    housewarming: "গৃহপ্রবেশ",
    puja: "পূজা",
    "thread-ceremony": "উপনয়ন",
    annaprashan: "অন্নপ্রাশন",
    christening: "ব্যাপটিজম",
    "prayer-meet": "স্মরণসভা",
    retirement: "অবসর সংবর্ধনা",
    "farewell-party": "বিদায় সংবর্ধনা",
    "shop-opening": "শুভ উদ্বোধন",
    launch: "শুভ সূচনা",
    "ganesh-chaturthi": "গণেশ চতুর্থী",
    navratri: "নবরাত্রি",
    janmashtami: "জন্মাষ্টমী",
    onam: "ওনাম",
    sankranti: "পৌষ সংক্রান্তি",
    lohri: "লোহরি",
    eid: "ঈদ",
  },
  ta: {
    roka: "பரிசம்",
    engagement: "நிச்சயதார்த்தம்",
    tilak: "திலகம்",
    "ganesh-puja": "கணபதி பூஜை",
    "grah-shanti": "கிரக சாந்தி",
    mandap: "பந்தக்கால்",
    mameru: "தாய்மாமன் சீர்",
    haldi: "மஞ்சள் நீராட்டு",
    mehendi: "மெஹந்தி",
    sangeet: "சங்கீத்",
    garba: "கர்பா",
    bhoj: "விருந்து",
    baraat: "மாப்பிள்ளை அழைப்பு",
    "baraat-welcome": "ஜானவாசம்",
    wedding: "திருமணம்",
    vidaai: "பெண் அனுப்புதல்",
    reception: "வரவேற்பு",
    birthday: "பிறந்தநாள்",
    anniversary: "திருமண நாள்",
    party: "விருந்து நிகழ்ச்சி",
    "baby-shower": "வளைகாப்பு",
    diwali: "தீபாவளி",
    housewarming: "கிரகப்பிரவேசம்",
    puja: "பூஜை",
    "thread-ceremony": "உபநயனம்",
    annaprashan: "அன்னப்பிராசனம்",
    christening: "ஞானஸ்நானம்",
    "prayer-meet": "நினைவஞ்சலி",
    retirement: "பணி ஓய்வு விழா",
    "farewell-party": "பிரிவு உபசார விழா",
    "shop-opening": "திறப்பு விழா",
    launch: "அறிமுக விழா",
    "ganesh-chaturthi": "விநாயகர் சதுர்த்தி",
    navratri: "நவராத்திரி",
    janmashtami: "கிருஷ்ண ஜெயந்தி",
    onam: "ஓணம்",
    sankranti: "பொங்கல்",
    lohri: "லோஹ்ரி",
    eid: "ஈத்",
  },
};

/** What a card in each language calls the wedding's auspicious time. */
export const CARD_MUHURAT_WORDS: Record<Exclude<CardLanguage, "en">, string> = {
  hi: "शुभ मुहूर्त",
  mr: "शुभ मुहूर्त",
  gu: "શુભ મુહૂર્ત",
  bn: "শুভ লগ্ন",
  ta: "சுப முகூர்த்தம்",
};
